-- The root all-import module: every source file of the project is reachable from here, and
-- `__check__.py` faults the omission, which a build reports as nothing at all.
--
-- A question day's modules carry French quotes, since `20260813` is not an identifier. Only
-- `Development` is imported: `Challenge.lean` shares its namespace and so cannot enter the
-- same environment, and is built by name instead.

import Atlas.Knowledge.AbelianizedGaloisRecovery
import Atlas.Knowledge.AbsoluteDegree
import Atlas.Knowledge.AbsoluteGaloisInvariance
import Atlas.Knowledge.AbsoluteGaloisProsolvability
import Atlas.Knowledge.AbsoluteInertiaDegree
import Atlas.Knowledge.AbsoluteInertiaInvariance
import Atlas.Knowledge.AbsoluteInertiaSubgroup
import Atlas.Knowledge.AbsoluteRamificationIndex
import Atlas.Knowledge.CharacterTwist
import Atlas.Knowledge.ClosedDerivedSeries
import Atlas.Knowledge.CompletedUnitGroup
import Atlas.Knowledge.CyclotomicCharacterInvariance
import Atlas.Knowledge.DigitSum
import Atlas.Knowledge.ElementaryFilteredAut
import Atlas.Knowledge.FiltAut
import Atlas.Knowledge.FiltOrd
import Atlas.Knowledge.FilteredBreak
import Atlas.Knowledge.FilteredComplete
import Atlas.Knowledge.FilteredDefect
import Atlas.Knowledge.FilteredGradedCriterion
import Atlas.Knowledge.FilteredGradedPiece
import Atlas.Knowledge.FilteredIso
import Atlas.Knowledge.FilteredLinear
import Atlas.Knowledge.FilteredModule
import Atlas.Knowledge.FilteredModulePi
import Atlas.Knowledge.FilteredProfiniteGroup
import Atlas.Knowledge.FilteredRhoMap
import Atlas.Knowledge.FreeFiltered
import Atlas.Knowledge.GroupAbsoluteDegree
import Atlas.Knowledge.GroupAbsoluteInertiaDegree
import Atlas.Knowledge.GroupAbsoluteRamificationIndex
import Atlas.Knowledge.GroupResidueCharacteristic
import Atlas.Knowledge.GroupRootOfUnityExponent
import Atlas.Knowledge.HerbrandPhi
import Atlas.Knowledge.HerbrandPsi
import Atlas.Knowledge.HigherUnitGroup
import Atlas.Knowledge.IntegerIsIntegralClosure
import Atlas.Knowledge.IntegralClosureDVR
import Atlas.Knowledge.IsFilteredHom
import Atlas.Knowledge.IsJumpPair
import Atlas.Knowledge.IsJumpSet
import Atlas.Knowledge.IsLadicRepresentation
import Atlas.Knowledge.IsMLFType
import Atlas.Knowledge.IsMStepSolvable
import Atlas.Knowledge.IsMStepSolvableRep
import Atlas.Knowledge.IsMixedCharLocalField
import Atlas.Knowledge.IsProsolvable
import Atlas.Knowledge.JumpMultiplicity
import Atlas.Knowledge.JumpOrder
import Atlas.Knowledge.JumpPairOf
import Atlas.Knowledge.JumpSetEquiv
import Atlas.Knowledge.JumpSetExtremal
import Atlas.Knowledge.JumpSetInduction
import Atlas.Knowledge.JumpSetOf
import Atlas.Knowledge.JumpSetSmall
import Atlas.Knowledge.JumpSetVector
import Atlas.Knowledge.LegendreFormula
import Atlas.Knowledge.LowerRamificationGroup
import Atlas.Knowledge.MStepSolvableCenterBound
import Atlas.Knowledge.MStepSolvableCenterFree
import Atlas.Knowledge.MStepSolvableExtension
import Atlas.Knowledge.MStepSolvableQuotient
import Atlas.Knowledge.MStepSolvableStability
import Atlas.Knowledge.MonogenicIntegralClosure
import Atlas.Knowledge.OutFilt
import Atlas.Knowledge.ParityIndex
import Atlas.Knowledge.QuasiFreeFiltered
import Atlas.Knowledge.RamificationFiltration
import Atlas.Knowledge.RamificationNumber
import Atlas.Knowledge.RamificationNumberEqAddVal
import Atlas.Knowledge.RamificationNumberRestrictScalars
import Atlas.Knowledge.RealHigherUnitGroup
import Atlas.Knowledge.RealLowerRamificationGroup
import Atlas.Knowledge.ResidueCharacteristic
import Atlas.Knowledge.RootOfUnityExponent
import Atlas.Knowledge.Shift
import Atlas.Knowledge.ShiftEPrime
import Atlas.Knowledge.ShiftEStar
import Atlas.Knowledge.ShiftRhoEP
import Atlas.Knowledge.ShiftRhoP
import Atlas.Knowledge.ShiftT
import Atlas.Knowledge.ShiftTStar
import Atlas.Knowledge.SolvabilityDegree
import Atlas.Knowledge.SpanOfOpenUnitSubgroup
import Atlas.Knowledge.StandardFiltered
import Atlas.Knowledge.TRhoEP
import Atlas.Knowledge.UpperRamificationGroup
import Atlas.Knowledge.WildInertiaSubgroup

import Atlas.Questions.«20260813».Development
