import Mathlib
import Atlas.Knowledge.FixingSubgroupAdjoinSimple

/-!
# abelianized Kummer root quotient

The Kummer character of an element, read on the topological abelianization of the absolute
Galois group: when `K` contains the `n`-th roots of unity, every class `g` of `G_K^ab`
multiplies every `n`-th root `β` of `a : Kˣ` in the algebraic closure by one scalar `x : Kˣ`
— `σ β = x β` for every lift `σ` of `g`, the same `x` for every lift and every root. This is
the literature's `φ_a (s) = s (α) / α`, a homomorphism from `G_K` to `μ_n`, descended to the
abelianization: its target is commutative, so it kills the commutator subgroup, and its
kernel is the fixing subgroup of `K⟮β⟯`, closed in the Krull topology, so it kills the
closure too. The item is what makes `Atlas.Knowledge.IsLocalHilbertSymbol` satisfiable: the
symbol's value at `(a, b)` is this scalar at the class `φ (b)` of the reciprocity map.

## Main statements

* `abelianizedKummerRootQuotient` — the scalar exists, uniform over lifts and roots; proved.
* `exists_kummerRootScalar` — one automorphism moves one root by a base scalar; proved.
* `kummerRoot_apply_apply_comm` — two automorphisms act on a root in either order; proved.
* `kummerRoot_apply_eq_self_of_mem_commutator_topologicalClosure` — the closure of the
  commutator subgroup fixes every root; proved.

## Implementation notes

The root quotient `σ β / β` is an `n`-th root of unity of the closure, hence the image of a
power of the base's primitive root (`IsPrimitiveRoot.eq_pow_of_pow_eq_one`), which is what
puts the scalar in `Kˣ` and makes it fixed by every automorphism; that fixedness is the whole
of the commutation lemma, and the commutation lemma applied to the root `τ⁻¹ (ρ⁻¹ β)` is the
whole of the commutator computation. The descent to the closure is
`Subgroup.topologicalClosure_minimal` against `IntermediateField.fixingSubgroup_isClosed`,
read through `Atlas.Knowledge.fixingSubgroupAdjoinSimple`; the fixing subgroup is bound at
the type `Field.absoluteGaloisGroup K` by a `let`, so that the derived topological-group
instance of that type, not the Krull instance of the underlying automorphism group, is the
one synthesized. Nothing about local fields enters — the statement holds over any field with
the roots of unity, and `n ≠ 0` serves root existence alone; the three lemmas on one root —
scalar, commutation, and the roots of unity coming from the base — are stated over an
arbitrary extension `L`, since the finite Kummer extensions downstream need them as much as
the closure does. The source has the finite-level root quotient
(`KummerTheory/Concrete/RootCharacters.lean:75`) on a chosen finite Kummer extension and no
abelianized form; the abelianized statement is this layer's, as
`Atlas.Knowledge.IsLocalHilbertSymbol` is stated against `G_K^ab`.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

namespace Atlas.Knowledge

open scoped commutatorElement

variable {K : Type*} [Field K]

/-- An `n`-th root of unity of an extension `L` is the image of a power of a primitive `n`-th
root of unity of the base: `μ_n` is cyclic, generated by any primitive root, and the base
already holds one. -/
theorem exists_algebraMap_pow_eq_of_pow_eq_one {L : Type*} [Field L] [Algebra K L] {n : ℕ}
    {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0) {ξ : L} (hξ : ξ ^ n = 1) :
    ∃ i : ℕ, algebraMap K L (ζ ^ i) = ξ := by
  haveI : NeZero n := ⟨hn⟩
  obtain ⟨i, -, hi⟩ :=
    (hζ.map_of_injective (algebraMap K L).injective).eq_pow_of_pow_eq_one hξ
  exact ⟨i, by rw [map_pow, hi]⟩

/-- Every automorphism of an extension `L` moves an `n`-th root `β` of `a : Kˣ` by a base
scalar: the root quotient `σ β / β` is an `n`-th root of unity of `L`, hence the image of a
power of the base's primitive root — the literature's `φ_a (s) = s (α) / α` at one `s`
([Serre 1979, Chap. XIV, §2, p.206][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/RootCharacters.lean:75`). -/
theorem exists_kummerRootScalar {L : Type*} [Field L] [Algebra K L] {n : ℕ} {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0) (a : Kˣ) (σ : L ≃ₐ[K] L) {β : L}
    (hβ : β ^ n = algebraMap K L (a : K)) :
    ∃ x : Kˣ, σ β = algebraMap K L (x : K) * β := by
  have ha0 : algebraMap K L (a : K) ≠ 0 := (map_ne_zero (algebraMap K L)).mpr a.ne_zero
  have hβ0 : β ≠ 0 := fun h => by
    rw [h, zero_pow hn] at hβ
    exact ha0 hβ.symm
  have hξ : (σ β / β) ^ n = 1 := by
    rw [div_pow, ← map_pow, hβ, AlgEquiv.commutes, div_self ha0]
  obtain ⟨i, hi⟩ := exists_algebraMap_pow_eq_of_pow_eq_one hζ hn hξ
  refine ⟨Units.mk0 (ζ ^ i) (pow_ne_zero _ (hζ.ne_zero hn)), ?_⟩
  rw [Units.val_mk0, hi, div_mul_cancel₀ _ hβ0]

/-- Two automorphisms of an extension `L` act on an `n`-th root of `a` in either order: each
moves it by a base scalar, and a base scalar is fixed by the other. -/
theorem kummerRoot_apply_apply_comm {L : Type*} [Field L] [Algebra K L] {n : ℕ} {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0) (a : Kˣ) (τ ρ : L ≃ₐ[K] L) {β : L}
    (hβ : β ^ n = algebraMap K L (a : K)) : τ (ρ β) = ρ (τ β) := by
  obtain ⟨x, hx⟩ := exists_kummerRootScalar hζ hn a ρ hβ
  obtain ⟨y, hy⟩ := exists_kummerRootScalar hζ hn a τ hβ
  rw [hx, hy, map_mul, map_mul, AlgEquiv.commutes, AlgEquiv.commutes, hx, hy]
  ring

/-- Every element of the closure of the commutator subgroup of the absolute Galois group
fixes every `n`-th root of a base element: a commutator fixes it by the commutation lemma, so
the commutator subgroup lies in the fixing subgroup of `K⟮β⟯`, which is closed. -/
theorem kummerRoot_apply_eq_self_of_mem_commutator_topologicalClosure {n : ℕ} {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0) (a : Kˣ)
    {β : AlgebraicClosure K} (hβ : β ^ n = algebraMap K (AlgebraicClosure K) (a : K))
    (σ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K)
    (hσ : (σ : Field.absoluteGaloisGroup K) ∈
      (commutator (Field.absoluteGaloisGroup K)).topologicalClosure) :
    σ β = β := by
  haveI : FiniteDimensional K (IntermediateField.adjoin K {β}) :=
    IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral β)
  let H : Subgroup (Field.absoluteGaloisGroup K) :=
    (IntermediateField.adjoin K {β}).fixingSubgroup
  have hmem : ∀ τ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K, τ β = β →
      τ ∈ (IntermediateField.adjoin K {β}).fixingSubgroup := by
    intro τ hτ
    rw [fixingSubgroupAdjoinSimple, MulAction.mem_stabilizer_iff, AlgEquiv.smul_def]
    exact hτ
  have hcomm : commutator (Field.absoluteGaloisGroup K) ≤ H := by
    rw [commutator_def, Subgroup.commutator_le]
    intro τ _ ρ _
    let τ' : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K := τ
    let ρ' : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K := ρ
    have hβ' : (τ'.symm (ρ'.symm β)) ^ n = algebraMap K (AlgebraicClosure K) (a : K) := by
      rw [← map_pow, ← map_pow, hβ, AlgEquiv.commutes, AlgEquiv.commutes]
    have h1 := kummerRoot_apply_apply_comm hζ hn a τ' ρ' hβ'
    rw [AlgEquiv.apply_symm_apply, AlgEquiv.apply_symm_apply] at h1
    exact hmem ⁅τ', ρ'⁆ (by rw [commutatorElement_def]; exact h1)
  have hclosed : IsClosed (H : Set (Field.absoluteGaloisGroup K)) :=
    IntermediateField.fixingSubgroup_isClosed _
  have h2 : (σ : Field.absoluteGaloisGroup K) ∈ H :=
    (commutator (Field.absoluteGaloisGroup K)).topologicalClosure_minimal hcomm hclosed hσ
  exact (IntermediateField.mem_fixingSubgroup_iff _ _).mp h2 β
    (IntermediateField.mem_adjoin_simple_self K β)

/-- **The abelianized Kummer root quotient**: every class of the topological abelianization
of the absolute Galois group multiplies every `n`-th root of `a` by one scalar from `K`, the
same for every lift of the class and every root — the literature's character
`φ_a (s) = s (α) / α`, descended to `G_K^ab` ([Serre 1979, Chap. XIV, §2, p.206][Serre1979];
Yamaguchi 2026, `KummerTheory/Concrete/RootCharacters.lean:75`, the finite-level root
quotient). -/
theorem abelianizedKummerRootQuotient {n : ℕ} (hn : n ≠ 0)
    (hmu : (primitiveRoots n K).Nonempty) (a : Kˣ)
    (g : Field.absoluteGaloisGroupAbelianization K) :
    ∃ x : Kˣ, ∀ σ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K,
      (QuotientGroup.mk (σ : Field.absoluteGaloisGroup K) :
        Field.absoluteGaloisGroupAbelianization K) = g →
      ∀ β : AlgebraicClosure K, β ^ n = algebraMap K (AlgebraicClosure K) (a : K) →
        σ β = algebraMap K (AlgebraicClosure K) ((x : Kˣ) : K) * β := by
  obtain ⟨ζ, hζ⟩ := hmu
  have hζ : IsPrimitiveRoot ζ n := (mem_primitiveRoots (Nat.pos_of_ne_zero hn)).mp hζ
  obtain ⟨σ₀, hσ₀⟩ : ∃ σ₀ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K,
      (QuotientGroup.mk (σ₀ : Field.absoluteGaloisGroup K) :
        Field.absoluteGaloisGroupAbelianization K) = g :=
    QuotientGroup.mk_surjective g
  obtain ⟨β₀, hβ₀⟩ := IsAlgClosed.exists_pow_nat_eq
    (algebraMap K (AlgebraicClosure K) (a : K)) (Nat.pos_of_ne_zero hn)
  obtain ⟨x, hx⟩ := exists_kummerRootScalar hζ hn a σ₀ hβ₀
  refine ⟨x, fun σ hσ β hβ => ?_⟩
  have h1 : σ β₀ = σ₀ β₀ := by
    have hmem : (σ₀ : Field.absoluteGaloisGroup K)⁻¹ * (σ : Field.absoluteGaloisGroup K) ∈
        (commutator (Field.absoluteGaloisGroup K)).topologicalClosure :=
      QuotientGroup.eq.mp (hσ₀.trans hσ.symm)
    have h := kummerRoot_apply_eq_self_of_mem_commutator_topologicalClosure hζ hn a hβ₀
      ((σ₀ : Field.absoluteGaloisGroup K)⁻¹ * (σ : Field.absoluteGaloisGroup K)) hmem
    change σ₀.symm (σ β₀) = β₀ at h
    rw [AlgEquiv.symm_apply_eq] at h
    exact h
  have ha0 : algebraMap K (AlgebraicClosure K) (a : K) ≠ 0 :=
    (map_ne_zero (algebraMap K (AlgebraicClosure K))).mpr a.ne_zero
  have hβ₀0 : β₀ ≠ 0 := fun h => by
    rw [h, zero_pow hn] at hβ₀
    exact ha0 hβ₀.symm
  obtain ⟨i, hi⟩ := exists_algebraMap_pow_eq_of_pow_eq_one hζ hn
    (show (β / β₀) ^ n = 1 by rw [div_pow, hβ, hβ₀, div_self ha0])
  have hβeq : β = algebraMap K (AlgebraicClosure K) (ζ ^ i) * β₀ := by
    rw [hi, div_mul_cancel₀ _ hβ₀0]
  rw [hβeq, map_mul, AlgEquiv.commutes, h1, hx]
  ring

end Atlas.Knowledge
