import Mathlib
import Atlas.Knowledge.IsMixedCharLocalField
import Atlas.Knowledge.ResidueCharacteristic

/-!
# absolute ramification index

The **absolute ramification index** `e_K` of a mixed-characteristic local field: the integer with
`p_K • 𝒪[K] = 𝓂[K] ^ e_K`, for `p_K` the residue characteristic
`Atlas.Knowledge.ResidueCharacteristic`. It is the `e` of every appearance of the shift
`Atlas.Knowledge.ShiftRhoEP` in the arithmetic of `K`—the same `e` that bounds how `p`-powering
moves the filtration `Atlas.Knowledge.HigherUnitGroup`—and one of the six invariants the
anabelian layer recovers group-theoretically.

## Main definitions

* `absoluteRamificationIndex` — the ramification index of `𝓂[K]` over `ℤ`.

## Main statements

* `span_residueCharacteristic_eq_maximalIdeal_pow` — the encoding means what the name says:
  `p_K • 𝒪[K] = 𝓂[K] ^ e_K`.

## Implementation notes

Encoded as Mathlib's `Ideal.ramificationIdx 𝓂[K] ℤ`: the pullback of `𝓂[K]` to `ℤ` is the prime
`(p_K)`, so this is ramification over `ℚ_{p_K}` without carrying a `ℚ_[p]`-algebra structure,
which the carrier `Atlas.Knowledge.IsMixedCharLocalField` deliberately omits. Outside the
mixed-characteristic situation the encoding takes Mathlib's junk values—in equal characteristic
`p` the ideal `p • 𝒪[K]` is `⊥` and the value is `0`.

The encoding is a length, not a valuation: `Ideal.ramificationIdx` is the length of `S_q / p S_q`
over the localization. What connects it back to the `e_K` of the sources is
`span_residueCharacteristic_eq_maximalIdeal_pow`, the well-posedness obligation of this item in
the sense of `Atlas.Knowledge.IsArithmeticFrobenius` and its companions: without it the
definition and its name would be two separate assertions. Every consumer that reads `e_K` as a
valuation rests on it—`Atlas.Knowledge.PadicExpConvergence` and the whole of
`Atlas.Knowledge.PadicExpIsomorphism` state their thresholds in terms of `e_K`, and it is this
theorem that makes those thresholds about the ramification rather than about a length.

The route avoids the localization entirely. `𝒪[K]` is a discrete valuation ring, so every
nonzero element is a unit times a power of a uniformizer and the ideal `p • 𝒪[K]` is `𝓂[K] ^ k`
for a unique `k`; the pullback `(𝓂[K]).under ℤ` is `(p_K)` because the residue field has
characteristic `p_K`; and `Ideal.IsDedekindDomain.ramificationIdx_eq_multiplicity` then reads the
index off as `multiplicity 𝓂[K] (𝓂[K] ^ k)`, which is `k`. The two `synthInstance` bumps are for
the ideal-arithmetic instances on `↥𝒪[K]`, which do not fit the default budget.

## References

* [Hyeon2025] S.-H. Hyeon, *The m-step solvable anabelian geometry of mixed-characteristic local
  fields*, J. London Math. Soc. **112** (2025), e70402.
* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
-/

open ValuativeRel

namespace Atlas.Knowledge

/-- The **absolute ramification index** of a mixed-characteristic local field: the integer `e_K`
with `p_K • 𝒪[K] = 𝓂[K] ^ e_K`, encoded as the ramification index of `𝓂[K]` over `ℤ`
([Hyeon 2025, §3, p.9][Hyeon2025]). -/
noncomputable def absoluteRamificationIndex (K : Type*) [Field K] [ValuativeRel K] : ℕ :=
  Ideal.ramificationIdx 𝓂[K] ℤ

namespace AbsoluteRamificationIndex

variable {K : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K] [IsMixedCharLocalField K]

set_option synthInstance.maxHeartbeats 80000 in
-- The residue-field rewrites go through `IsLocalRing ↥𝒪[K]`, which does not fit the default
-- instance budget.
/-- The prime of `ℤ` below the maximal ideal is the residue characteristic. -/
private theorem under_eq : (𝓂[K]).under ℤ = Ideal.span {(residueCharacteristic K : ℤ)} := by
  haveI := ringChar.charP 𝓀[K]
  ext n
  have hres : IsLocalRing.residue ↥𝒪[K] ((algebraMap ℤ ↥𝒪[K]) n) = (n : 𝓀[K]) := by
    rw [show (algebraMap ℤ ↥𝒪[K]) n = (n : ↥𝒪[K]) by simp, map_intCast]
  rw [Ideal.mem_span_singleton, Ideal.mem_under, ← IsLocalRing.residue_eq_zero_iff, hres]
  exact CharP.intCast_eq_zero_iff 𝓀[K] (ringChar 𝓀[K]) n

set_option synthInstance.maxHeartbeats 80000 in
-- Same instance search as `under_eq`, now under `Ideal.map`.
/-- Pushing that prime back up gives the ideal generated by the residue characteristic. -/
private theorem map_under_eq :
    ((𝓂[K]).under ℤ).map (algebraMap ℤ ↥𝒪[K])
      = Ideal.span {((residueCharacteristic K : ℕ) : ↥𝒪[K])} := by
  rw [under_eq, Ideal.map_span]
  simp

end AbsoluteRamificationIndex

set_option synthInstance.maxHeartbeats 80000 in
-- The ideal arithmetic on `↥𝒪[K]` does not fit the default instance budget.
/-- The absolute ramification index is the exponent it is named for: the ideal generated by the
residue characteristic is the `e_K`th power of the maximal ideal, which is the sources' defining
property `p_K • 𝒪[K] = 𝓂[K] ^ e_K` ([Hyeon 2025, §3, p.9][Hyeon2025];
[Serre 1979, Chap. II, §5, p.36][Serre1979]). -/
theorem span_residueCharacteristic_eq_maximalIdeal_pow (K : Type*) [Field K] [ValuativeRel K]
    [TopologicalSpace K] [IsMixedCharLocalField K] :
    Ideal.span {((residueCharacteristic K : ℕ) : ↥𝒪[K])}
      = 𝓂[K] ^ absoluteRamificationIndex K := by
  have hp : (residueCharacteristic K).Prime := residueCharacteristic_prime K
  have hpne : ((residueCharacteristic K : ℕ) : ↥𝒪[K]) ≠ 0 := by simpa using hp.ne_zero
  -- In a discrete valuation ring the ideal generated by `p` is a power of the maximal ideal.
  obtain ⟨k, hk⟩ : ∃ k, Ideal.span {((residueCharacteristic K : ℕ) : ↥𝒪[K])} = 𝓂[K] ^ k := by
    obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible (↥𝒪[K])
    obtain ⟨k, u, hu⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hpne hϖ
    exact ⟨k, by rw [hu, Ideal.span_singleton_mul_left_unit u.isUnit, hϖ.maximalIdeal_eq,
      Ideal.span_singleton_pow]⟩
  rw [hk]
  congr 1
  -- and that exponent is the ramification index, read off as a multiplicity.
  haveI : (𝓂[K]).IsPrime := (IsLocalRing.maximalIdeal.isMaximal _).isPrime
  have hmap : ((𝓂[K]).under ℤ).map (algebraMap ℤ ↥𝒪[K]) = 𝓂[K] ^ k := by
    rw [AbsoluteRamificationIndex.map_under_eq, hk]
  have hprime : Prime (𝓂[K] : Ideal ↥𝒪[K]) :=
    Ideal.prime_of_isPrime (IsDiscreteValuationRing.not_a_field ↥𝒪[K]) inferInstance
  have hidx := Ideal.IsDedekindDomain.ramificationIdx_eq_multiplicity ((𝓂[K]).under ℤ) 𝓂[K]
    (by rw [hmap]; exact pow_ne_zero _ hprime.ne_zero)
  rw [absoluteRamificationIndex, hidx, hmap, multiplicity_pow_self_of_prime hprime]

end Atlas.Knowledge
