import Mathlib

/-!
# cyclotomic integer basis

The integers of the cyclotomic extension of `ℚ_[p]` inside its algebraic closure: for `ζ` a
primitive `p ^ m`-th root of unity in `PadicAlgCl p`, every element of `ℚ_[p]⟮ζ⟯` of norm at
most one lies in `Algebra.adjoin ℤ_[p] {ζ}`. This is Serre's description of the ring of
integers of the cyclotomic field as generated by `ζ` over `ℤ_[p]`, together with the two
facts it rides on: the cyclotomic polynomial of level `p ^ m` is irreducible over
`ℚ_[p]`—it is the minimal polynomial of `ζ`—and the extension has degree `(p ^ m).totient`.

## Main statements

* `CyclotomicIntegerBasis.isIntegral_of_norm_le_one` — an element of the algebraic closure of
  norm at most one is integral over `ℤ_[p]`: the norm is the spectral norm, so all
  coefficients of the minimal polynomial are `p`-adic integers.
* `CyclotomicIntegerBasis.minpoly_eq_cyclotomic` — the minimal polynomial of `ζ` over
  `ℚ_[p]` is `Polynomial.cyclotomic (p ^ m) ℚ_[p]`.
* `CyclotomicIntegerBasis.finrank_adjoin` — `ℚ_[p]⟮ζ⟯` has degree `(p ^ m).totient` over
  `ℚ_[p]`.
* `cyclotomicIntegerBasis` — the headline: an element of `ℚ_[p]⟮ζ⟯` of norm at most one lies
  in `Algebra.adjoin ℤ_[p] {ζ}`.

## Implementation notes

Serre works with an abstract finite extension of the base field; here everything is stated
inside `PadicAlgCl p`, Mathlib's algebraic closure of `ℚ_[p]` carrying the spectral norm, and
"the ring of integers" becomes the membership statement of the headline. The chain is
Serre's: `ζ - 1` is a root of the Eisenstein polynomial obtained by composing the cyclotomic
polynomial with `X + 1`, which pins down the minimal polynomials of `ζ - 1` and `ζ` at once,
and the Eisenstein shape of `minpoly ℤ_[p] (ζ - 1)` is what lets a `p`-power denominator be
cleared inside `Algebra.adjoin ℤ_[p] {ζ - 1}`. That last step is
`mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt`, applied to the power basis of
`ζ - 1` on the intermediate field `ℚ_[p]⟮ζ⟯`; Mathlib runs the same argument over `ℚ` in
`IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton_of_prime_pow`, but that route
is tied to `ℚ` by its discriminant input, so the Eisenstein leg is rebuilt here over `ℤ_[p]`.
Irreducibility of the composed cyclotomic polynomial descends to `ℤ_[p]` by Eisenstein's
criterion and climbs back to `ℚ_[p]` by Gauss's lemma, `ℤ_[p]` being integrally closed with
fraction field `ℚ_[p]`.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
-/

open Polynomial

open scoped IntermediateField

namespace Atlas.Knowledge

namespace CyclotomicIntegerBasis

variable {p : ℕ} [Fact p.Prime]

/-- An element of the algebraic closure of `ℚ_[p]` of norm at most one is integral over
`ℤ_[p]`: the norm is the spectral norm of the minimal polynomial, so a norm bounded by one
bounds every coefficient of the minimal polynomial, whose lift to `ℤ_[p]` is then a monic
witness—the valuation ring of a finite extension of a complete field is the integral closure
of the valuation ring below ([Serre 1979, Chap. II, §2, Prop. 3, pp.28–29][Serre1979]). -/
theorem isIntegral_of_norm_le_one (x : PadicAlgCl p) (hx : ‖x‖ ≤ 1) :
    IsIntegral ℤ_[p] x := by
  have hint : IsIntegral ℚ_[p] x :=
    ((PadicAlgCl.isAlgebraic p).isAlgebraic x).isIntegral
  have hmono : (minpoly ℚ_[p] x).Monic := minpoly.monic hint
  have hcoeff : ∀ n : ℕ, ‖(minpoly ℚ_[p] x).coeff n‖ ≤ 1 := by
    refine (spectralValue_le_one_iff hmono).mp ?_
    have h1 : spectralValue (minpoly ℚ_[p] x) = ‖x‖ := PadicAlgCl.spectralNorm_eq p x
    rw [h1]
    exact hx
  let c : ℕ → ℤ_[p] := fun n => ⟨(minpoly ℚ_[p] x).coeff n, hcoeff n⟩
  have hmap : (∑ n ∈ Finset.range ((minpoly ℚ_[p] x).natDegree + 1), C (c n) * X ^ n).map
      (algebraMap ℤ_[p] ℚ_[p]) = minpoly ℚ_[p] x := by
    conv_rhs => rw [(minpoly ℚ_[p] x).as_sum_range' _ (Nat.lt_succ_self _)]
    rw [Polynomial.map_sum]
    refine Finset.sum_congr rfl fun n _ => ?_
    rw [Polynomial.map_mul, Polynomial.map_C, Polynomial.map_pow, Polynomial.map_X,
      C_mul_X_pow_eq_monomial]
    rfl
  have hmonic : (∑ n ∈ Finset.range ((minpoly ℚ_[p] x).natDegree + 1),
      C (c n) * X ^ n).Monic :=
    Polynomial.monic_of_injective (IsFractionRing.injective ℤ_[p] ℚ_[p]) (by rwa [hmap])
  refine ⟨_, hmonic, ?_⟩
  rw [← Polynomial.aeval_def, ← Polynomial.aeval_map_algebraMap ℚ_[p], hmap]
  exact minpoly.aeval ℚ_[p] x

/-- Denominators in `ℚ_[p]` are `p`-powers: multiplying by a large enough power of `p` drives
any element into the unit ball `ℤ_[p]`. -/
theorem exists_pow_mul_norm_le_one (c : ℚ_[p]) : ∃ n : ℕ, ‖(p : ℚ_[p]) ^ n * c‖ ≤ 1 := by
  have hp' : p.Prime := Fact.out
  have hp1 : 1 < (p : ℝ) := by exact_mod_cast hp'.one_lt
  obtain ⟨n, hn⟩ := pow_unbounded_of_one_lt ‖c‖ hp1
  refine ⟨n, ?_⟩
  rw [norm_mul, norm_pow, Padic.norm_p]
  calc ((p : ℝ)⁻¹) ^ n * ‖c‖ ≤ ((p : ℝ)⁻¹) ^ n * (p : ℝ) ^ n := by
        have h0 : (0 : ℝ) ≤ ((p : ℝ)⁻¹) ^ n := by positivity
        exact mul_le_mul_of_nonneg_left hn.le h0
    _ = 1 := by
        rw [← mul_pow, inv_mul_cancel₀ (by positivity), one_pow]

/-- The composition of the `p ^ m`-th cyclotomic polynomial over `ℤ_[p]` with `X + 1` is
Eisenstein at `p`: Serre's Eisenstein equation for `ζ - 1`, of degree the totient and with
constant term `p` ([Serre 1979, Chap. IV, §4, proof of Prop. 17, p.78][Serre1979]). The
coefficient conditions transfer from the corresponding fact over `ℤ`,
`cyclotomic_prime_pow_comp_X_add_one_isEisensteinAt`. -/
theorem cyclotomic_comp_isEisensteinAt {m : ℕ} (hm : m ≠ 0) :
    ((cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1)).IsEisensteinAt
      (Ideal.span {(p : ℤ_[p])}) := by
  obtain ⟨k, rfl⟩ : ∃ k, m = k + 1 :=
    ⟨m - 1, (Nat.succ_pred_eq_of_pos (Nat.pos_of_ne_zero hm)).symm⟩
  have hZ := cyclotomic_prime_pow_comp_X_add_one_isEisensteinAt p k
  have hmonicZ : ((cyclotomic (p ^ (k + 1)) ℤ).comp (X + 1)).Monic := by
    simpa using (cyclotomic.monic (p ^ (k + 1)) ℤ).comp_X_add_C 1
  have hmap : ((cyclotomic (p ^ (k + 1)) ℤ).comp (X + 1)).map (Int.castRingHom ℤ_[p])
      = (cyclotomic (p ^ (k + 1)) ℤ_[p]).comp (X + C 1) := by
    rw [Polynomial.map_comp, map_cyclotomic_int]
    simp
  have hmonic : ((cyclotomic (p ^ (k + 1)) ℤ_[p]).comp (X + C 1)).Monic :=
    (cyclotomic.monic (p ^ (k + 1)) ℤ_[p]).comp_X_add_C 1
  have hdeg : ((cyclotomic (p ^ (k + 1)) ℤ_[p]).comp (X + C 1)).natDegree
      = ((cyclotomic (p ^ (k + 1)) ℤ).comp (X + 1)).natDegree := by
    rw [← hmap, hmonicZ.natDegree_map]
  refine ⟨?_, @fun n hn => ?_, ?_⟩
  · rw [hmonic.leadingCoeff]
    intro h1
    rw [Ideal.mem_span_singleton] at h1
    exact PadicInt.prime_p.not_unit (isUnit_of_dvd_one h1)
  · rw [hdeg] at hn
    have h : (p : ℤ) ∣ ((cyclotomic (p ^ (k + 1)) ℤ).comp (X + 1)).coeff n :=
      Ideal.mem_span_singleton.mp (hZ.mem hn)
    refine Ideal.mem_span_singleton.mpr ?_
    rw [← hmap, Polynomial.coeff_map]
    simpa using (Int.castRingHom ℤ_[p]).map_dvd h
  · have h0 : ((cyclotomic (p ^ (k + 1)) ℤ_[p]).comp (X + C 1)).coeff 0 = (p : ℤ_[p]) := by
      rw [Polynomial.coeff_zero_eq_eval_zero, Polynomial.eval_comp]
      simp [Polynomial.eval_one_cyclotomic_prime_pow]
    rw [h0, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    intro hdvd
    obtain ⟨c, hc⟩ := hdvd
    have h1 : (p : ℤ_[p]) * 1 = (p : ℤ_[p]) * ((p : ℤ_[p]) * c) := by
      rw [mul_one, ← mul_assoc, ← sq]
      exact hc
    exact PadicInt.prime_p.not_unit
      (IsUnit.of_mul_eq_one c (mul_left_cancel₀ PadicInt.prime_p.ne_zero h1).symm)

/-- The composition of the `p ^ m`-th cyclotomic polynomial over `ℚ_[p]` with `X + 1` is
irreducible: Eisenstein's criterion over the discrete valuation ring `ℤ_[p]`, then Gauss's
lemma up to the fraction field
([Serre 1979, Chap. IV, §4, proof of Prop. 17, p.78][Serre1979]). -/
theorem cyclotomic_comp_irreducible {m : ℕ} (hm : m ≠ 0) :
    Irreducible ((cyclotomic (p ^ m) ℚ_[p]).comp (X + C 1)) := by
  have hp' : p.Prime := Fact.out
  have hmonicZ : ((cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1)).Monic :=
    (cyclotomic.monic (p ^ m) ℤ_[p]).comp_X_add_C 1
  have hprime : (Ideal.span {(p : ℤ_[p])}).IsPrime :=
    (Ideal.span_singleton_prime PadicInt.prime_p.ne_zero).mpr PadicInt.prime_p
  have hdeg : 0 < ((cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1)).natDegree := by
    rw [Polynomial.natDegree_comp, Polynomial.natDegree_cyclotomic,
      Polynomial.natDegree_X_add_C, mul_one]
    exact Nat.totient_pos.mpr (pow_pos hp'.pos m)
  have hirrZ : Irreducible ((cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1)) :=
    (cyclotomic_comp_isEisensteinAt hm).irreducible hprime hmonicZ.isPrimitive hdeg
  have h := (hmonicZ.irreducible_iff_irreducible_map_fraction_map (K := ℚ_[p])).mp hirrZ
  rwa [Polynomial.map_comp, map_cyclotomic, Polynomial.map_add, Polynomial.map_X,
    Polynomial.map_C, map_one] at h

/-- The minimal polynomial of `ζ - 1` over `ℚ_[p]` is the `p ^ m`-th cyclotomic polynomial
composed with `X + 1`: `ζ - 1` is a root, and the composition is monic and irreducible
([Serre 1979, Chap. IV, §4, proof of Prop. 17, p.78][Serre1979]). -/
theorem minpoly_sub_one_eq {m : ℕ} {ζ : PadicAlgCl p} (hζ : IsPrimitiveRoot ζ (p ^ m))
    (hm : m ≠ 0) :
    minpoly ℚ_[p] (ζ - 1) = (cyclotomic (p ^ m) ℚ_[p]).comp (X + C 1) := by
  have hp' : p.Prime := Fact.out
  refine (minpoly.eq_of_irreducible_of_monic (cyclotomic_comp_irreducible hm) ?_
    ((cyclotomic.monic (p ^ m) ℚ_[p]).comp_X_add_C 1)).symm
  rw [Polynomial.aeval_comp]
  have h1 : (Polynomial.aeval (ζ - 1)) ((X : ℚ_[p][X]) + C 1) = ζ := by simp
  rw [h1, Polynomial.aeval_def, ← Polynomial.eval_map, map_cyclotomic]
  exact hζ.isRoot_cyclotomic (pow_pos hp'.pos m)

/-- The minimal polynomial of a primitive `p ^ m`-th root of unity over `ℚ_[p]` is the
`p ^ m`-th cyclotomic polynomial—equivalently, the cyclotomic polynomial stays irreducible
over `ℚ_[p]` ([Serre 1979, Chap. IV, §4, Prop. 17, p.78][Serre1979]). -/
theorem minpoly_eq_cyclotomic {m : ℕ} {ζ : PadicAlgCl p} (hζ : IsPrimitiveRoot ζ (p ^ m))
    (hm : m ≠ 0) : minpoly ℚ_[p] ζ = Polynomial.cyclotomic (p ^ m) ℚ_[p] := by
  have h1 : minpoly ℚ_[p] (ζ - 1) = (minpoly ℚ_[p] ζ).comp (X + C 1) := by
    simpa using minpoly.sub_algebraMap ζ (1 : ℚ_[p])
  have h2 := (minpoly_sub_one_eq hζ hm).symm.trans h1
  have h3 := congrArg (fun q : ℚ_[p][X] => q.comp (X - C 1)) h2
  simpa [Polynomial.comp_assoc] using h3.symm

/-- The cyclotomic extension `ℚ_[p]⟮ζ⟯` of `ℚ_[p]` by a primitive `p ^ m`-th root of unity
has degree `(p ^ m).totient` ([Serre 1979, Chap. IV, §4, Prop. 17, p.78][Serre1979]). -/
theorem finrank_adjoin {m : ℕ} {ζ : PadicAlgCl p} (hζ : IsPrimitiveRoot ζ (p ^ m))
    (hm : m ≠ 0) : Module.finrank ℚ_[p] ↥(ℚ_[p]⟮ζ⟯) = (p ^ m).totient := by
  have hint : IsIntegral ℚ_[p] ζ := ((PadicAlgCl.isAlgebraic p).isAlgebraic ζ).isIntegral
  rw [IntermediateField.adjoin.finrank hint, minpoly_eq_cyclotomic hζ hm,
    Polynomial.natDegree_cyclotomic]

/-- A primitive `p ^ m`-th root of unity has norm one in the algebraic closure. -/
theorem norm_eq_one {m : ℕ} {ζ : PadicAlgCl p} (hζ : IsPrimitiveRoot ζ (p ^ m)) :
    ‖ζ‖ = 1 := by
  have hp' : p.Prime := Fact.out
  have h1 : ‖ζ‖ ^ (p ^ m) = 1 := by
    rw [← norm_pow, hζ.pow_eq_one, norm_one]
  exact (pow_eq_one_iff_of_nonneg (norm_nonneg ζ) (pow_pos hp'.pos m).ne').mp h1

end CyclotomicIntegerBasis

/-- The **integers of the cyclotomic extension**: an element of `ℚ_[p]⟮ζ⟯` of norm at most
one lies in `Algebra.adjoin ℤ_[p] {ζ}`, for `ζ` a primitive `p ^ m`-th root of unity in the
algebraic closure of `ℚ_[p]`—Serre's generation of the valuation ring by `ζ` alone
([Serre 1979, Chap. IV, §4, Prop. 17, p.78][Serre1979]). The element is integral over
`ℤ_[p]`, a `p`-power multiple of it lies in `Algebra.adjoin ℤ_[p] {ζ - 1}` by clearing
denominators in the power basis of `ζ - 1`, and the Eisenstein shape of
`minpoly ℤ_[p] (ζ - 1)` clears the `p`-power. -/
theorem cyclotomicIntegerBasis {p : ℕ} [Fact p.Prime] {m : ℕ} {ζ : PadicAlgCl p}
    (hζ : IsPrimitiveRoot ζ (p ^ m)) (hm : m ≠ 0) {x : PadicAlgCl p}
    (hx : x ∈ ℚ_[p]⟮ζ⟯) (hnorm : ‖x‖ ≤ 1) :
    x ∈ Algebra.adjoin ℤ_[p] {ζ} := by
  haveI : IsScalarTower ℤ_[p] ↥(ℚ_[p]⟮ζ⟯) (PadicAlgCl p) :=
    ⟨fun a b c => smul_assoc a (b : PadicAlgCl p) c⟩
  have hζint : IsIntegral ℚ_[p] ζ := ((PadicAlgCl.isAlgebraic p).isAlgebraic ζ).isIntegral
  set ζ' : ↥(ℚ_[p]⟮ζ⟯) := IntermediateField.AdjoinSimple.gen ℚ_[p] ζ with hζ'
  have hζ'map : algebraMap ↥(ℚ_[p]⟮ζ⟯) (PadicAlgCl p) ζ' = ζ :=
    IntermediateField.AdjoinSimple.algebraMap_gen _ _
  have hinj : Function.Injective (algebraMap ↥(ℚ_[p]⟮ζ⟯) (PadicAlgCl p)) :=
    (algebraMap ↥(ℚ_[p]⟮ζ⟯) (PadicAlgCl p)).injective
  -- integrality over `ℤ_[p]` of the two elements in play
  have hζsub_norm : ‖ζ - 1‖ ≤ 1 := by
    refine le_trans ?_ (le_of_eq (by rw [CyclotomicIntegerBasis.norm_eq_one hζ, norm_one,
      max_self] : max ‖ζ‖ ‖(1 : PadicAlgCl p)‖ = 1))
    simpa [sub_eq_add_neg] using IsUltrametricDist.norm_add_le_max ζ (-1)
  have hζsub_int : IsIntegral ℤ_[p] (ζ - 1) :=
    CyclotomicIntegerBasis.isIntegral_of_norm_le_one _ hζsub_norm
  have hζ'sub_map : algebraMap ↥(ℚ_[p]⟮ζ⟯) (PadicAlgCl p) (ζ' - 1) = ζ - 1 := by
    rw [map_sub, hζ'map, map_one]
  have hζ'sub_int : IsIntegral ℤ_[p] (ζ' - 1) :=
    (isIntegral_algebraMap_iff hinj).mp (hζ'sub_map ▸ hζsub_int)
  set y : ↥(ℚ_[p]⟮ζ⟯) := ⟨x, hx⟩ with hy
  have hyint : IsIntegral ℤ_[p] y :=
    (isIntegral_algebraMap_iff hinj).mp
      (CyclotomicIntegerBasis.isIntegral_of_norm_le_one x hnorm)
  -- the power basis generated by `ζ' - 1`
  have hζ'int : IsIntegral ℚ_[p] ζ' := (isIntegral_algebraMap_iff hinj).mp
    (by rw [hζ'map]; exact hζint)
  have hζ'sub_intQ : IsIntegral ℚ_[p] (ζ' - 1) := hζ'int.sub isIntegral_one
  have htop : Algebra.adjoin ℚ_[p] {ζ' - 1} = ⊤ := by
    refine PowerBasis.adjoin_eq_top_of_gen_mem_adjoin
      (B := IntermediateField.adjoin.powerBasis hζint) ?_
    change ζ' ∈ Algebra.adjoin ℚ_[p] {ζ' - 1}
    have h1 : (ζ' - 1) + 1 ∈ Algebra.adjoin ℚ_[p] {ζ' - 1} :=
      Subalgebra.add_mem _ (Algebra.self_mem_adjoin_singleton _ _) (Subalgebra.one_mem _)
    simpa using h1
  set B : PowerBasis ℚ_[p] ↥(ℚ_[p]⟮ζ⟯) := PowerBasis.ofAdjoinEqTop hζ'sub_intQ htop with hB
  have hBgen : B.gen = ζ' - 1 := rfl
  -- the minimal polynomial of the generator over `ℤ_[p]` is the shifted cyclotomic
  have hminQ : minpoly ℚ_[p] (ζ' - 1) = (cyclotomic (p ^ m) ℚ_[p]).comp (X + C 1) := by
    rw [← minpoly.algebraMap_eq hinj (ζ' - 1), hζ'sub_map,
      CyclotomicIntegerBasis.minpoly_sub_one_eq hζ hm]
  have hminZ : minpoly ℤ_[p] (ζ' - 1) = (cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1) := by
    have h1 : minpoly ℚ_[p] (ζ' - 1) = (minpoly ℤ_[p] (ζ' - 1)).map (algebraMap ℤ_[p] ℚ_[p]) :=
      minpoly.isIntegrallyClosed_eq_field_fractions' ℚ_[p] hζ'sub_int
    have h2 : ((cyclotomic (p ^ m) ℤ_[p]).comp (X + C 1)).map (algebraMap ℤ_[p] ℚ_[p])
        = (cyclotomic (p ^ m) ℚ_[p]).comp (X + C 1) := by
      rw [Polynomial.map_comp, map_cyclotomic, Polynomial.map_add, Polynomial.map_X,
        Polynomial.map_C, map_one]
    refine Polynomial.map_injective _ (IsFractionRing.injective ℤ_[p] ℚ_[p]) ?_
    rw [← h1, h2, hminQ]
  -- clear denominators: a `p`-power multiple of `y` lies in the adjoin of the generator
  obtain ⟨n, hn⟩ : ∃ n : ℕ, (p : ℤ_[p]) ^ n • y ∈ Algebra.adjoin ℤ_[p] {B.gen} := by
    have hrepr := B.basis.sum_repr y
    choose ns hns using fun i =>
      CyclotomicIntegerBasis.exists_pow_mul_norm_le_one (p := p) (B.basis.repr y i)
    set N := Finset.univ.sup ns with hN
    refine ⟨N, ?_⟩
    rw [← hrepr, Finset.smul_sum]
    refine Subalgebra.sum_mem _ fun i _ => ?_
    have hcoef : ‖(p : ℚ_[p]) ^ N * B.basis.repr y i‖ ≤ 1 := by
      have hle : ns i ≤ N := Finset.le_sup (Finset.mem_univ i)
      have hsplit : (p : ℚ_[p]) ^ N * B.basis.repr y i
          = (p : ℚ_[p]) ^ (N - ns i) * ((p : ℚ_[p]) ^ ns i * B.basis.repr y i) := by
        rw [← mul_assoc, ← pow_add, Nat.sub_add_cancel hle]
      rw [hsplit, norm_mul]
      have h1 : ‖(p : ℚ_[p]) ^ (N - ns i)‖ ≤ 1 := by
        rw [norm_pow, Padic.norm_p]
        exact pow_le_one₀ (by positivity)
          (inv_le_one_of_one_le₀ (by exact_mod_cast (Fact.out : p.Prime).one_le))
      calc ‖(p : ℚ_[p]) ^ (N - ns i)‖ * ‖(p : ℚ_[p]) ^ ns i * B.basis.repr y i‖
          ≤ 1 * 1 := mul_le_mul h1 (hns i) (norm_nonneg _) zero_le_one
        _ = 1 := mul_one 1
    set d : ℤ_[p] := ⟨(p : ℚ_[p]) ^ N * B.basis.repr y i, hcoef⟩ with hd
    have hd_eq : (p : ℤ_[p]) ^ N • B.basis.repr y i = algebraMap ℤ_[p] ℚ_[p] d := by
      rw [Algebra.smul_def, map_pow, map_natCast, PadicInt.algebraMap_apply]
    rw [← smul_assoc, hd_eq, algebraMap_smul]
    refine Subalgebra.smul_mem _ ?_ d
    rw [B.basis_eq_pow i]
    exact Subalgebra.pow_mem _ (Algebra.self_mem_adjoin_singleton _ _) _
  -- the Eisenstein descent removes the `p`-power
  have hyadj : y ∈ Algebra.adjoin ℤ_[p] {B.gen} :=
    mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt PadicInt.prime_p
      (hBgen ▸ hζ'sub_int) hyint hn
      (by rw [hBgen, hminZ]; exact CyclotomicIntegerBasis.cyclotomic_comp_isEisensteinAt hm)
  -- transport the membership down to the algebraic closure
  have hmap_adj : x ∈ Algebra.adjoin ℤ_[p] {ζ - 1} := by
    have himage : (Algebra.adjoin ℤ_[p] {B.gen}).map
        ((IntermediateField.val ℚ_[p]⟮ζ⟯).restrictScalars ℤ_[p])
        = Algebra.adjoin ℤ_[p] {ζ - 1} := by
      rw [AlgHom.map_adjoin]
      congr 1
      rw [Set.image_singleton]
      exact congrArg Set.singleton (hBgen ▸ hζ'sub_map)
    rw [← himage]
    exact ⟨y, hyadj, rfl⟩
  have hle : Algebra.adjoin ℤ_[p] {ζ - 1} ≤ Algebra.adjoin ℤ_[p] {ζ} := by
    refine Algebra.adjoin_le ?_
    refine Set.singleton_subset_iff.mpr ?_
    exact Subalgebra.sub_mem _ (Algebra.self_mem_adjoin_singleton _ _) (Subalgebra.one_mem _)
  exact hle hmap_adj

end Atlas.Knowledge
