import Mathlib

/-!
# cyclotomic floor

The cyclotomic floor of a field: `cycloField K m` is the subextension
of the algebraic closure generated by the `m`-th roots of unity,
carried as the adjunction of the root set of `X ^ m - 1` so that the
splitting-field instances fire. The floor is finite and normal over
any base and abelian Galois in characteristic zero — these are the
levels on which the Frobenius normalization of the local reciprocity
map is read (#104).

## Main definitions

* `cycloField` — the level-`m` cyclotomic subextension of the
  algebraic closure.

## Main statements

* `mem_cycloField` — the `m`-th roots of unity land in the floor;
  proved.
* `cycloField_aut_comm` — the Galois group of a floor is commutative;
  proved.
* `cycloField_isAbelianGalois` — in characteristic zero a floor of
  nonzero level is an abelian Galois extension, as an instance;
  proved.

## Implementation notes

Promotion provenance: `cycloField`, its splitting-field,
finite-dimensionality, and normality instances, `mem_cycloField`,
`cycloField_aut_comm`, and the root-set reading
`cycloField_pow_eq_one_of_mem_rootSet` moved here from the private
section of `Atlas.Knowledge.IsLocalReciprocity`, where the uniqueness
proof built them for its own use — the promotion deferred there until a
second consumer appeared, executed on the #104 Brick-C decision now
that the Frobenius normalization reads the floors
(`Atlas.Knowledge.CycloFieldLowerRamificationGroupEqBot` and the
assembly after it). The names and signatures are kept exactly as the
private copies had them, so the consumer's call sites do not move; the
hypotheses are weakened to what each proof uses — the definition, the
three instances, the membership lemma, and the root-set reading ask
only `Field K`, and the commutativity asks `CharZero K` where the
private copies carried the whole local-field pack. The two instances
new here, `cycloField_isGalois` and `cycloField_isAbelianGalois`, are
the forms the target-side dictionary
(`Atlas.Knowledge.AbsoluteAbelianRestriction`) demands at a floor; the
abelian one takes its nonvanishing as `NeZero m` because instance
arguments cannot be plain hypotheses, and at level zero the floor is
`⊥` and the instance is not needed. The device is the question writer's
own: the read repository never forms this intermediate field — its
cyclotomic extensions live monogenically over an abstract top field, in
the corner whose delta
`Atlas.Knowledge.CycloFieldLowerRamificationGroupEqBot` discloses and
cites in full — and no classical source is transcribed: the
commutativity is the standard exponent-multiplication argument on a
chosen primitive root. -/

namespace Atlas.Knowledge

variable (K : Type*) [Field K]

/-- The **cyclotomic floor** at level `m`: the subextension of the
algebraic closure generated by the `m`-th roots of unity, carried as
the adjunction of the root set of `X ^ m - 1` so that the
splitting-field instances fire. -/
noncomputable def cycloField (m : ℕ) : IntermediateField K (AlgebraicClosure K) :=
  IntermediateField.adjoin K
    ((Polynomial.X ^ m - 1 : Polynomial K).rootSet (AlgebraicClosure K))

/-- The cyclotomic floor splits `X ^ m - 1`: it is the adjunction of
the full root set of a polynomial split by the algebraic closure. -/
instance cycloField_isSplittingField (m : ℕ) :
    Polynomial.IsSplittingField K ↥(cycloField K m) (Polynomial.X ^ m - 1 : Polynomial K) :=
  IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)

/-- The cyclotomic floor is a finite extension, as the splitting field
of one polynomial. -/
instance cycloField_finiteDimensional (m : ℕ) : FiniteDimensional K ↥(cycloField K m) :=
  Polynomial.IsSplittingField.finiteDimensional _ (Polynomial.X ^ m - 1 : Polynomial K)

/-- The cyclotomic floor is a normal extension, as a splitting
field. -/
instance cycloField_normal (m : ℕ) : Normal K ↥(cycloField K m) :=
  Normal.of_isSplittingField (Polynomial.X ^ m - 1 : Polynomial K)

/-- Membership in the root set of `X ^ m - 1` is being an `m`-th root
of unity — the reading lemma for the generating set of the cyclotomic
floor. -/
theorem cycloField_pow_eq_one_of_mem_rootSet {m : ℕ} {x : AlgebraicClosure K}
    (hx : x ∈ (Polynomial.X ^ m - 1 : Polynomial K).rootSet (AlgebraicClosure K)) :
    x ^ m = 1 := by
  rw [Polynomial.mem_rootSet] at hx
  simpa [sub_eq_zero] using hx.2

/-- Roots of unity land in the cyclotomic floor. -/
theorem mem_cycloField {m : ℕ} (hm : m ≠ 0) {ζ : AlgebraicClosure K}
    (hζ : ζ ^ m = 1) : ζ ∈ cycloField K m := by
  refine IntermediateField.subset_adjoin _ _ ?_
  rw [Polynomial.mem_rootSet]
  refine ⟨fun h0 => ?_, by simp [hζ]⟩
  have h1 := congrArg (Polynomial.eval (0 : K)) h0
  simp [zero_pow hm] at h1

variable [CharZero K]

/-- The Galois group of a cyclotomic floor is commutative: every
automorphism raises a primitive root to a power, and the exponents
multiply commutatively. -/
theorem cycloField_aut_comm {m : ℕ} (hm : m ≠ 0)
    (σ τ : ↥(cycloField K m) ≃ₐ[K] ↥(cycloField K m)) : σ * τ = τ * σ := by
  haveI : NeZero m := ⟨hm⟩
  haveI : NeZero (m : K) := ⟨Nat.cast_ne_zero.mpr hm⟩
  obtain ⟨ζ₀, hζ₀⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure K) m
  have hζmem : ζ₀ ∈ cycloField K m := mem_cycloField K hm hζ₀.pow_eq_one
  have hζ' : IsPrimitiveRoot (⟨ζ₀, hζmem⟩ : ↥(cycloField K m)) m := by
    refine ⟨Subtype.ext (by simpa using hζ₀.pow_eq_one), fun l hl => ?_⟩
    exact hζ₀.dvd_of_pow_eq_one l (by simpa using congrArg Subtype.val hl)
  have key : ∀ ρ : ↥(cycloField K m) ≃ₐ[K] ↥(cycloField K m),
      ∃ a : ℕ, ρ ⟨ζ₀, hζmem⟩ = (⟨ζ₀, hζmem⟩ : ↥(cycloField K m)) ^ a := by
    intro ρ
    have hρ : (ρ ⟨ζ₀, hζmem⟩) ^ m = 1 := by rw [← map_pow, hζ'.pow_eq_one, map_one]
    obtain ⟨a, -, ha⟩ := hζ'.eq_pow_of_pow_eq_one hρ
    exact ⟨a, ha.symm⟩
  obtain ⟨a, ha⟩ := key σ
  obtain ⟨b, hb⟩ := key τ
  apply AlgEquiv.coe_toAlgHom_injective
  refine IntermediateField.algHom_ext_of_eq_adjoin (S := cycloField K m) K rfl ?_
  intro x hx
  have hxm : (⟨x, IntermediateField.subset_adjoin _ _ hx⟩ : ↥(cycloField K m)) ^ m = 1 := by
    rw [Polynomial.mem_rootSet] at hx
    exact Subtype.ext (by simpa [sub_eq_zero] using hx.2)
  obtain ⟨j, -, hj⟩ := hζ'.eq_pow_of_pow_eq_one hxm
  have h1 : (σ * τ) ⟨ζ₀, hζmem⟩ = (⟨ζ₀, hζmem⟩ : ↥(cycloField K m)) ^ (a * b) := by
    rw [AlgEquiv.mul_apply, hb, map_pow, ha, ← pow_mul]
  have h2 : (τ * σ) ⟨ζ₀, hζmem⟩ = (⟨ζ₀, hζmem⟩ : ↥(cycloField K m)) ^ (b * a) := by
    rw [AlgEquiv.mul_apply, ha, map_pow, hb, ← pow_mul]
  simp only [AlgEquiv.coe_toAlgHom]
  rw [← hj, map_pow, map_pow, h1, h2, Nat.mul_comm a b]

/-- In characteristic zero the cyclotomic floor is a Galois extension:
it is normal as a splitting field and separable as any algebraic
extension of a field of characteristic zero. -/
instance cycloField_isGalois (m : ℕ) : IsGalois K ↥(cycloField K m) := ⟨⟩

/-- In characteristic zero a cyclotomic floor of nonzero level is an
**abelian Galois extension** — the instance form of
`Atlas.Knowledge.cycloField_aut_comm`, the shape the finite abelian
subextension vocabulary keys on. -/
instance cycloField_isAbelianGalois (m : ℕ) [NeZero m] :
    IsAbelianGalois K ↥(cycloField K m) where
  is_comm := ⟨fun σ τ => cycloField_aut_comm K (NeZero.ne m) σ τ⟩

end Atlas.Knowledge
