import Mathlib

/-!
# fixing subgroup of a simple adjunction

The fixing subgroup of `K⟮x⟯` inside the automorphism group of an extension `L` of `K` is the
stabilizer of `x`: an automorphism fixes the field generated by `x` exactly when it fixes
`x`. The forward direction is that `x` lies in `K⟮x⟯`; the reverse runs through the fixed
field of the cyclic subgroup the automorphism generates, which contains `x` and therefore all
of `K⟮x⟯`. This is the glue that lets a condition on one element — `σ x = x` — be read as
membership in a subgroup that the Krull topology knows to be closed, which is where
`Atlas.Knowledge.AbelianizedKummerRootQuotient` and `Atlas.Knowledge.DenseGaloisFixedElement`
need it.

## Main statements

* `fixingSubgroupAdjoinSimple` — `K⟮x⟯.fixingSubgroup = MulAction.stabilizer (L ≃ₐ[K] L) x`;
  proved.

## Implementation notes

The statement is an equality of subgroups of `L ≃ₐ[K] L`, the stabilizer taken for the
evaluation action `AlgEquiv.applyMulSemiringAction`, so that `AlgEquiv.smul_def` turns
membership into `σ x = x`. No Galois, separability, or finiteness hypothesis enters: the
identity holds for any field extension, and `IntermediateField.fixingSubgroup_isClosed` adds
the topology downstream once `x` is integral. The reverse inclusion is
`IntermediateField.le_iff_le` in disguise — `K⟮x⟯` lies in the fixed field of
`Subgroup.zpowers σ` as soon as `x` does, and `x` does because the stabilizer is a subgroup —
spelled with `Subgroup.zpowers_le` on the stabilizer rather than by an induction over the
adjunction.
-/

namespace Atlas.Knowledge

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The fixing subgroup of `K⟮x⟯` is the stabilizer of `x`: an automorphism fixes the field
generated by `x` exactly when it fixes `x`, since the fixed field of the cyclic group it
generates then contains `x` and with it all of `K⟮x⟯`. -/
theorem fixingSubgroupAdjoinSimple (x : L) :
    (IntermediateField.adjoin K {x}).fixingSubgroup = MulAction.stabilizer (L ≃ₐ[K] L) x := by
  ext σ
  rw [IntermediateField.mem_fixingSubgroup_iff, MulAction.mem_stabilizer_iff, AlgEquiv.smul_def]
  constructor
  · intro h
    exact h x (IntermediateField.mem_adjoin_simple_self K x)
  · intro h y hy
    have hσ : σ ∈ MulAction.stabilizer (L ≃ₐ[K] L) x := by
      rw [MulAction.mem_stabilizer_iff, AlgEquiv.smul_def]
      exact h
    have h1 : IntermediateField.adjoin K {x} ≤
        IntermediateField.fixedField (Subgroup.zpowers σ) := by
      rw [IntermediateField.adjoin_simple_le_iff, IntermediateField.mem_fixedField_iff]
      intro g hg
      exact MulAction.mem_stabilizer_iff.mp (Subgroup.zpowers_le.mpr hσ hg)
    exact (IntermediateField.mem_fixedField_iff _ y).mp (h1 hy) σ (Subgroup.mem_zpowers σ)

end Atlas.Knowledge
