import Mathlib
import Atlas.Knowledge.FrobeniusElements
import Atlas.Knowledge.NormalizedDegree
import Atlas.Knowledge.TopologicalGeneration

/-!
# Frobenius exponent

The natural exponent attached to a Frobenius element: the class's normalized
degree is a natural power of the multiplicative generator of `ℤ̂`, and the
exponent is unique because distinct powers of the generator are distinct.
Around it, the analytic half of the Frobenius fixed-field argument: the
normalized degree of the extension as a continuous homomorphism, surjective;
its kernel restricting injectively into the finite group `G(L|K)`; the
closedness of the relative inertia; and the key injectivity — a continuous
homomorphism into `ℤ̂` from a profinite group topologically generated by one
element sent to `1` is injective, by trapping the group between a finite
quotient and a finite reduction of `ℤ̂` (#104).

## Main definitions

* `profiniteIntegerReductionMul` — reduction modulo `n`, multiplicatively.
* `DegreeData.frobeniusExponent` — the exponent `d_K(σ)` of a Frobenius
  element.
* `DegreeData.extensionNormalizedDegreeContinuous` — the factorized
  normalized degree, continuous.
* `DegreeData.extensionDegreeKernelRestriction` — the restriction mapping
  the degree kernel into `G(L|K)`.

## Main statements

* `injective_of_topologicallyGenerates_ofAdd_one` — a continuous
  homomorphism to `ℤ̂` sending a topological generator to `1` is injective;
  proved.
* `DegreeData.frobeniusExponent_pos` — the exponent is strictly positive;
  proved.
* `DegreeData.extensionNormalizedDegree_frobenius_eq_pow` — the normalized
  degree of a Frobenius element is the exponent's power of the generator;
  proved.
* `DegreeData.frobeniusExponent_unique` — the degree equation determines
  the exponent; proved.
* `DegreeData.extensionNormalizedDegreeContinuous_surjective` — the
  continuous degree is onto; proved.
* `DegreeData.extensionDegreeKernelRestriction_injective` — restriction is
  injective on the degree kernel; proved.
* `DegreeData.extensionInertiaWithin_isClosed` — the relative inertia is
  closed; proved.

## Implementation notes

The source's private continuous-quotient helpers stay private here; the two
helpers its second half uses go with that half. The injectivity theorem the
second half consumes is public. The source's bundled reduction takes a
positivity hypothesis; the layer's `ProfiniteInteger.reduction` carries
`NeZero`, as across the layer. The simp attribute the source puts on the
`toMonoidHom` computation rule is dropped — simp rewrites its left side by
`ContinuousMonoidHom.coe_toMonoidHom` first, so the rule can never fire —
and the closedness of the relative inertia drops the source's unused
topological-group binder.

## References

* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

namespace Atlas.Knowledge

noncomputable section

universe u

variable {G : Type u} [Group G] [TopologicalSpace G]

/- The quotient projection with its quotient topology, used locally below
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:23`). -/
private def continuousQuotientMk
    {A : Type*} [Group A] [TopologicalSpace A]
    (N : Subgroup A) [N.Normal] : A →ₜ* A ⧸ N where
  toMonoidHom := QuotientGroup.mk' N
  continuous_toFun := continuous_quotient_mk'

/- The continuous lift of a homomorphism through a quotient, used locally
below (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:31`). -/
private def continuousQuotientLift
    {A : Type*} {B : Type*} [Group A] [TopologicalSpace A]
    [Group B] [TopologicalSpace B]
    (N : Subgroup A) [N.Normal] (f : A →ₜ* B)
    (hN : N ≤ f.toMonoidHom.ker) : A ⧸ N →ₜ* B := by
  let φ : A ⧸ N →* B := QuotientGroup.lift N f.toMonoidHom hN
  have hcomp : Continuous (fun x : A => φ (QuotientGroup.mk' N x)) := by
    simpa [φ, QuotientGroup.lift_mk'] using f.continuous_toFun
  exact
    { toMonoidHom := φ
      continuous_toFun :=
        (QuotientGroup.isQuotientMap_mk (G := A)
          (N := N)).continuous_iff.2 hcomp }

/- A nonidentity element of a profinite group is omitted by some open normal
subgroup (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:65`). -/
private theorem exists_openNormalSubgroup_not_mem
    {A : Type*} [Group A] [TopologicalSpace A] [IsTopologicalGroup A]
    [CompactSpace A] [T2Space A] [TotallyDisconnectedSpace A]
    {x : A} (hx : x ≠ 1) :
    ∃ U : OpenNormalSubgroup A, x ∉ (U : Subgroup A) := by
  let W : Set A := ({x} : Set A)ᶜ
  have hWopen : IsOpen W := isClosed_singleton.isOpen_compl
  have hWone : (1 : A) ∈ W := by
    simpa [W] using hx.symm
  obtain ⟨U, hUW⟩ :=
    ProfiniteGrp.exist_openNormalSubgroup_sub_open_nhds_of_one
      (G := A) hWopen hWone
  refine ⟨U, ?_⟩
  intro hxU
  have hxW : x ∈ W := hUW hxU
  change x ∉ ({x} : Set A) at hxW
  exact hxW (by simp)

/-- **Reduction modulo `n`, in the multiplicative presentation**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:111`). -/
def profiniteIntegerReductionMul (n : ℕ) [NeZero n] :
    ProfiniteIntegerMul →ₜ* Multiplicative (ZMod n) where
  toFun z := Multiplicative.ofAdd (ProfiniteInteger.reduction n z.toAdd)
  map_one' := by
    apply Multiplicative.ext
    exact map_zero ((ProfiniteInteger.reduction n) : ProfiniteInteger →+ ZMod n)
  map_mul' x y := by
    apply Multiplicative.ext
    exact map_add (ProfiniteInteger.reduction n) x.toAdd y.toAdd
  continuous_toFun := ProfiniteInteger.continuous_reduction n

/-- The multiplicative reduction reads as the reduction on additive
coordinates. -/
@[simp]
theorem profiniteIntegerReductionMul_apply_toAdd (n : ℕ) [NeZero n]
    (z : ProfiniteIntegerMul) :
    (profiniteIntegerReductionMul n z).toAdd =
      ProfiniteInteger.reduction n z.toAdd :=
  rfl

/-- **A continuous homomorphism to `ℤ̂` sending a topological generator to
`1` is injective**, the cardinal comparison of the classical Frobenius
fixed-field proof: any nonvanishing kernel element survives into a finite
quotient that the corresponding finite reduction of `ℤ̂` matches exactly
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:132`). -/
theorem injective_of_topologicallyGenerates_ofAdd_one
    {A : Type*} [CommGroup A] [TopologicalSpace A]
    [IsTopologicalGroup A] [CompactSpace A] [T2Space A]
    [TotallyDisconnectedSpace A]
    (f : A →ₜ* ProfiniteIntegerMul) (x : A)
    (hxgen : TopologicallyGenerates ({x} : Set A))
    (hfx : f x = Multiplicative.ofAdd (1 : ProfiniteInteger)) :
    Function.Injective f := by
  intro a b hab
  suffices h : a⁻¹ * b = 1 by
    exact inv_mul_eq_one.mp h
  let y := a⁻¹ * b
  have hfy : f y = 1 := by
    dsimp [y]
    rw [map_mul, map_inv, hab, inv_mul_cancel]
  by_contra hy
  obtain ⟨U, hyU⟩ := exists_openNormalSubgroup_not_mem hy
  letI : Finite (A ⧸ (U : Subgroup A)) :=
    Subgroup.quotient_finite_of_isOpen (U : Subgroup A)
      U.toOpenSubgroup.isOpen'
  let m := Nat.card (A ⧸ (U : Subgroup A))
  have hm : 0 < m := by
    dsimp [m]
    exact Nat.card_pos
  letI : NeZero m := ⟨hm.ne'⟩
  let q : A →ₜ* (A ⧸ (U : Subgroup A)) :=
    continuousQuotientMk (U : Subgroup A)
  have hqx :
      q x = QuotientGroup.mk' (U : Subgroup A) x := rfl
  have hqpow : (q x) ^ m = 1 := by
    exact pow_card_eq_one'
  let H : ClosedSubgroup A :=
    closedSubgroupGenerated ({x ^ m} : Set A)
  letI : (H.toSubgroup).Normal := by infer_instance
  have hHU : H.toSubgroup ≤ (U : Subgroup A) := by
    apply Subgroup.topologicalClosure_minimal
    · rw [Subgroup.closure_le]
      intro z hz
      rw [Set.mem_singleton_iff] at hz
      subst z
      apply (QuotientGroup.eq_one_iff (x ^ m)).mp
      change q (x ^ m) = 1
      rw [map_pow]
      simpa only [hqx] using hqpow
    · exact Subgroup.isClosed_of_isOpen (U : Subgroup A) U.isOpen'
  letI : IsClosed (H.toSubgroup : Set A) := H.isClosed'
  let B := A ⧸ H.toSubgroup
  let qH : A →ₜ* B := continuousQuotientMk H.toSubgroup
  have hqHx :
      qH x = QuotientGroup.mk' H.toSubgroup x := rfl
  have hqHgen : TopologicallyGenerates ({qH x} : Set B) := by
    have h := topologicallyGenerates_quotient_image H.toSubgroup hxgen
    simpa only [Set.image_singleton, hqHx] using h
  have hqHpow : (qH x) ^ m = 1 := by
    rw [← map_pow]
    change (QuotientGroup.mk' H.toSubgroup) (x ^ m) = 1
    apply (QuotientGroup.eq_one_iff (N := H.toSubgroup) (x ^ m)).2
    change x ^ m ∈
      (closedSubgroupGenerated ({x ^ m} : Set A) : Subgroup A)
    exact Subgroup.le_topologicalClosure _
      (Subgroup.subset_closure (by simp))
  have hqHfiniteOrder : IsOfFinOrder (qH x) := by
    rw [← orderOf_pos_iff]
    have hdvd : orderOf (qH x) ∣ m :=
      orderOf_dvd_of_pow_eq_one hqHpow
    exact Nat.pos_of_dvd_of_pos hdvd hm
  have hzpowersClosed :
      IsClosed ((Subgroup.zpowers (qH x) : Subgroup B) : Set B) :=
    (finite_zpowers.mpr hqHfiniteOrder).isClosed
  have hzpowersTopologicalClosure :
      (Subgroup.zpowers (qH x)).topologicalClosure =
        Subgroup.zpowers (qH x) := by
    apply SetLike.ext'
    rw [Subgroup.topologicalClosure_coe]
    rw [hzpowersClosed.closure_eq]
  have hzpowersTop : Subgroup.zpowers (qH x) = ⊤ := by
    rw [TopologicallyGenerates, ← Subgroup.zpowers_eq_closure,
      hzpowersTopologicalClosure] at hqHgen
    exact hqHgen
  letI : Finite (Subgroup.zpowers (qH x)) :=
    (finite_zpowers.mpr hqHfiniteOrder).to_subtype
  letI : Finite B :=
    Finite.of_injective
      (fun b : B =>
        (⟨b, by rw [hzpowersTop]; trivial⟩ : Subgroup.zpowers (qH x)))
      (by
        intro a b hab
        exact congrArg Subtype.val hab)
  have hcardB : Nat.card B = orderOf (qH x) :=
    (orderOf_eq_card_of_zpowers_eq_top hzpowersTop).symm
  have hcardBle : Nat.card B ≤ m := by
    rw [hcardB]
    exact orderOf_le_of_pow_eq_one hm hqHpow
  let r : A →ₜ* Multiplicative (ZMod m) :=
    (profiniteIntegerReductionMul m).comp f
  have hrx : r x = Multiplicative.ofAdd (1 : ZMod m) := by
    apply Multiplicative.ext
    change ProfiniteInteger.reduction m (f x).toAdd = 1
    rw [hfx]
    simp
  have hHker : H.toSubgroup ≤ r.toMonoidHom.ker := by
    apply Subgroup.topologicalClosure_minimal
    · rw [Subgroup.closure_le]
      intro z hz
      rw [Set.mem_singleton_iff] at hz
      subst z
      change r (x ^ m) = 1
      rw [map_pow, hrx]
      apply Multiplicative.ext
      simp
    · change IsClosed {z : A | r z = 1}
      letI : T2Space (Multiplicative (ZMod m)) := by
        change T2Space (ZMod m)
        infer_instance
      exact isClosed_eq r.continuous_toFun continuous_const
  let rbar : B →ₜ* Multiplicative (ZMod m) :=
    continuousQuotientLift H.toSubgroup r hHker
  have hrbarSurj : Function.Surjective rbar := by
    intro z
    obtain ⟨k, hk⟩ := ZMod.intCast_surjective z.toAdd
    refine ⟨(qH x) ^ k, ?_⟩
    apply Multiplicative.ext
    rw [map_zpow]
    change ((r x) ^ k).toAdd = z.toAdd
    rw [hrx]
    simpa using hk
  have hcodCard : Nat.card (Multiplicative (ZMod m)) = m := by
    calc
      Nat.card (Multiplicative (ZMod m)) =
          Nat.card (ZMod m) :=
        Nat.card_congr Multiplicative.toAdd
      _ = m := Nat.card_zmod m
  have hcardLower : m ≤ Nat.card B := by
    rw [← hcodCard]
    exact Nat.card_le_card_of_surjective rbar hrbarSurj
  have hcardEq : Nat.card B =
      Nat.card (Multiplicative (ZMod m)) := by
    rw [hcodCard]
    exact le_antisymm hcardBle hcardLower
  have hrbarInj : Function.Injective rbar :=
    (Nat.bijective_iff_surjective_and_card rbar).mpr
      ⟨hrbarSurj, hcardEq⟩ |>.1
  have hry : r y = 1 := by
    change profiniteIntegerReductionMul m (f y) = 1
    rw [hfy, map_one]
  have hqy : qH y = 1 := by
    apply hrbarInj
    change r y = r 1
    rw [hry, map_one]
  change (QuotientGroup.mk' H.toSubgroup) y = 1 at hqy
  have hyH : y ∈ H.toSubgroup :=
    (QuotientGroup.eq_one_iff (N := H.toSubgroup) y).mp hqy
  exact hyU (hHU hyH)

namespace DegreeData

/-- **The Frobenius exponent** `d_K(σ)` of a Frobenius element
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:295`). -/
def frobeniusExponent (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) : ℕ :=
  Exists.choose σ.2

/-- **The Frobenius exponent is strictly positive** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:302`). -/
theorem frobeniusExponent_pos (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    0 < D.frobeniusExponent K L hLK σ :=
  (Exists.choose_spec σ.2).1

/-- The Frobenius exponent is nonzero, so the division apparatus of the
profinite integers applies to it directly. -/
instance frobeniusExponent_neZero (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    NeZero (D.frobeniusExponent K L hLK σ) :=
  ⟨(D.frobeniusExponent_pos K L hLK σ).ne'⟩

/-- **The normalized degree of a Frobenius element is the exponent's power
of the generator** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:310`). -/
theorem extensionNormalizedDegree_frobenius_eq_pow (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.extensionNormalizedDegree K L hLK σ.1 =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^
        D.frobeniusExponent K L hLK σ :=
  (Exists.choose_spec σ.2).2

/-- **The normalized-degree equation determines the Frobenius exponent**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:322`). -/
theorem frobeniusExponent_unique (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) (n : ℕ)
    (hn :
      D.extensionNormalizedDegree K L hLK σ.1 =
        (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n) :
    n = D.frobeniusExponent K L hLK σ := by
  apply ProfiniteInteger.ofAdd_one_pow_injective
  exact hn.symm.trans
    (D.extensionNormalizedDegree_frobenius_eq_pow K L hLK σ)

/-- **The factorized normalized degree as a continuous homomorphism**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:336`). -/
def extensionNormalizedDegreeContinuous (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal] :
    (K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) →ₜ*
      ProfiniteIntegerMul :=
  { toMonoidHom := D.extensionNormalizedDegree K L hLK
    continuous_toFun :=
      (continuousQuotientLift (D.extensionInertiaWithin K.field L hLK)
        (D.normalizedDegree K)
        (by
          intro x hx
          rw [D.normalizedDegree_ker K]
          exact hx.2)).continuous_toFun }

/-- The continuous normalized degree evaluates as the algebraic one. -/
@[simp]
theorem extensionNormalizedDegreeContinuous_apply (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (x : K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) :
    D.extensionNormalizedDegreeContinuous K L hLK x =
      D.extensionNormalizedDegree K L hLK x :=
  rfl

/-- Forgetting continuity recovers the normalized-degree homomorphism. -/
theorem extensionNormalizedDegreeContinuous_toMonoidHom (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal] :
    (D.extensionNormalizedDegreeContinuous K L hLK).toMonoidHom =
      D.extensionNormalizedDegree K L hLK :=
  rfl

/-- **The continuous normalized degree of the extension is surjective**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:372`). -/
theorem extensionNormalizedDegreeContinuous_surjective (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal] :
    Function.Surjective
      (D.extensionNormalizedDegreeContinuous K L hLK) := by
  intro z
  obtain ⟨k, hk⟩ := D.normalizedDegree_surjective K z
  refine ⟨QuotientGroup.mk k, ?_⟩
  simpa using hk

/-- **Restriction embeds the degree kernel on `G(L̃|K)` into the finite
group `G(L|K)`** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:385`). -/
def extensionDegreeKernelRestriction (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal] :
    (D.extensionNormalizedDegreeContinuous K L hLK).toMonoidHom.ker →*
      (K.field.toSubgroup ⧸
        L.toSubgroup.subgroupOf K.field.toSubgroup) :=
  (D.extensionRestriction K.field L hLK).comp
    (D.extensionNormalizedDegreeContinuous K L hLK).toMonoidHom.ker.subtype

/-- **Restriction is injective on the degree kernel** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:395`). -/
theorem extensionDegreeKernelRestriction_injective (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal] :
    Function.Injective
      (D.extensionDegreeKernelRestriction K L hLK) := by
  intro a b hab
  let c := (a.1 :
    K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK)⁻¹ * b.1
  have hcRestriction : D.extensionRestriction K.field L hLK c = 1 := by
    dsimp [c]
    rw [map_mul, map_inv]
    change (D.extensionDegreeKernelRestriction K L hLK a)⁻¹ *
        D.extensionDegreeKernelRestriction K L hLK b = 1
    rw [hab, inv_mul_cancel]
  have hcDegree :
      D.extensionNormalizedDegreeContinuous K L hLK c = 1 := by
    dsimp [c]
    rw [map_mul, map_inv]
    change (D.extensionNormalizedDegreeContinuous K L hLK a.1)⁻¹ *
        D.extensionNormalizedDegreeContinuous K L hLK b.1 = 1
    have ha : D.extensionNormalizedDegreeContinuous K L hLK a.1 = 1 := a.2
    have hb : D.extensionNormalizedDegreeContinuous K L hLK b.1 = 1 := b.2
    rw [ha, hb, inv_one, one_mul]
  obtain ⟨k, hk⟩ := QuotientGroup.mk'_surjective
    (D.extensionInertiaWithin K.field L hLK) c
  have hkE : k ∈ L.toSubgroup.subgroupOf K.field.toSubgroup := by
    apply (QuotientGroup.eq_one_iff k).mp
    rw [← hk] at hcRestriction
    simpa using hcRestriction
  have hkI : k ∈ D.fieldInertiaWithin K.field := by
    rw [← D.normalizedDegree_ker K]
    change D.normalizedDegree K k = 1
    rw [← hk] at hcDegree
    simpa using hcDegree
  have hkc : k ∈ D.extensionInertiaWithin K.field L hLK :=
    ⟨hkE, hkI⟩
  have hcOne : c = 1 := by
    rw [← hk]
    exact (QuotientGroup.eq_one_iff k).mpr hkc
  apply Subtype.ext
  exact inv_mul_eq_one.mp hcOne

/-- **The relative inertia is closed in the base subgroup**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:438`). -/
theorem extensionInertiaWithin_isClosed (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup) :
    IsClosed
      (D.extensionInertiaWithin K.field L hLK :
        Set K.field.toSubgroup) := by
  have hE : IsClosed
      (L.toSubgroup.subgroupOf K.field.toSubgroup :
        Set K.field.toSubgroup) := by
    change IsClosed
      ((fun x : K.field.toSubgroup => (x : G)) ⁻¹' (L : Set G))
    exact L.isClosed'.preimage continuous_subtype_val
  have hI : IsClosed
      (D.fieldInertiaWithin K.field : Set K.field.toSubgroup) := by
    letI : T2Space ProfiniteIntegerMul := by
      change T2Space ProfiniteInteger
      infer_instance
    change IsClosed {x : K.field.toSubgroup | D.degree x.1 = 1}
    exact isClosed_eq
      (D.restrictedDegree K.field).continuous_toFun continuous_const
  change IsClosed
    ((L.toSubgroup.subgroupOf K.field.toSubgroup ⊓
      D.fieldInertiaWithin K.field) : Set K.field.toSubgroup)
  exact hE.inter hI

end DegreeData

end

end Atlas.Knowledge
