import Mathlib
import Atlas.Knowledge.DegreeData
import Atlas.Knowledge.FrobeniusElements
import Atlas.Knowledge.FrobeniusExponent
import Atlas.Knowledge.ProfiniteInteger
import Atlas.Knowledge.QuotientTotallyDisconnectedOfProfinite
import Atlas.Knowledge.RelativeIndexCardinal
import Atlas.Knowledge.TopologicalGeneration

/-!
# Frobenius fixed field

The group-dual Frobenius fixed-field theorem: the closed subgroup `Γ`
topologically generated by a Frobenius lift `σ` carries the normalized
degree `d_Σ = (1/d_K(σ))·d_K`, which identifies `Γ` continuously with `ℤ̂`
— the procyclic degree isomorphism — and under it `σ` is the Frobenius of
its own fixed field. Along the way, the residue-degree calculation: the
image of `d_K` on `Γ` is `d_K(σ)·ℤ̂`, of index the exponent; `Γ` has finite
index, so the fixed field is a finite extension; and when the lift has
exponent one, that index is at most the degree of the finite Galois
extension the lift came from (#104).

## Main definitions

* `profiniteIntegerPowNat` — multiplication by `n` on `ℤ̂`,
  multiplicatively.
* `DegreeData.frobeniusClosure` / `DegreeData.frobeniusInClosure` — the
  closed subgroup `Γ` generated by the lift, and the lift inside it.
* `DegreeData.frobeniusClosureDegree` — the normalized degree of the
  extension restricted to `Γ`.
* `DegreeData.fixedFieldNormalizedDegree` — the normalized degree `d_Σ` on
  `Γ`.
* `DegreeData.frobeniusFixedField_normalizedDegreeEquiv` — the procyclic
  degree isomorphism `Γ ≃ₜ* ℤ̂`.
* `DegreeData.fixedFieldFrobenius` — the Frobenius of the fixed field.

## Main statements

* `DegreeData.frobeniusClosureDegree_range` /
  `DegreeData.frobeniusClosureDegree_range_index` — the image of `d_K` on
  `Γ` is `d_K(σ)·ℤ̂`, of index the exponent; proved.
* `DegreeData.frobeniusExponent_nsmul_fixedFieldNormalizedDegree` — the
  defining identity `d_K(σ)·d_Σ = d_K` on `Γ`; proved.
* `DegreeData.fixedFieldNormalizedDegree_surjective` /
  `DegreeData.frobeniusFixedField_normalizedDegree_injective` — `d_Σ` is a
  bijection; proved.
* `DegreeData.frobeniusFixedField_finiteIndex` — `Γ` has finite index;
  proved.
* `DegreeData.frobeniusClosure_index_le_extensionIndex_of_exponent_eq_one`
  — at exponent one the fixed field's degree is at most the extension's;
  proved.
* `DegreeData.frobeniusFixedField_frobenius` — the lift is the Frobenius
  of its fixed field; proved.

## Implementation notes

The source states the degree image with the range of its bundled
multiplication-by-`n`; the layer states it with
`ProfiniteInteger.spanAddSubgroup`, whose membership, closedness, index, and
division apparatus `Atlas.Knowledge.ProfiniteInteger` already carries, and
the two inclusion proofs bridge by `mem_spanAddSubgroup_iff`. The positivity
hypotheses of the source's division apparatus become the `NeZero` instance
on the exponent, registered in `Atlas.Knowledge.FrobeniusExponent` beside
its positivity; the generation of `ℤ̂` by the generator moved to the
profinite-integer item beside its power-injectivity sibling. Four of the
source's ambient Hausdorff binders are unused once the layer's `abbrev`
spelling of `ℤ̂` supplies its own separation, and are dropped; the two that
remain are real — `frobeniusClosureCommGroup` consumes its binder through
instance synthesis the unused-argument linter cannot see, and
`frobeniusClosureDegreeInMulNatRange` keeps the source signature because it
is the value map the whole procyclic arc builds on.

## References

* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

noncomputable section

universe u

variable {G : Type u} [Group G] [TopologicalSpace G]

/- Inclusion of a subgroup with its subtype topology, used locally below
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:45`]
[Yamaguchi2026]). -/
private def continuousSubgroupSubtype
    {A : Type*} [Group A] [TopologicalSpace A]
    (H : Subgroup A) : H →ₜ* A where
  toMonoidHom := H.subtype
  continuous_toFun := continuous_subtype_val

/- A bijective continuous homomorphism from a compact group to a Hausdorff
group is a continuous multiplicative equivalence ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:53`]
[Yamaguchi2026]). -/
private noncomputable def continuousMulEquivOfBijectiveCompactToT2
    {A : Type*} {B : Type*} [Group A] [TopologicalSpace A]
    [Group B] [TopologicalSpace B] [CompactSpace A] [T2Space B]
    (φ : A →* B) (hφcont : Continuous φ) (hφ : Function.Bijective φ) :
    A ≃ₜ* B := by
  let e : A ≃ B := Equiv.ofBijective φ hφ
  let eh : A ≃ₜ B :=
    e.toHomeomorphOfContinuousClosed hφcont (Continuous.isClosedMap hφcont)
  exact ContinuousMulEquiv.mk' eh φ.map_mul

/-- **Multiplication by `n` on `ℤ̂`, in the multiplicative presentation**
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:85`]
[Yamaguchi2026]). -/
def profiniteIntegerPowNat (n : ℕ) :
    ProfiniteIntegerMul →ₜ* ProfiniteIntegerMul where
  toFun z := Multiplicative.ofAdd (n • z.toAdd)
  map_one' := by
    apply Multiplicative.ext
    simp
  map_mul' x y := by
    apply Multiplicative.ext
    exact nsmul_add x.toAdd y.toAdd n
  continuous_toFun :=
    show Continuous fun z : ProfiniteInteger => n • z from continuous_nsmul n

/-- The natural profinite power reads as scalar multiplication on additive
coordinates. -/
@[simp]
theorem profiniteIntegerPowNat_apply_toAdd (n : ℕ) (z : ProfiniteIntegerMul) :
    (profiniteIntegerPowNat n z).toAdd = n • z.toAdd :=
  rfl

/-- The natural profinite power map sends the generator to its power. -/
@[simp]
theorem profiniteIntegerPowNat_one (n : ℕ) :
    profiniteIntegerPowNat n
        (Multiplicative.ofAdd (1 : ProfiniteInteger)) =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n := by
  apply Multiplicative.ext
  rfl

namespace DegreeData

/-- **The closed subgroup `Γ` topologically generated by a Frobenius lift**
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:459`]
[Yamaguchi2026]). -/
def frobeniusClosure (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    ClosedSubgroup
      (K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) :=
  closedSubgroupGenerated
    (Set.range (fun _ : Unit => σ.1))

/-- **The chosen Frobenius lift, regarded in `Γ`** ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:470`]
[Yamaguchi2026]). -/
def frobeniusInClosure (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosure K L hLK σ :=
  closedSubgroupGeneratedMap (fun _ : Unit => σ.1) ()

/-- `Γ` inherits a topological group structure ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:479`]
[Yamaguchi2026]). -/
instance frobeniusClosure_isTopologicalGroup
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    IsTopologicalGroup (D.frobeniusClosure K L hLK σ) := by
  change IsTopologicalGroup
    ↑((D.frobeniusClosure K L hLK σ).toSubgroup)
  infer_instance

/-- `Γ` is commutative: it is the closure of the cyclic subgroup the lift
generates ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:491`]
[Yamaguchi2026]). -/
@[reducible] def frobeniusClosureCommGroup
    (D : DegreeData G) [IsTopologicalGroup G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    CommGroup (D.frobeniusClosure K L hLK σ) := by
  letI : IsClosed
      (D.extensionInertiaWithin K.field L hLK : Set K.field.toSubgroup) :=
    D.extensionInertiaWithin_isClosed K L hLK
  let Q := K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK
  let s : Subgroup Q :=
    Subgroup.closure (Set.range (fun _ : Unit => σ.1))
  let c : CommGroup ↑s.topologicalClosure :=
    Subgroup.commGroupTopologicalClosure s (by
      intro a b
      have hrange : Set.range (fun _ : Unit => σ.1) = ({σ.1} : Set Q) := by
        ext y
        simp
      have ha : (a : Q) ∈ Subgroup.zpowers σ.1 := by
        simpa [s, hrange, Subgroup.zpowers_eq_closure] using a.2
      have hb : (b : Q) ∈ Subgroup.zpowers σ.1 := by
        simpa [s, hrange, Subgroup.zpowers_eq_closure] using b.2
      obtain ⟨m, hm⟩ := Subgroup.mem_zpowers_iff.mp ha
      obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hb
      apply Subtype.ext
      change (a : Q) * (b : Q) = (b : Q) * (a : Q)
      rw [← hm, ← hn, ← zpow_add, add_comm, zpow_add])
  exact
    { (inferInstance : Group (D.frobeniusClosure K L hLK σ)) with
      mul_comm := c.mul_comm }

/-- The lift topologically generates `Γ`, by construction
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:525`]
[Yamaguchi2026]). -/
theorem frobeniusInClosure_topologicallyGenerates
    (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    TopologicallyGenerates
      ({D.frobeniusInClosure K L hLK σ} : Set
        (D.frobeniusClosure K L hLK σ)) := by
  let φ : Unit →
      (K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) :=
    fun _ => σ.1
  have hgen := closedSubgroupGeneratedMap_topologicallyGenerates φ
  have hrange : Set.range (closedSubgroupGeneratedMap φ) =
      ({closedSubgroupGeneratedMap φ ()} : Set
        (closedSubgroupGenerated (Set.range φ))) := by
    ext x
    simp only [Set.mem_range, Set.mem_singleton_iff]
    constructor
    · rintro ⟨u, rfl⟩
      cases u
      rfl
    · intro hx
      exact ⟨(), hx.symm⟩
  rw [hrange] at hgen
  change TopologicallyGenerates
    ({closedSubgroupGeneratedMap φ ()} : Set
      (closedSubgroupGenerated (Set.range φ) : Subgroup _))
  exact hgen

/-- **The normalized degree of the extension restricted to `Γ`** — the
object of the residue-degree calculation ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:556`]
[Yamaguchi2026]). -/
def frobeniusClosureDegree (D : DegreeData G) [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosure K L hLK σ →ₜ* ProfiniteIntegerMul :=
  (D.extensionNormalizedDegreeContinuous K L hLK).comp
    (continuousSubgroupSubtype
      (D.frobeniusClosure K L hLK σ).toSubgroup)

/-- The degree of the lift in `Γ` is the exponent's power of the generator
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:568`]
[Yamaguchi2026]). -/
@[simp]
theorem frobeniusClosureDegree_generator (D : DegreeData G)
    [IsTopologicalGroup G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosureDegree K L hLK σ
        (D.frobeniusInClosure K L hLK σ) =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^
        D.frobeniusExponent K L hLK σ := by
  change D.extensionNormalizedDegree K L hLK
      (D.frobeniusInClosure K L hLK σ).1 =
    (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^
      D.frobeniusExponent K L hLK σ
  have hval :
      (D.frobeniusInClosure K L hLK σ).1 = σ.1 := rfl
  rw [hval]
  exact D.extensionNormalizedDegree_frobenius_eq_pow K L hLK σ

/-- **The image of `d_K` on `Γ` is `d_K(σ)·ℤ̂`** — the group-dual
residue-degree calculation of the Frobenius fixed-field theorem
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:590`]
[Yamaguchi2026]). -/
theorem frobeniusClosureDegree_range (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range =
      AddSubgroup.toSubgroup
        (ProfiniteInteger.spanAddSubgroup
          (D.frobeniusExponent K L hLK σ)) := by
  letI : CompactSpace K.field.toSubgroup := by
    change CompactSpace K.field
    infer_instance
  let Γ := D.frobeniusClosure K L hLK σ
  let x : Γ := D.frobeniusInClosure K L hLK σ
  let f : Γ →ₜ* ProfiniteIntegerMul :=
    D.frobeniusClosureDegree K L hLK σ
  let n := D.frobeniusExponent K L hLK σ
  let R : Subgroup ProfiniteIntegerMul :=
    AddSubgroup.toSubgroup (ProfiniteInteger.spanAddSubgroup n)
  have hxgen : TopologicallyGenerates ({x} : Set Γ) := by
    simpa [Γ, x] using
      D.frobeniusInClosure_topologicallyGenerates K L hLK σ
  have hfx : f x =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n := by
    change D.frobeniusClosureDegree K L hLK σ
        (D.frobeniusInClosure K L hLK σ) =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^
        D.frobeniusExponent K L hLK σ
    exact D.frobeniusClosureDegree_generator K L hLK σ
  have hRclosed : IsClosed (R : Set ProfiniteIntegerMul) := by
    change IsClosed
      ((Ideal.span {((n : ℕ) : ProfiniteInteger)} :
        Ideal ProfiniteInteger) : Set ProfiniteInteger)
    exact ProfiniteInteger.isClosed_span_singleton _
  have hclosed_le_R :
      (closedSubgroupGenerated ({f x} : Set ProfiniteIntegerMul) :
        Subgroup ProfiniteIntegerMul) ≤ R := by
    apply Subgroup.topologicalClosure_minimal
    · rw [Subgroup.closure_le]
      intro y hy
      rw [Set.mem_singleton_iff] at hy
      subst y
      rw [hfx]
      change (n : ℕ) • (1 : ProfiniteInteger) ∈
        ProfiniteInteger.spanAddSubgroup n
      exact (ProfiniteInteger.mem_spanAddSubgroup_iff _).mpr
        ⟨1, by rw [nsmul_eq_mul]⟩
    · exact hRclosed
  apply le_antisymm
  · rintro y ⟨a, rfl⟩
    have ha : a ∈
        (closedSubgroupGenerated ({x} : Set Γ) : Subgroup Γ) := by
      rw [show (closedSubgroupGenerated ({x} : Set Γ) : Subgroup Γ) = ⊤ by
        simpa [TopologicallyGenerates, closedSubgroupGenerated] using hxgen]
      trivial
    exact hclosed_le_R
      (map_mem_closedSubgroupGenerated_singleton f x ha)
  · intro y hy
    change y.toAdd ∈ ProfiniteInteger.spanAddSubgroup n at hy
    obtain ⟨z, hz⟩ := (ProfiniteInteger.mem_spanAddSubgroup_iff _).mp hy
    have hzgen : Multiplicative.ofAdd z ∈
        (closedSubgroupGenerated
          ({Multiplicative.ofAdd (1 : ProfiniteInteger)} :
            Set ProfiniteIntegerMul) :
          Subgroup ProfiniteIntegerMul) := by
      rw [show (closedSubgroupGenerated
          ({Multiplicative.ofAdd (1 : ProfiniteInteger)} :
            Set ProfiniteIntegerMul) :
          Subgroup ProfiniteIntegerMul) = ⊤ by
        simpa [TopologicallyGenerates, closedSubgroupGenerated] using
          ProfiniteInteger.ofAdd_one_topologicallyGenerates]
      trivial
    have hmap := map_mem_closedSubgroupGenerated_singleton
      (profiniteIntegerPowNat n)
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) hzgen
    have hclosed_le_range :
        (closedSubgroupGenerated
          ({(Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n} :
            Set ProfiniteIntegerMul) :
          Subgroup ProfiniteIntegerMul) ≤ f.toMonoidHom.range := by
      apply Subgroup.topologicalClosure_minimal
      · rw [Subgroup.closure_le]
        intro w hw
        rw [Set.mem_singleton_iff] at hw
        subst w
        exact ⟨x, hfx⟩
      · have hcompact : IsCompact (Set.range f) :=
          letI : CompactSpace Γ := by
            dsimp [Γ]
            infer_instance
          isCompact_range f.continuous_toFun
        have hrange : Set.range f =
            (f.toMonoidHom.range : Set ProfiniteIntegerMul) := by
          ext w
          constructor <;> rintro ⟨a, rfl⟩ <;> exact ⟨a, rfl⟩
        exact (hrange ▸ hcompact).isClosed
    have hzmap : profiniteIntegerPowNat n (Multiplicative.ofAdd z) ∈
        f.toMonoidHom.range := by
      apply hclosed_le_range
      simpa using hmap
    have hzy : profiniteIntegerPowNat n (Multiplicative.ofAdd z) = y := by
      apply Multiplicative.ext
      change (n : ℕ) • z = y.toAdd
      rw [nsmul_eq_mul]
      exact hz
    exact hzy ▸ hzmap

/-- **The fixed field's relative residue degree is the exponent**: the
index reading of the degree image ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:691`]
[Yamaguchi2026]). -/
theorem frobeniusClosureDegree_range_index (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    (Subgroup.toAddSubgroup'
      (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range).index =
      D.frobeniusExponent K L hLK σ := by
  rw [D.frobeniusClosureDegree_range K L hLK σ]
  change (ProfiniteInteger.spanAddSubgroup
    (D.frobeniusExponent K L hLK σ)).index = _
  exact ProfiniteInteger.index_span_natCast _

/-- The value of `d_K` on `Γ`, regarded in `d_K(σ)·ℤ̂`
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:705`]
[Yamaguchi2026]). -/
def frobeniusClosureDegreeInMulNatRange (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK)
    (a : D.frobeniusClosure K L hLK σ) :
    ProfiniteInteger.spanAddSubgroup (D.frobeniusExponent K L hLK σ) := by
  refine ⟨(D.frobeniusClosureDegree K L hLK σ a).toAdd, ?_⟩
  have ha : D.frobeniusClosureDegree K L hLK σ a ∈
      (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range :=
    ⟨a, rfl⟩
  rw [D.frobeniusClosureDegree_range K L hLK σ] at ha
  exact ha

/-- The restricted degree has the stated underlying profinite value. -/
@[simp]
theorem frobeniusClosureDegreeInMulNatRange_coe (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK)
    (a : D.frobeniusClosure K L hLK σ) :
    (D.frobeniusClosureDegreeInMulNatRange K L hLK σ a).1 =
      (D.frobeniusClosureDegree K L hLK σ a).toAdd :=
  rfl

/-- **The normalized degree `d_Σ = (1/d_K(σ))·d_K` on `Γ`**
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:734`]
[Yamaguchi2026]). -/
def fixedFieldNormalizedDegree (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosure K L hLK σ →ₜ* ProfiniteIntegerMul where
  toFun a := Multiplicative.ofAdd
    (ProfiniteInteger.divide (D.frobeniusExponent K L hLK σ)
      (D.frobeniusClosureDegreeInMulNatRange K L hLK σ a))
  map_one' := by
    apply Multiplicative.ext
    rw [show D.frobeniusClosureDegreeInMulNatRange K L hLK σ 1 = 0 by
      apply Subtype.ext
      simp]
    exact map_zero
      (ProfiniteInteger.divide (D.frobeniusExponent K L hLK σ))
  map_mul' a b := by
    apply Multiplicative.ext
    rw [show D.frobeniusClosureDegreeInMulNatRange K L hLK σ (a * b) =
        D.frobeniusClosureDegreeInMulNatRange K L hLK σ a +
          D.frobeniusClosureDegreeInMulNatRange K L hLK σ b by
      apply Subtype.ext
      exact congrArg Multiplicative.toAdd
        (map_mul (D.frobeniusClosureDegree K L hLK σ) a b)]
    exact map_add
      (ProfiniteInteger.divide (D.frobeniusExponent K L hLK σ)) _ _
  continuous_toFun := by
    apply (map_continuous
      (ProfiniteInteger.divide (D.frobeniusExponent K L hLK σ))).comp
    exact Continuous.subtype_mk
      (D.frobeniusClosureDegree K L hLK σ).continuous_toFun
      (fun a =>
        (D.frobeniusClosureDegreeInMulNatRange K L hLK σ a).2)

/-- **The defining identity `d_K(σ)·d_Σ = d_K` on `Γ`** ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:774`]
[Yamaguchi2026]). -/
theorem frobeniusExponent_nsmul_fixedFieldNormalizedDegree
    (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK)
    (a : D.frobeniusClosure K L hLK σ) :
    D.frobeniusExponent K L hLK σ •
        (D.fixedFieldNormalizedDegree K L hLK σ a).toAdd =
      (D.frobeniusClosureDegree K L hLK σ a).toAdd := by
  change D.frobeniusExponent K L hLK σ •
      ProfiniteInteger.divide (D.frobeniusExponent K L hLK σ)
        (D.frobeniusClosureDegreeInMulNatRange K L hLK σ a) =
    (D.frobeniusClosureDegree K L hLK σ a).toAdd
  rw [nsmul_eq_mul]
  exact ProfiniteInteger.mul_divide _
    (D.frobeniusClosureDegreeInMulNatRange K L hLK σ a)

/-- The lift has normalized degree the generator over its fixed field
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:792`]
[Yamaguchi2026]). -/
@[simp]
theorem fixedFieldNormalizedDegree_generator (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.fixedFieldNormalizedDegree K L hLK σ
        (D.frobeniusInClosure K L hLK σ) =
      Multiplicative.ofAdd (1 : ProfiniteInteger) := by
  apply Multiplicative.ext
  apply ProfiniteInteger.nsmul_left_injective
    (D.frobeniusExponent_pos K L hLK σ).ne'
  change D.frobeniusExponent K L hLK σ •
      (D.fixedFieldNormalizedDegree K L hLK σ
        (D.frobeniusInClosure K L hLK σ)).toAdd =
    D.frobeniusExponent K L hLK σ •
      (Multiplicative.ofAdd (1 : ProfiniteInteger)).toAdd
  rw [D.frobeniusExponent_nsmul_fixedFieldNormalizedDegree]
  change (D.frobeniusClosureDegree K L hLK σ
      (D.frobeniusInClosure K L hLK σ)).toAdd =
    D.frobeniusExponent K L hLK σ • (1 : ProfiniteInteger)
  rw [D.frobeniusClosureDegree_generator]
  rfl

/-- **The normalized degree on `Γ` is onto** ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:817`]
[Yamaguchi2026]). -/
theorem fixedFieldNormalizedDegree_surjective (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    Function.Surjective
      (D.fixedFieldNormalizedDegree K L hLK σ) := by
  intro z
  have hz : Multiplicative.ofAdd
      (D.frobeniusExponent K L hLK σ • z.toAdd) ∈
      (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range := by
    rw [D.frobeniusClosureDegree_range K L hLK σ]
    change D.frobeniusExponent K L hLK σ • z.toAdd ∈
      ProfiniteInteger.spanAddSubgroup (D.frobeniusExponent K L hLK σ)
    exact (ProfiniteInteger.mem_spanAddSubgroup_iff _).mpr
      ⟨z.toAdd, by rw [nsmul_eq_mul]⟩
  obtain ⟨a, ha⟩ := hz
  refine ⟨a, ?_⟩
  apply Multiplicative.ext
  apply ProfiniteInteger.nsmul_left_injective
    (D.frobeniusExponent_pos K L hLK σ).ne'
  change D.frobeniusExponent K L hLK σ •
      (D.fixedFieldNormalizedDegree K L hLK σ a).toAdd =
    D.frobeniusExponent K L hLK σ • z.toAdd
  rw [D.frobeniusExponent_nsmul_fixedFieldNormalizedDegree]
  exact congrArg Multiplicative.toAdd ha

/-- `Γ` is totally disconnected ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:843`]
[Yamaguchi2026]). -/
theorem frobeniusClosure_totallyDisconnectedSpace (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    TotallyDisconnectedSpace (D.frobeniusClosure K L hLK σ) := by
  letI : CompactSpace K.field.toSubgroup := by
    change CompactSpace K.field
    infer_instance
  letI : TotallyDisconnectedSpace K.field.toSubgroup := by
    change TotallyDisconnectedSpace K.field
    infer_instance
  let Q := K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK
  letI : TotallyDisconnectedSpace Q :=
    quotient_totallyDisconnected_of_profinite
      (D.extensionInertiaWithin K.field L hLK)
      (D.extensionInertiaWithin_isClosed K L hLK)
  infer_instance

/-- **`Γ` has finite index, so the Frobenius fixed field is finite over
`K`** — the Galois-dual finiteness of the fixed field ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:873`]
[Yamaguchi2026]). -/
theorem frobeniusFixedField_finiteIndex (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    [hLfinite : Finite (K.field.toSubgroup ⧸
      L.toSubgroup.subgroupOf K.field.toSubgroup)]
    (σ : D.FrobeniusElements K L hLK) :
    Finite
      ((K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK) ⧸
        (D.frobeniusClosure K L hLK σ).toSubgroup) := by
  let Q := K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK
  let Γ : Subgroup Q :=
    (D.frobeniusClosure K L hLK σ).toSubgroup
  let dQ : Q →ₜ* ProfiniteIntegerMul :=
    D.extensionNormalizedDegreeContinuous K L hLK
  have hΓmap : Γ.map dQ.toMonoidHom =
      (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range := by
    ext z
    constructor
    · rintro ⟨q, hq, rfl⟩
      exact ⟨⟨q, hq⟩, rfl⟩
    · rintro ⟨q, rfl⟩
      exact ⟨q.1, q.2, rfl⟩
  have htopmap : (Subgroup.map dQ.toMonoidHom (⊤ : Subgroup Q)) = ⊤ := by
    apply top_unique
    intro z _
    obtain ⟨q, rfl⟩ :=
      D.extensionNormalizedDegreeContinuous_surjective K L hLK z
    exact ⟨q, trivial, rfl⟩
  have himage : (Γ.map dQ.toMonoidHom).relIndex
      ((⊤ : Subgroup Q).map dQ.toMonoidHom) ≠ 0 := by
    rw [hΓmap, htopmap, Subgroup.relIndex_top_right,
      D.frobeniusClosureDegree_range K L hLK σ,
      AddSubgroup.index_toSubgroup,
      ProfiniteInteger.index_span_natCast]
    exact (D.frobeniusExponent_pos K L hLK σ).ne'
  let j := D.extensionDegreeKernelRestriction K L hLK
  letI : Finite dQ.toMonoidHom.ker :=
    Finite.of_injective j
      (D.extensionDegreeKernelRestriction_injective K L hLK)
  let T : Subgroup Q := (⊤ : Subgroup Q) ⊓ dQ.toMonoidHom.ker
  let toKer : T → dQ.toMonoidHom.ker :=
    fun t => ⟨t.1, t.2.2⟩
  letI : Finite T := Finite.of_injective toKer (by
    intro a b hab
    apply Subtype.ext
    exact congrArg (fun x : dQ.toMonoidHom.ker => x.1) hab)
  have hkernel : (Γ ⊓ dQ.toMonoidHom.ker).relIndex
      ((⊤ : Subgroup Q) ⊓ dQ.toMonoidHom.ker) ≠ 0 := by
    rw [Subgroup.relIndex]
    change ((Γ ⊓ dQ.toMonoidHom.ker).subgroupOf T).index ≠ 0
    exact Subgroup.index_ne_zero_of_finite
  have hrel : Γ.relIndex (⊤ : Subgroup Q) ≠ 0 := by
    rw [relIndex_eq_map_relIndex_mul_inf_ker_relIndex
      dQ.toMonoidHom le_top]
    exact Nat.mul_ne_zero himage hkernel
  apply (Subgroup.index_ne_zero_iff_finite).mp
  simpa [Γ, Q, Subgroup.relIndex_top_right] using hrel

/-- **The procyclic degree isomorphism, kernel form**: `d_Σ` has trivial
kernel, by comparing the finite quotients `Γ/Γᵐ` with `ℤ̂/mℤ̂`
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:936`]
[Yamaguchi2026]). -/
theorem frobeniusFixedField_normalizedDegree_injective (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    Function.Injective
      (D.fixedFieldNormalizedDegree K L hLK σ) := by
  let Γ := D.frobeniusClosure K L hLK σ
  letI : CompactSpace K.field.toSubgroup := by
    change CompactSpace K.field
    infer_instance
  letI : CompactSpace Γ := by infer_instance
  letI : TotallyDisconnectedSpace Γ :=
    D.frobeniusClosure_totallyDisconnectedSpace K L hLK σ
  letI : CommGroup Γ :=
    D.frobeniusClosureCommGroup K L hLK σ
  apply injective_of_topologicallyGenerates_ofAdd_one
    (D.fixedFieldNormalizedDegree K L hLK σ)
    (D.frobeniusInClosure K L hLK σ)
  · exact D.frobeniusInClosure_topologicallyGenerates K L hLK σ
  · exact D.fixedFieldNormalizedDegree_generator K L hLK σ

/-- **At exponent one the fixed field's degree is at most the extension's**
— the index estimate in the finiteness of the Frobenius fixed field
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:968`]
[Yamaguchi2026]). -/
theorem frobeniusClosure_index_le_extensionIndex_of_exponent_eq_one
    (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    [hLfinite : Finite (K.field.toSubgroup ⧸
      L.toSubgroup.subgroupOf K.field.toSubgroup)]
    (σ : D.FrobeniusElements K L hLK)
    (hσ : D.frobeniusExponent K L hLK σ = 1) :
    (D.frobeniusClosure K L hLK σ).toSubgroup.index ≤
      (L.toSubgroup.subgroupOf K.field.toSubgroup).index := by
  let Q := K.field.toSubgroup ⧸ D.extensionInertiaWithin K.field L hLK
  let dQ : Q →ₜ* ProfiniteIntegerMul :=
    D.extensionNormalizedDegreeContinuous K L hLK
  let H : Subgroup Q := dQ.toMonoidHom.ker
  let Γ : Subgroup Q :=
    (D.frobeniusClosure K L hLK σ).toSubgroup
  let j := D.extensionDegreeKernelRestriction K L hLK
  letI : Finite H :=
    Finite.of_injective j
      (D.extensionDegreeKernelRestriction_injective K L hLK)
  have hΓmap : Γ.map dQ.toMonoidHom =
      (D.frobeniusClosureDegree K L hLK σ).toMonoidHom.range := by
    ext z
    constructor
    · rintro ⟨q, hq, rfl⟩
      exact ⟨⟨q, hq⟩, rfl⟩
    · rintro ⟨q, rfl⟩
      exact ⟨q.1, q.2, rfl⟩
  have htopmap : (⊤ : Subgroup Q).map dQ.toMonoidHom = ⊤ := by
    apply top_unique
    intro z _
    obtain ⟨q, hq⟩ :=
      D.extensionNormalizedDegreeContinuous_surjective K L hLK z
    exact ⟨q, trivial, hq⟩
  have himage : (Γ.map dQ.toMonoidHom).relIndex
      ((⊤ : Subgroup Q).map dQ.toMonoidHom) = 1 := by
    rw [hΓmap, htopmap, Subgroup.relIndex_top_right,
      D.frobeniusClosureDegree_range K L hLK σ,
      AddSubgroup.index_toSubgroup,
      ProfiniteInteger.index_span_natCast, hσ]
  have hΓker : Γ ⊓ dQ.toMonoidHom.ker = ⊥ := by
    apply le_antisymm
    · intro q hq
      let γ : D.frobeniusClosure K L hLK σ := ⟨q, hq.1⟩
      have hγDegreeOne :
          D.frobeniusClosureDegree K L hLK σ γ = 1 := by
        change dQ q = 1
        exact hq.2
      have hγNormalizedOne :
          D.fixedFieldNormalizedDegree K L hLK σ γ = 1 := by
        apply Multiplicative.ext
        have hrel :=
          D.frobeniusExponent_nsmul_fixedFieldNormalizedDegree
            K L hLK σ γ
        rw [hσ, one_nsmul, hγDegreeOne] at hrel
        simpa using hrel
      have hγone : γ = 1 :=
        D.frobeniusFixedField_normalizedDegree_injective K L hLK σ (by
          rw [map_one]
          exact hγNormalizedOne)
      change q = 1
      exact congrArg Subtype.val hγone
    · exact bot_le
  have hkernel : (Γ ⊓ dQ.toMonoidHom.ker).relIndex
      ((⊤ : Subgroup Q) ⊓ dQ.toMonoidHom.ker) =
      Nat.card H := by
    rw [hΓker]
    have htopker : (⊤ : Subgroup Q) ⊓ dQ.toMonoidHom.ker =
        dQ.toMonoidHom.ker := inf_eq_right.mpr le_top
    rw [htopker]
    change (⊥ : Subgroup Q).relIndex H = Nat.card H
    rw [Subgroup.relIndex_bot_left]
  have hindex : Γ.index = Nat.card H := by
    rw [← Subgroup.relIndex_top_right]
    rw [relIndex_eq_map_relIndex_mul_inf_ker_relIndex dQ.toMonoidHom le_top,
      himage, hkernel, one_mul]
  have hcard_le : Nat.card H ≤
      Nat.card (K.field.toSubgroup ⧸
        L.toSubgroup.subgroupOf K.field.toSubgroup) :=
    Nat.card_le_card_of_injective j
      (D.extensionDegreeKernelRestriction_injective K L hLK)
  calc
    (D.frobeniusClosure K L hLK σ).toSubgroup.index =
        Nat.card H := hindex
    _ ≤ Nat.card (K.field.toSubgroup ⧸
        L.toSubgroup.subgroupOf K.field.toSubgroup) := hcard_le
    _ = (L.toSubgroup.subgroupOf K.field.toSubgroup).index :=
      (Subgroup.index_eq_card
        (L.toSubgroup.subgroupOf K.field.toSubgroup)).symm

/-- **The procyclic degree isomorphism**: `d_Σ` identifies `Γ` continuously
with `ℤ̂`; on the field side its trivial kernel says the fixed field's
maximal unramified extension is the whole tower ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:1063`]
[Yamaguchi2026]). -/
def frobeniusFixedField_normalizedDegreeEquiv (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosure K L hLK σ ≃ₜ* ProfiniteIntegerMul := by
  let Γ := D.frobeniusClosure K L hLK σ
  letI : CompactSpace K.field.toSubgroup := by
    change CompactSpace K.field
    infer_instance
  letI : CompactSpace Γ := by infer_instance
  exact continuousMulEquivOfBijectiveCompactToT2
    (D.fixedFieldNormalizedDegree K L hLK σ).toMonoidHom
    (D.fixedFieldNormalizedDegree K L hLK σ).continuous_toFun
    ⟨D.frobeniusFixedField_normalizedDegree_injective K L hLK σ,
      D.fixedFieldNormalizedDegree_surjective K L hLK σ⟩

/-- The degree isomorphism evaluates by restriction. -/
@[simp]
theorem frobeniusFixedField_normalizedDegreeEquiv_apply (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK)
    (a : D.frobeniusClosure K L hLK σ) :
    D.frobeniusFixedField_normalizedDegreeEquiv K L hLK σ a =
      D.fixedFieldNormalizedDegree K L hLK σ a :=
  rfl

/-- The kernel-triviality form of the procyclic degree isomorphism
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:1103`]
[Yamaguchi2026]). -/
theorem frobeniusFixedField_kernel (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    (D.fixedFieldNormalizedDegree K L hLK σ).toMonoidHom.ker = ⊥ :=
  (D.fixedFieldNormalizedDegree K L hLK σ).toMonoidHom.ker_eq_bot_iff.mpr
    (D.frobeniusFixedField_normalizedDegree_injective K L hLK σ)

/-- **The Frobenius over the fixed field `Σ`**, the element `d_Σ` sends to
the generator ([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:1115`]
[Yamaguchi2026]). -/
def fixedFieldFrobenius (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusClosure K L hLK σ :=
  (D.frobeniusFixedField_normalizedDegreeEquiv K L hLK σ).symm
    (Multiplicative.ofAdd (1 : ProfiniteInteger))

/-- **The chosen lift is the Frobenius of its own fixed field**
([Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/FrobeniusFixedField.lean:1128`]
[Yamaguchi2026]). -/
theorem frobeniusFixedField_frobenius (D : DegreeData G)
    [IsTopologicalGroup G] [CompactSpace G] [T2Space G]
    [TotallyDisconnectedSpace G]
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hLnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    (σ : D.FrobeniusElements K L hLK) :
    D.frobeniusInClosure K L hLK σ =
      D.fixedFieldFrobenius K L hLK σ := by
  apply (D.frobeniusFixedField_normalizedDegreeEquiv K L hLK σ).injective
  rw [D.frobeniusFixedField_normalizedDegreeEquiv_apply]
  rw [D.fixedFieldNormalizedDegree_generator]
  exact
    ((D.frobeniusFixedField_normalizedDegreeEquiv
      K L hLK σ).apply_symm_apply _).symm

end DegreeData

end

end Atlas.Knowledge
