import Mathlib
import Atlas.Knowledge.AbelianizedGaloisCyclotomicRigidity
import Atlas.Knowledge.AbsoluteAbelianOpenSubgroupField
import Atlas.Knowledge.AbsoluteAbelianRestriction
import Atlas.Knowledge.AbsoluteFiniteQuotientEquiv
import Atlas.Knowledge.AbsoluteLocalArtinFrobenius
import Atlas.Knowledge.AbsoluteLocalArtinMonoidHom
import Atlas.Knowledge.AbsoluteLocalArtinNormKernel
import Atlas.Knowledge.CycloField
import Atlas.Knowledge.IsMixedCharLocalField
import Atlas.Knowledge.UniformizerUnitsGenerate

/-!
# local reciprocity

The local reciprocity map of a mixed-characteristic local field, as a characterization:
`IsLocalReciprocity K φ` says the homomorphism `φ : Kˣ → G_K^ab` has dense range, cuts out
the norm subgroup of every finite abelian subextension, and satisfies the arithmetic
Frobenius normalization on roots of unity. These are the properties that classically pin the
Artin map `Art_K` — uniqueness is proved here, with no class-field input, and existence is
proved from the layer's absolute local Artin homomorphism, the summit of the reciprocity
engine (#104); the profinite-completion isomorphism `K̂ˣ ≅ G_K^ab`, recorded here, is proved
in `Atlas.Knowledge.UnitsCompletionOfLocalExistence`. The map is
`Atlas.Knowledge.absoluteLocalArtinMonoidHom`, the witness of the existence theorem; every
consumer of `Art_K` in this layer still takes a `φ` with this predicate, which uniqueness
makes unambiguous.

## Main definitions

* `IsLocalReciprocity` — dense range, norm kernels, Frobenius normalization.

## Main statements

* `exists_isLocalReciprocity` — the Artin map exists; proved, the witness being
  `Atlas.Knowledge.absoluteLocalArtinMonoidHom`.
* `IsLocalReciprocity.unique` — the three properties pin the map; proved.

## Implementation notes

`G_K^ab` is `Field.absoluteGaloisGroupAbelianization K`, defeq to the
`mStepSolvableQuotient … 1` of `Atlas.Knowledge.AbelianizedGaloisRecovery`; stating over the
algebraic closure is legitimate because `CharZero` makes it Galois. The `normKernel` field
renders "the kernel of `φ` followed by restriction to `L` is the norm subgroup" without
constructing the factored restriction: preimage of the image of the fixing subgroup equals
the range of the unit norm. The `frobenius` field quantifies over every lift `σ` of `φ (u)`
— all lifts agree on abelian subextensions, and the ∀-form keeps the statement free of the
descended map. The completion claim — the second of this predicate's two claims,
`IsLocalReciprocity.unitsCompletion_continuousMulEquiv`, which was recorded here ahead of
its proof and is now `Atlas.Knowledge.UnitsCompletionOfLocalExistence`'s, its statement
unchanged, since the proof rests on that reduction item, which imports this one — is stated
against Mathlib's profinite completion, which completes against *all* finite-index normal
subgroups; its agreement with the topological completion of the classical statement is the
char-0 fact that every finite-index subgroup of `Kˣ` is open — false in equal
characteristic, which is why `IsMixedCharLocalField` is load-bearing and the read
repository, which proves the comparison only under an undischarged openness hypothesis
(`LocalClassFieldTheory/Infinite/AbstractProfiniteCompletionComparison.lean:298`), states
its own completion instead. The `∃ e` shape, rather than a `ProfiniteGrp` bundling, is
forced: the compactness instances do not synthesize through the `absoluteGaloisGroup`
definition. The existence proof assembles the engine's three merged fields at
`Atlas.Knowledge.absoluteLocalArtinMonoidHom`: its dense range, the norm-kernel identity
`Atlas.Knowledge.absoluteLocalArtinMonoidHom_comap_restrictionKernel` read through the
restriction-kernel dictionary — the field's `[IsGalois]`-plus-commutativity shape becomes
the dictionary's `[IsAbelianGalois]` by a `letI` — and the Frobenius normalization
`Atlas.Knowledge.absoluteLocalArtinMonoidHom_frobenius`, stated verbatim as the field.

The uniqueness proof needs none of the theory the existence proof draws on. Uniformizer units
generate `Kˣ`, since the integers are a discrete valuation ring, so it is enough to pin
`φ (π)` for a uniformizer `π`. The `normKernel` field makes `φ (π)` and `ψ (π)` members of
exactly the same open subgroups — every open subgroup of `G_K^ab` is the pushforward of the
fixing subgroup of a finite abelian subextension, its preimage containing the commutator — so
`ψ (π)` lies in the closed procyclic subgroup generated by `φ (π)`. Against a fixed open
subgroup `U`, take `d` the order of `φ (π)` modulo `U` and read both elements on the
cyclotomic floor `K (μ_m)` with `m = q ^ d - 1`: the `frobenius` field forces both
restrictions to be the `q`-power map, whose order on the `m`-th roots of unity is exactly `d`,
and the two memberships then differ by `φ (π) ^ (d ⋅ k) ∈ U`. The discrepancy lies in every
open subgroup of a group whose identity is closed, hence vanishes. The `denseRange` field is
nowhere used: `normKernel` and `frobenius` alone pin the map, so the proof gives strictly more
than the docstring's "three properties" phrasing asks. The open-subgroup correspondence is
`Atlas.Knowledge.absoluteAbelianOpenSubgroupField`; the cyclotomic rigidity and uniformizer
generation arguments are `Atlas.Knowledge.abelianizedGalois_eq_of_cyclotomic` and
`Atlas.Knowledge.uniformizerUnits_generate`, also used by norm naturality. The cyclotomic-floor
apparatus the proof also built — `cycloField` with its splitting-field instances, `mem_cycloField`,
`cycloField_aut_comm`, and the root-set reading `cycloField_pow_eq_one_of_mem_rootSet` — sat
under the same deferral until its second consumer arrived with the `frobenius`-field bricks of
#104: Brick C promoted it to `Atlas.Knowledge.CycloField` at the weaker hypotheses each piece
needs, and this file now imports the promoted names, its proofs unchanged but for the two
call-site names.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Hyeon2025] S.-H. Hyeon, *The m-step solvable anabelian geometry of mixed-characteristic
  local fields*, J. London Math. Soc. **112** (2025), e70402.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

open ValuativeRel

namespace Atlas.Knowledge

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsMixedCharLocalField K]

/-- The **local reciprocity** characterization of a homomorphism
`φ : Kˣ →* G_K^ab`: dense range, norm kernels at every finite abelian level, and the
arithmetic Frobenius normalization. These are the properties that pin the Artin map
([Serre 1979, Chap. XIII, §4, pp.195–198][Serre1979];
[Milne 2020, Chap. I, §1, Thm. 1.1, p.20][MilneCFT];
[Hyeon 2025, §3, p.10][Hyeon2025]; Yamaguchi 2026,
`LocalClassFieldTheory/Infinite/ProfiniteLocalReciprocity.lean:144`). -/
structure IsLocalReciprocity (φ : Kˣ →* Field.absoluteGaloisGroupAbelianization K) :
    Prop where
  /-- The range is dense: at every finite abelian level the induced map surjects. -/
  denseRange : DenseRange φ
  /-- At every finite abelian subextension `L`, the preimage under `φ` of the image of the
  fixing subgroup of `L` in `G_K^ab` is exactly the norm subgroup `N_{L/K} (Lˣ)`: the induced
  map is `Kˣ / N_{L/K} (Lˣ) ≅ Gal (L/K)`. -/
  normKernel : ∀ (L : IntermediateField K (AlgebraicClosure K)) [FiniteDimensional K L]
    [IsGalois K ↥L], (∀ σ τ : ↥L ≃ₐ[K] ↥L, σ * τ = τ * σ) →
    Subgroup.comap φ
        (Subgroup.map
          (QuotientGroup.mk' (commutator (Field.absoluteGaloisGroup K)).topologicalClosure)
          (IntermediateField.fixingSubgroup L))
      = MonoidHom.range (Units.map (Algebra.norm K (S := ↥L)))
  /-- The arithmetic normalization: every lift of `φ (π)`, `π` a uniformizer, acts on the
  prime-to-`p` roots of unity by `ζ ↦ ζ ^ q`, `q = Nat.card 𝓀[K]` — uniformizer ↦ arithmetic
  Frobenius, read on the maximal unramified subextension. -/
  frobenius : ∀ (u : Kˣ) (hu : (u : K) ∈ 𝒪[K]), Irreducible (⟨(u : K), hu⟩ : 𝒪[K]) →
    ∀ σ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K,
      (QuotientGroup.mk (σ : Field.absoluteGaloisGroup K) :
        Field.absoluteGaloisGroupAbelianization K) = φ u →
    ∀ m : ℕ, Nat.Coprime m (Nat.card 𝓀[K]) →
    ∀ ζ : AlgebraicClosure K, ζ ^ m = 1 → σ ζ = ζ ^ Nat.card 𝓀[K]

/-- The absolute local Artin homomorphism has dense range,
the norm kernels, and the Frobenius normalization
([Serre 1979, Chap. XIII, §4, pp.195–197][Serre1979];
[Milne 2020, Chap. I, §1, Thm. 1.1, p.20][MilneCFT];
Yamaguchi 2026,
`LocalClassFieldTheory/Infinite/ProfiniteLocalReciprocity.lean:144`). -/
theorem isLocalReciprocity_absoluteLocalArtinMonoidHom :
    IsLocalReciprocity K (absoluteLocalArtinMonoidHom K) where
  denseRange := absoluteLocalArtinMonoidHom_denseRange K
  normKernel := by
    intro L _ _ h
    letI : IsAbelianGalois K ↥L := { is_comm := ⟨h⟩ }
    rw [← absoluteFiniteQuotientPreimage_restrictionKernel K L,
      absoluteFiniteQuotientPreimage_map_eq]
    exact absoluteLocalArtinMonoidHom_comap_restrictionKernel K L
  frobenius := absoluteLocalArtinMonoidHom_frobenius K

/-- The local reciprocity map exists
([Serre 1979, Chap. XIII, §4, pp.195–197][Serre1979]). -/
theorem exists_isLocalReciprocity :
    ∃ φ : Kˣ →* Field.absoluteGaloisGroupAbelianization K, IsLocalReciprocity K φ :=
  ⟨absoluteLocalArtinMonoidHom K, isLocalReciprocity_absoluteLocalArtinMonoidHom K⟩

namespace IsLocalReciprocity

variable {K}
variable {φ ψ : Kˣ →* Field.absoluteGaloisGroupAbelianization K}

/-- The characterization pins the map: two homomorphisms satisfying it are equal — on the
uniformizers that generate `Kˣ`, the norm kernels decide the same open subgroups and the
Frobenius normalization pins the cyclotomic restrictions, which pins the element. The proof
is class-field-free and never touches `denseRange`: the other two fields alone suffice. The
classical statement is uniqueness in [Milne 2020, Chap. I, §1, Thm. 1.1, p.20][MilneCFT]. -/
theorem unique (hφ : IsLocalReciprocity K φ) (hψ : IsLocalReciprocity K ψ) : φ = ψ := by
  haveI : IsGalois K (AlgebraicClosure K) := ⟨⟩
  haveI : CompactSpace (Field.absoluteGaloisGroup K) :=
    inferInstanceAs (CompactSpace (AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K))
  -- the two maps agree on every uniformizer unit
  have key : ∀ (u : Kˣ) (hu : (u : K) ∈ 𝒪[K]),
      Irreducible (⟨(u : K), hu⟩ : 𝒪[K]) → φ u = ψ u := by
    intro u hu hirr
    -- the norm subgroups decide membership in every open subgroup, identically
    have hmem : ∀ V : Subgroup (Field.absoluteGaloisGroupAbelianization K),
        IsOpen (V : Set (Field.absoluteGaloisGroupAbelianization K)) →
          (φ u ∈ V ↔ ψ u ∈ V) := by
      intro V hV
      obtain ⟨L, hfin, hgal, hcomm, hmap⟩ := absoluteAbelianOpenSubgroupField K hV
      haveI := hfin
      haveI := hgal
      have h1 := hφ.normKernel L hcomm
      have h2 := hψ.normKernel L hcomm
      rw [hmap] at h1 h2
      constructor
      · intro h
        exact (by rw [h2, ← h1]; exact h : u ∈ Subgroup.comap ψ V)
      · intro h
        exact (by rw [h1, ← h2]; exact h : u ∈ Subgroup.comap φ V)
    exact abelianizedGalois_eq_of_cyclotomic K
      (fun V hV => (hmem V hV).mp) (Nat.card 𝓀[K]) Finite.one_lt_card
      (fun m hm σ hσ => hφ.frobenius u hu hirr σ hσ m hm)
      (fun m hm σ hσ => hψ.frobenius u hu hirr σ hσ m hm)
  -- extend from the uniformizer units, which generate
  ext x
  have hx : x ∈ Subgroup.closure
      {u : Kˣ | ∃ hu : (u : K) ∈ 𝒪[K], Irreducible (⟨(u : K), hu⟩ : 𝒪[K])} := by
    rw [uniformizerUnits_generate]
    trivial
  induction hx using Subgroup.closure_induction with
  | mem u hu => obtain ⟨hu', hirr⟩ := hu; exact key u hu' hirr
  | one => rw [map_one, map_one]
  | mul a b _ _ ha hb => rw [map_mul, map_mul, ha, hb]
  | inv a _ ha => rw [map_inv, map_inv, ha]

end IsLocalReciprocity

end Atlas.Knowledge
