import Mathlib
import Atlas.Knowledge.AbelianizedKummerRootQuotient
import Atlas.Knowledge.CycloField

/-!
# Kummer field

The Kummer extension `K (a ^ (1 / n))` of the literature, as a subfield of the algebraic
closure: `kummerField K n a` is the field generated by all `n`-th roots of `a`, the splitting
field of `X ^ n - C a`. It is finite over `K`, Galois in characteristic zero when `a ≠ 0`,
and once `K` holds a primitive `n`-th root of unity an automorphism of it is determined by
its value at one root and its Galois group is commutative — the facts
`Atlas.Knowledge.LocalHilbertSymbolSkewSymmetry` consumes when it reads the reciprocity map's
norm kernel on this field. At `a = 1` it is the cyclotomic floor
`Atlas.Knowledge.CycloField`, definitionally. Ramification is not this item's: at a unit `a`
and an exponent `n` that is a unit of the integers the field is unramified, which is what the
tame formula's discharge will read the Frobenius congruence on, and that is stated where it
is proved.

## Main definitions

* `kummerField` — `IntermediateField.adjoin K ((X ^ n - C a).rootSet (AlgebraicClosure K))`.

## Main statements

* `mem_rootSet_X_pow_sub_C_iff`, `mem_kummerField_of_pow_eq`, `exists_mem_kummerField_pow_eq`
  — the roots of `X ^ n - C a` are the `n`-th roots of `a`, every one lies in the field, and
  one exists; proved.
* `cycloField_eq_kummerField` — the cyclotomic floor is the Kummer field of `1`, by `rfl`;
  proved.
* `kummerField_isSplittingField`, `kummerField_finiteDimensional`, `kummerField_isGalois` —
  the splitting-field, finiteness and Galois instances; proved.
* `kummerField_algEquiv_ext` — with the roots of unity in the base, an automorphism is
  determined by its value at one root; proved.
* `kummerField_aut_comm` — with the roots of unity in the base, the Galois group is
  commutative; proved.

## Implementation notes

The field is the adjunction of the whole root set and not `K⟮β⟯` for a chosen root: it names
no root, so its Galois-ness is Mathlib's `IntermediateField.adjoin_rootSet_isSplittingField`
with `IsGalois.of_separable_splitting_field` and `Polynomial.separable_X_pow_sub_C` — the
last needs `(n : K) ≠ 0`, supplied by `CharZero K` and `NeZero n`, and `a ≠ 0`, supplied by a
unit `a : Kˣ` so that the instance is keyed on the coercion. Extensionality on the root set
is `IntermediateField.adjoin_algHom_ext` applied to the definition directly; routing it
through `IntermediateField.algHom_ext_of_eq_adjoin` with `rfl` for the defining equation
sends `whnf` into a timeout on the root set, and so does an `abbrev` in place of the `def`.
Commutativity is the commutation of two automorphisms on a root,
`Atlas.Knowledge.kummerRoot_apply_apply_comm`, read through the extensionality, so Mathlib's
cyclicity of Kummer extensions — stated for irreducible `X ^ n - C a` only — is not needed
and no irreducibility is assumed: the field is the splitting field for every `a`, the `n`-th
powers included, where it is `K` itself. Abelianness is a theorem rather than an instance,
since it needs the roots of unity in the base, which is not an instance-shaped hypothesis. At
`a = 1` the definition is `Atlas.Knowledge.cycloField` verbatim, and
`cycloField_eq_kummerField` records it by `rfl`: `cycloField_isSplittingField` and
`cycloField_finiteDimensional` are the special cases of the instances here, while
`cycloField_aut_comm` is not the special case of `kummerField_aut_comm`, since the floor is
abelian with no primitive root in the base and the Kummer field is abelian only with one. The
source works with a simple extension of one chosen root
(`KummerTheory/Concrete/SimpleExtension.lean:55`), generated by that root (`:107`), finite
(`:140`) and abelian Galois (`:153`) under the same hypotheses; once `K` holds a primitive
`n`-th root of unity the two fields coincide — without one they need not, `ℚ⟮∛2⟯` against the
degree-six splitting field of `X ^ 3 - 2` — and the ambient closures differ, the separable
closure there against the algebraic closure here, which agree in characteristic zero, where
this item's Galois instance lives. The root-free presentation is what lets the Hilbert-symbol
items quantify over every root.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

open Polynomial

namespace Atlas.Knowledge

variable (K : Type*) [Field K]

/-- The **Kummer field** `K (a ^ (1 / n))` inside the algebraic closure: the subfield
generated by all `n`-th roots of `a`, the splitting field of `X ^ n - C a`
([Serre 1979, Chap. X, §3, p.155 and Chap. XIV, §2, p.206][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/SimpleExtension.lean:55`, the simple extension of one chosen root). -/
noncomputable def kummerField (n : ℕ) (a : K) : IntermediateField K (AlgebraicClosure K) :=
  IntermediateField.adjoin K ((X ^ n - C a).rootSet (AlgebraicClosure K))

/-- The roots of `X ^ n - C a` in the closure are the `n`-th roots of `a`. -/
theorem mem_rootSet_X_pow_sub_C_iff {n : ℕ} (hn : n ≠ 0) (a : K) (x : AlgebraicClosure K) :
    x ∈ (X ^ n - C a).rootSet (AlgebraicClosure K) ↔
      x ^ n = algebraMap K (AlgebraicClosure K) a := by
  rw [Polynomial.mem_rootSet]
  constructor
  · rintro ⟨-, hx⟩
    simpa [sub_eq_zero] using hx
  · intro hx
    refine ⟨Polynomial.X_pow_sub_C_ne_zero (Nat.pos_of_ne_zero hn) _, ?_⟩
    simp [hx]

/-- An `n`-th root of `a` lies in the Kummer field. -/
theorem mem_kummerField_of_pow_eq {n : ℕ} (hn : n ≠ 0) {a : K} {x : AlgebraicClosure K}
    (hx : x ^ n = algebraMap K (AlgebraicClosure K) a) : x ∈ kummerField K n a :=
  IntermediateField.subset_adjoin K _ ((mem_rootSet_X_pow_sub_C_iff K hn a x).mpr hx)

/-- The Kummer field holds an `n`-th root of `a`: the closure has one. -/
theorem exists_mem_kummerField_pow_eq {n : ℕ} (hn : n ≠ 0) (a : K) :
    ∃ x : AlgebraicClosure K, x ∈ kummerField K n a ∧
      x ^ n = algebraMap K (AlgebraicClosure K) a := by
  obtain ⟨x, hx⟩ := IsAlgClosed.exists_pow_nat_eq (algebraMap K (AlgebraicClosure K) a)
    (Nat.pos_of_ne_zero hn)
  exact ⟨x, mem_kummerField_of_pow_eq K hn hx, hx⟩

/-- The cyclotomic floor is the Kummer field of `1`: the two definitions agree by `rfl`
([Serre 1979, Chap. X, §3, p.155][Serre1979]). -/
theorem cycloField_eq_kummerField (m : ℕ) : cycloField K m = kummerField K m 1 := rfl

/-- The Kummer field is the splitting field of `X ^ n - C a`. -/
instance kummerField_isSplittingField (n : ℕ) (a : K) :
    (X ^ n - C a).IsSplittingField K (kummerField K n a) :=
  IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)

/-- The Kummer field is finite over the base. -/
instance kummerField_finiteDimensional (n : ℕ) (a : K) :
    FiniteDimensional K (kummerField K n a) :=
  Polynomial.IsSplittingField.finiteDimensional _ (X ^ n - C a)

/-- In characteristic zero the Kummer field of a unit is Galois: `X ^ n - C a` is separable
([Serre 1979, Chap. X, §3, p.155][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/SimpleExtension.lean:153`). -/
instance kummerField_isGalois [CharZero K] (n : ℕ) [NeZero n] (a : Kˣ) :
    IsGalois K (kummerField K n (a : K)) :=
  IsGalois.of_separable_splitting_field
    (Polynomial.separable_X_pow_sub_C (a : K) (Nat.cast_ne_zero.mpr (NeZero.ne n)) a.ne_zero)

variable {K}

/-- When the base holds the `n`-th roots of unity, an automorphism of the Kummer field is
determined by its value at one `n`-th root of `a`: every root is that root times a root of
unity from the base — the character `φ_a (s) = s (x) / x` determines `s`
([Serre 1979, Chap. X, §3, p.155][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/SimpleExtension.lean:107`, the same generation at the chosen root). -/
theorem kummerField_algEquiv_ext {n : ℕ} {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0)
    (a : Kˣ) {β : kummerField K n (a : K)}
    (hβ : (β : AlgebraicClosure K) ^ n = algebraMap K (AlgebraicClosure K) (a : K))
    {σ τ : kummerField K n (a : K) ≃ₐ[K] kummerField K n (a : K)} (h : σ β = τ β) :
    σ = τ := by
  have ha0 : algebraMap K (AlgebraicClosure K) (a : K) ≠ 0 :=
    (map_ne_zero (algebraMap K (AlgebraicClosure K))).mpr a.ne_zero
  have hβ0 : (β : AlgebraicClosure K) ≠ 0 := fun h0 => by
    rw [h0, zero_pow hn] at hβ
    exact ha0 hβ.symm
  apply AlgEquiv.coe_toAlgHom_injective
  refine IntermediateField.adjoin_algHom_ext K (fun x hx => ?_)
  have hx' := (mem_rootSet_X_pow_sub_C_iff K hn (a : K) x).mp hx
  obtain ⟨i, hi⟩ := exists_algebraMap_pow_eq_of_pow_eq_one hζ hn
    (show (x / β) ^ n = 1 by rw [div_pow, hx', hβ, div_self ha0])
  have hxL : (⟨x, mem_kummerField_of_pow_eq K hn hx'⟩ : kummerField K n (a : K))
      = algebraMap K (kummerField K n (a : K)) (ζ ^ i) * β := by
    apply Subtype.ext
    change x = ((algebraMap K (kummerField K n (a : K)) (ζ ^ i) : kummerField K n (a : K)) :
      AlgebraicClosure K) * β
    rw [show ((algebraMap K (kummerField K n (a : K)) (ζ ^ i) : kummerField K n (a : K)) :
        AlgebraicClosure K) = algebraMap K (AlgebraicClosure K) (ζ ^ i) from rfl, hi,
      div_mul_cancel₀ _ hβ0]
  change σ (⟨x, mem_kummerField_of_pow_eq K hn hx'⟩ : kummerField K n (a : K))
    = τ ⟨x, mem_kummerField_of_pow_eq K hn hx'⟩
  rw [hxL, map_mul, map_mul, AlgEquiv.commutes, AlgEquiv.commutes, h]

/-- When the base holds the `n`-th roots of unity, the Galois group of the Kummer field is
commutative: two automorphisms commute on a generating root
([Serre 1979, Chap. X, §3, p.155][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/SimpleExtension.lean:153`). -/
theorem kummerField_aut_comm {n : ℕ} {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0)
    (a : Kˣ) (σ τ : kummerField K n (a : K) ≃ₐ[K] kummerField K n (a : K)) :
    σ * τ = τ * σ := by
  obtain ⟨x, hxL, hx⟩ := exists_mem_kummerField_pow_eq K hn (a : K)
  set β : kummerField K n (a : K) := ⟨x, hxL⟩ with hβdef
  have hβ : β ^ n = algebraMap K (kummerField K n (a : K)) (a : K) :=
    Subtype.ext (by simp [hβdef, hx])
  refine kummerField_algEquiv_ext hζ hn a (β := β) hx ?_
  rw [AlgEquiv.mul_apply, AlgEquiv.mul_apply]
  exact kummerRoot_apply_apply_comm hζ hn a σ τ hβ

end Atlas.Knowledge
