import Mathlib
import Atlas.Knowledge.AbelianizedKummerRootQuotient
import Atlas.Knowledge.KummerCharacterEquiv
import Atlas.Knowledge.KummerRadicalSubgroup

/-!
# Kummer norm of `c ^ n - a`

In a finite Galois extension `L` of `K` generated by an `n`-th root `β` of `a : Kˣ`, with `K`
holding a primitive `n`-th root of unity, every `c ^ n - a` with `c : K` is a norm from `L`:
the polynomial identity `c ^ n - a = ∏ (c - ξ β)` over the `n`-th roots of unity `ξ` regroups
along the cosets of the image of `Gal (L/K)` in `μ_n` under the root character `σ ↦ σ β / β`,
and each coset's product is the norm of `c - ξ₀ β` for its representative `ξ₀`. At `c = 0`
this is `-a` and at `c = 1` it is `1 - a` — the two norms behind the symbol identities
`(a, -a) = 1` and `(a, 1 - a) = 1` of `Atlas.Knowledge.LocalHilbertSymbolSkewSymmetry`.
Nothing about local fields enters.

## Main statements

* `kummerPowSubNorm` — `∃ y : L, Algebra.norm K y = c ^ n - a`; proved.
* `exists_units_map_eq_of_pow_eq_one` — the roots of unity of `L` come from the base, in the
  units form the Kummer character homomorphism takes; proved.
* `apply_eq_self_of_pow_eq_one` — automorphisms fix the roots of unity of `L`; proved.

## Implementation notes

The generation hypothesis is the injectivity of `σ ↦ σ β` on `Gal (L/K)`, `hgen`, rather than
`K⟮β⟯ = ⊤`: it is what the argument consumes, and the consumer obtains it from
`Atlas.Knowledge.kummerField_algEquiv_ext` on the Kummer field. The character is the layer's
`Atlas.Knowledge.kummerCharacterHom` at the class of `a` in the radical subgroup, read
through `Atlas.Knowledge.kummerCharacterHom_apply` at the unit `β`; its injectivity is `hgen`
through the root quotient. The coset decomposition is `Subgroup.exists_isComplement_left` for
the character's range inside `rootsOfUnity n L`, with `Subgroup.IsComplement.equiv` splitting
`∏ ξ` into `∏ s, ∏ t` over a transversal and the range, the inner product reindexed to
`Gal (L/K)` by `MonoidHom.ofInjective` and collapsed by `Algebra.norm_eq_prod_automorphisms`.
The coset products are stated over the set-subtype of the range that the complement
equivalence produces, not over the subgroup's own subtype: unifying the two `Fintype`
instances, both classical over `Fintype.ofFinite`, sends `whnf` into a timeout. The full
product is `X_pow_sub_C_eq_prod` evaluated at `c`, reindexed from `Finset.range n` to the
roots of unity by `IsPrimitiveRoot.pow_inj` and `IsPrimitiveRoot.eq_pow_of_pow_eq_one`.
Serre's proof is this regrouping with the cosets indexed as `j ≡ i mod d`, `d` the largest
divisor of `n` for which `a` is a `d`-th power; the transversal replaces that indexing. The
source proves the `c = 1` case in its transposed slot
(`KummerTheory/Concrete/SimpleExtensionNorm.lean:25`) by the same quotient of `μ_n` with
`Quotient.out` representatives; the general `c` is Serre's and costs nothing more.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

namespace Atlas.Knowledge

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Every `n`-th root of unity of `L`, as a unit, is the image of a unit of the base once the
base holds a primitive `n`-th root of unity — the hypothesis shape of
`Atlas.Knowledge.kummerCharacterHom`. -/
theorem exists_units_map_eq_of_pow_eq_one {n : ℕ} {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0)
    (u : Lˣ) (hu : u ^ n = 1) :
    ∃ z : Kˣ, Units.map (algebraMap K L).toMonoidHom z = u := by
  have hu' : (u : L) ^ n = 1 := by rw [← Units.val_pow_eq_pow_val, hu, Units.val_one]
  obtain ⟨i, hi⟩ := exists_algebraMap_pow_eq_of_pow_eq_one hζ hn hu'
  refine ⟨Units.mk0 (ζ ^ i) (pow_ne_zero _ (hζ.ne_zero hn)), Units.ext ?_⟩
  simp [hi]

/-- Automorphisms of `L` fix its `n`-th roots of unity, which come from the base. -/
theorem apply_eq_self_of_pow_eq_one {n : ℕ} {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0)
    (σ : L ≃ₐ[K] L) {ξ : L} (hξ : ξ ^ n = 1) : σ ξ = ξ := by
  obtain ⟨i, hi⟩ := exists_algebraMap_pow_eq_of_pow_eq_one hζ hn hξ
  rw [← hi, AlgEquiv.commutes]

/-- **`c ^ n - a` is a norm from `K (a ^ (1 / n))`**: for `L` generated over `K` by an `n`-th
root `β` of `a`, the identity `c ^ n - a = ∏ (c - ξ β)` over the `n`-th roots of unity `ξ`
regroups along the cosets of the root character's range, and each coset's product is the norm
of `c - ξ₀ β` for its representative `ξ₀`
([Serre 1979, Chap. XIV, §2, Prop. 4 iv, p.206][Serre1979]; Yamaguchi 2026,
`KummerTheory/Concrete/SimpleExtensionNorm.lean:25`, the case `c = 1`). -/
theorem kummerPowSubNorm [FiniteDimensional K L] [IsGalois K L] {n : ℕ} {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (hn : n ≠ 0) (a : Kˣ) {β : L}
    (hβ : β ^ n = algebraMap K L (a : K))
    (hgen : ∀ σ τ : L ≃ₐ[K] L, σ β = τ β → σ = τ) (c : K) :
    ∃ y : L, Algebra.norm K y = c ^ n - a := by
  classical
  haveI : NeZero n := ⟨hn⟩
  haveI : Fintype ↥(rootsOfUnity n L) := Fintype.ofFinite _
  have ha0 : algebraMap K L (a : K) ≠ 0 := (map_ne_zero (algebraMap K L)).mpr a.ne_zero
  have hβ0 : β ≠ 0 := fun h => by
    rw [h, zero_pow hn] at hβ
    exact ha0 hβ.symm
  set βu : Lˣ := Units.mk0 β hβ0 with hβu
  have hβu' : βu ^ n = Units.map (algebraMap K L).toMonoidHom a := by
    ext
    simp [hβu, hβ]
  have hmu : ∀ u : Lˣ, u ^ n = 1 → ∃ z : Kˣ, Units.map (algebraMap K L).toMonoidHom z = u :=
    fun u hu => exists_units_map_eq_of_pow_eq_one hζ hn u hu
  have ha : a ∈ kummerRadicalSubgroup K L n := ⟨βu, hβu'⟩
  set χ : (L ≃ₐ[K] L) →* ↥(rootsOfUnity n L) :=
    kummerCharacterHom K L n hmu (QuotientGroup.mk ⟨a, ha⟩) with hχdef
  have hχ : ∀ σ : L ≃ₐ[K] L, ((χ σ : Lˣ) : L) = σ β / β := by
    intro σ
    rw [hχdef, kummerCharacterHom_apply K L n hmu ha hβu' σ]
    simp [hβu, AlgEquiv.smul_units_def]
  have hχinj : Function.Injective χ := by
    intro σ τ hστ
    apply hgen
    have h1 := congrArg (fun z : ↥(rootsOfUnity n L) => ((z : Lˣ) : L)) hστ
    simp only [hχ] at h1
    exact (div_left_inj' hβ0).mp h1
  have hζ' : IsPrimitiveRoot (algebraMap K L ζ) n :=
    hζ.map_of_injective (algebraMap K L).injective
  set ζu : Lˣ := Units.mk0 (algebraMap K L ζ) (hζ'.ne_zero hn) with hζudef
  have hζu : IsPrimitiveRoot ζu n :=
    IsPrimitiveRoot.coe_units_iff.mp (by rw [hζudef, Units.val_mk0]; exact hζ')
  set f : ↥(rootsOfUnity n L) → L := fun ξ => algebraMap K L c - ((ξ : Lˣ) : L) * β with hfdef
  -- the full product is `c ^ n - a`
  have hprod : ∏ ξ : ↥(rootsOfUnity n L), f ξ = algebraMap K L (c ^ n - a) := by
    have hpoly := X_pow_sub_C_eq_prod hζ' (Nat.pos_of_ne_zero hn) hβ
    have heval := congrArg (Polynomial.eval (algebraMap K L c)) hpoly
    simp only [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X, Polynomial.eval_C,
      Polynomial.eval_prod] at heval
    rw [map_sub, map_pow, heval]
    symm
    refine Finset.prod_nbij (fun i => ⟨ζu ^ i, ?_⟩) ?_ ?_ ?_ ?_
    · rw [mem_rootsOfUnity, ← pow_mul, mul_comm, pow_mul, hζu.pow_eq_one, one_pow]
    · intro i _
      exact Finset.mem_univ _
    · intro i hi j hj hij
      exact hζu.pow_inj (Finset.mem_range.mp hi) (Finset.mem_range.mp hj)
        (congrArg Subtype.val hij)
    · intro ξ _
      obtain ⟨i, hi, hξ⟩ := hζ'.eq_pow_of_pow_eq_one ((mem_rootsOfUnity' _ _).mp ξ.2)
      refine ⟨i, Finset.mem_range.mpr hi, Subtype.ext (Units.ext ?_)⟩
      rw [Units.val_pow_eq_pow_val, hζudef, Units.val_mk0]
      exact hξ
    · intro i _
      simp [hfdef, hζudef, Units.val_pow_eq_pow_val]
  -- the coset decomposition of the full product
  obtain ⟨S, hS, -⟩ := χ.range.exists_isComplement_left 1
  have hdecomp : ∏ ξ : ↥(rootsOfUnity n L), f ξ
      = ∏ s : S, ∏ t : ↥((χ.range : Subgroup ↥(rootsOfUnity n L)) : Set ↥(rootsOfUnity n L)),
          f (s.1 * t.1) := by
    have h1 : ∏ ξ : ↥(rootsOfUnity n L), f ξ
        = ∏ p : S × ↥((χ.range : Subgroup ↥(rootsOfUnity n L)) : Set ↥(rootsOfUnity n L)),
            f (p.1.1 * p.2.1) := by
      refine Fintype.prod_equiv hS.equiv f _ (fun ξ => ?_)
      congr 1
      have := hS.equiv_symm_apply (hS.equiv ξ)
      rw [Equiv.symm_apply_apply] at this
      exact this
    exact h1.trans (Fintype.prod_prod_type _)
  -- each coset product is a norm
  have hinner : ∀ s : S,
      ∏ t : ↥((χ.range : Subgroup ↥(rootsOfUnity n L)) : Set ↥(rootsOfUnity n L)), f (s.1 * t.1)
        = algebraMap K L (Algebra.norm K (algebraMap K L c - ((s.1 : Lˣ) : L) * β)) := by
    intro s
    rw [Algebra.norm_eq_prod_automorphisms]
    let e : (L ≃ₐ[K] L) ≃ ↥((χ.range : Subgroup ↥(rootsOfUnity n L)) : Set ↥(rootsOfUnity n L)) :=
      (MonoidHom.ofInjective hχinj).toEquiv.trans (Equiv.subtypeEquivRight fun _ => Iff.rfl)
    refine (Fintype.prod_equiv e _ _ (fun σ => ?_)).symm
    have he : ((e σ : ↥((χ.range : Subgroup ↥(rootsOfUnity n L)) : Set ↥(rootsOfUnity n L))) :
        ↥(rootsOfUnity n L)) = χ σ :=
      MonoidHom.ofInjective_apply hχinj
    have hs : ((s.1 : Lˣ) : L) ^ n = 1 := (mem_rootsOfUnity' _ _).mp s.1.2
    rw [map_sub, map_mul, AlgEquiv.commutes, apply_eq_self_of_pow_eq_one hζ hn σ hs]
    simp only [hfdef, Subgroup.coe_mul, Units.val_mul, he, hχ]
    rw [mul_assoc, div_mul_cancel₀ _ hβ0]
  refine ⟨∏ s : S, (algebraMap K L c - ((s.1 : Lˣ) : L) * β), ?_⟩
  apply (algebraMap K L).injective
  rw [map_prod, ← hprod, hdecomp, map_prod]
  exact Finset.prod_congr rfl (fun s _ => (hinner s).symm)

end Atlas.Knowledge
