import Mathlib

/-!
# local Kronecker–Weber theorem

Every finite abelian extension of `ℚ_[p]` lies in a cyclotomic extension: some
`CyclotomicField m ℚ_[p]`, generated over `ℚ_[p]` by a chosen primitive `m`-th root of
unity, receives an embedding of it. The statement is pure Mathlib vocabulary — nothing
here depends on any other knowledge item — and the claim is recorded ahead of its proof,
which is local class field theory's existence theorem run through norm-subgroup order
reversal in the source.

## Main statements

* `localKroneckerWeber` — recorded ahead of its proof.

## Implementation notes

The primitive-root clause is part of the source's statement, and a port does not weaken
an existential: the recorded claim keeps the witness `ζ` with
`Algebra.adjoin ℚ_[p] {ζ} = ⊤` because dropping it would record a strictly weaker claim
than the theorem being ported. The source consumes the ported theorem nowhere — it is
the reader-facing endpoint, and the global chain runs through a structured variant whose
destructuring discards exactly this witness
(`KroneckerWeber/LocalCyclotomicEmbedding.lean:340`) — so keeping the clause also loses
nothing downstream. `L` is `Type`, not `Type*`, matching the source — the claim is
recorded for the port. Pinned Mathlib has no Kronecker–Weber statement, local or global,
to identify against.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in
  Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

/-- The **local Kronecker–Weber theorem**: every finite abelian extension of `ℚ_[p]`
embeds in a cyclotomic extension of `ℚ_[p]` generated by a primitive root of unity.
Claim recorded ahead of its proof
([Milne 2020, Chap. I, §4, Rem. 4.14, p.49][MilneCFT];
[Yamaguchi 2026, `KroneckerWeber/LocalCyclotomicEmbedding.lean:191`][Yamaguchi2026]). -/
theorem localKroneckerWeber (p : ℕ) [Fact p.Prime] (L : Type) [Field L]
    [Algebra ℚ_[p] L] [FiniteDimensional ℚ_[p] L] [IsAbelianGalois ℚ_[p] L] :
    ∃ m : ℕ, 0 < m ∧ ∃ ζ : CyclotomicField m ℚ_[p],
      IsPrimitiveRoot ζ m ∧ Algebra.adjoin ℚ_[p] ({ζ} : Set _) = ⊤ ∧
      Nonempty (L →ₐ[ℚ_[p]] CyclotomicField m ℚ_[p]) := by
  sorry

end Atlas.Knowledge
