import Mathlib
import Atlas.Knowledge.PadicCycloFieldNormSubgroup
import Atlas.Knowledge.PadicIntegerEquiv
import Atlas.Knowledge.CycloFieldOfDegree
import Atlas.Knowledge.FiniteAbelianSubfieldOrder
import Atlas.Knowledge.StandardOpenSubgroups
import Atlas.Knowledge.UnitsFiniteIndexOpen
import Atlas.Knowledge.LocalNormSubgroupExistence
import Atlas.Knowledge.NormalizedValuation
import Atlas.Knowledge.NormIndexAbelian

/-!
# local Kronecker–Weber theorem

Every finite abelian extension of `ℚ_[p]` lies in a cyclotomic extension: some
`CyclotomicField m ℚ_[p]`, generated over `ℚ_[p]` by a chosen primitive `m`-th root of
unity, receives an embedding of it. The statement is pure Mathlib vocabulary — nothing
here depends on any other knowledge item — and the proof is local class field theory's
existence theorem run through norm-subgroup order reversal: the norm subgroup of the
extension is open of finite index, so it contains a standard subgroup `⟨p ^ f⟩ ⊔ U^(n)`,
which is the norm subgroup of the cyclotomic field of level `(p ^ f - 1) * p ^ n`, and the
order reversal turns that containment of norm subgroups into a containment of fields.
Everything here is proved.

## Main statements

* `localKroneckerWeber` — proved.
* `LocalKroneckerWeber.cycloField_le_of_dvd` — a cyclotomic floor of level dividing `m` lies
  in the floor of level `m`; proved.

## Implementation notes

The primitive-root clause is part of the source's statement, and a port does not weaken
an existential: the recorded claim keeps the witness `ζ` with
`Algebra.adjoin ℚ_[p] {ζ} = ⊤` because dropping it would record a strictly weaker claim
than the theorem being ported. The source consumes the ported theorem nowhere — it is
the reader-facing endpoint, and the global chain runs through a structured variant whose
destructuring discards exactly this witness
(`KroneckerWeber/LocalCyclotomicEmbedding.lean:340`) — so keeping the clause also loses
nothing downstream. `L` is `Type`, not `Type*`, matching the source — the claim was
recorded for the port and its statement has not moved. Pinned Mathlib has no
Kronecker–Weber statement, local or global, to identify against.

The proof follows the source's (`KroneckerWeber/LocalCyclotomicEmbedding.lean:91`) with
the layer's bricks in place of its own. `L` is carried into `AlgebraicClosure ℚ_[p]` as the
field range of `IsAlgClosed.lift`, because the order reversal
`Atlas.Knowledge.finiteAbelian_le_iff_localNormSubgroup_le` and the compositum bound
`Atlas.Knowledge.zpowers_sup_higherUnitGroup_inf_comap_le` both read subfields of the
closure, and the abelian and finite-dimensional instances ride the equivalence
`AlgHom.equivFieldRange`. The norm subgroup of that copy has finite index by
`Atlas.Knowledge.normIndexAbelian` and is therefore open by
`Atlas.Knowledge.unitsFiniteIndexOpen`, which is the step the source takes as a hypothesis;
`Atlas.Knowledge.StandardOpenSubgroups` then places `⟨p ^ f⟩ ⊔ U^(n)` inside it with `f`
the index itself. The unramified factor is the cyclotomic floor of level `p ^ f - 1`, whose
norm subgroup `Atlas.Knowledge.CycloFieldOfDegree` computes at `Nat.card 𝓀[ℚ_[p]] = p`; the
ramified factor is the floor of level `p ^ n`, whose norm subgroup is
`Atlas.Knowledge.PadicCycloFieldNormSubgroup`; both floors lie in the floor of level `m`,
whose norm subgroup is therefore contained in the intersection, and the intersection is
bounded by the standard subgroup. The floor of level `m` is finally identified with
`CyclotomicField m ℚ_[p]` through `Polynomial.IsSplittingField.lift` on `X ^ m - 1`, and
the witness is Mathlib's `IsCyclotomicExtension.zeta`. The cyclotomic fields of the source
are abstract fields generated by a primitive root where the layer's are floors of the
algebraic closure, which is the one place the port's carrier differs from the source's.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

open ValuativeRel Polynomial

namespace Atlas.Knowledge

namespace LocalKroneckerWeber

/-- A cyclotomic floor of level dividing `m` lies in the floor of level `m`: every root of
unity of order dividing `a ∣ m` is an `m`-th root of unity. -/
theorem cycloField_le_of_dvd (K : Type*) [Field K] {a m : ℕ} (hm : m ≠ 0) (h : a ∣ m) :
    cycloField K a ≤ cycloField K m := by
  rw [cycloField, IntermediateField.adjoin_le_iff]
  intro x hx
  have hxa : x ^ a = 1 := cycloField_pow_eq_one_of_mem_rootSet K hx
  obtain ⟨k, rfl⟩ := h
  exact mem_cycloField K hm (by rw [pow_mul, hxa, one_pow])

end LocalKroneckerWeber

open LocalKroneckerWeber PadicCycloFieldNormSubgroup in
/-- The **local Kronecker–Weber theorem**: every finite abelian extension of `ℚ_[p]`
embeds in a cyclotomic extension of `ℚ_[p]` generated by a primitive root of unity
([Milne 2020, Chap. I, §4, Cor. 4.12, p.48][MilneCFT]; Yamaguchi 2026,
`KroneckerWeber/LocalCyclotomicEmbedding.lean:191`). -/
theorem localKroneckerWeber (p : ℕ) [Fact p.Prime] (L : Type) [Field L]
    [Algebra ℚ_[p] L] [FiniteDimensional ℚ_[p] L] [IsAbelianGalois ℚ_[p] L] :
    ∃ m : ℕ, 0 < m ∧ ∃ ζ : CyclotomicField m ℚ_[p],
      IsPrimitiveRoot ζ m ∧ Algebra.adjoin ℚ_[p] ({ζ} : Set _) = ⊤ ∧
      Nonempty (L →ₐ[ℚ_[p]] CyclotomicField m ℚ_[p]) := by
  classical
  have hp : p.Prime := Fact.out
  -- carry `L` into the algebraic closure
  let i : L →ₐ[ℚ_[p]] AlgebraicClosure ℚ_[p] := IsAlgClosed.lift
  let E : IntermediateField ℚ_[p] (AlgebraicClosure ℚ_[p]) := i.fieldRange
  let e : L ≃ₐ[ℚ_[p]] E := i.equivFieldRange
  haveI : FiniteDimensional ℚ_[p] E := LinearEquiv.finiteDimensional e.toLinearEquiv
  haveI : IsAbelianGalois ℚ_[p] E := IsAbelianGalois.of_algHom e.symm.toAlgHom
  -- its norm subgroup is open of finite index
  set H := localNormSubgroup ℚ_[p] E with hH
  haveI hHfin : H.FiniteIndex := ⟨by
    change Nat.card (ℚ_[p]ˣ ⧸ (Units.map (Algebra.norm ℚ_[p])).range) ≠ 0
    rw [normIndexAbelian ℚ_[p] E]
    exact Module.finrank_pos.ne'⟩
  have hHopen : IsOpen (H : Set ℚ_[p]ˣ) := unitsFiniteIndexOpen ℚ_[p] H hHfin
  -- so it contains a standard subgroup `⟨p ^ f⟩ ⊔ U^(n)`
  have hπ := PadicIntegerEquiv.irreducible_natCast p
  obtain ⟨n, hn⟩ :=
    exists_zpowers_sup_higherUnitGroup_le_of_isOpen_finiteIndex ℚ_[p] H hHopen (p : 𝒪[ℚ_[p]]) hπ
  set f := H.index with hf
  have hf0 : f ≠ 0 := Subgroup.FiniteIndex.index_ne_zero
  have hpf : 1 < p ^ f := Nat.one_lt_pow hf0 hp.one_lt
  set m := (p ^ f - 1) * p ^ (n : ℕ) with hm
  have hm0 : m ≠ 0 := Nat.mul_ne_zero (by omega) (pow_ne_zero _ hp.ne_zero)
  haveI : NeZero m := ⟨hm0⟩
  -- the two cyclotomic factors and their norm subgroups
  have hU : localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ f - 1)) =
      Subgroup.comap (normalizedValuationHom ℚ_[p])
        (Subgroup.zpowers (Multiplicative.ofAdd (f : ℤ))) := by
    have h := cycloField_localNormSubgroup ℚ_[p] (d := f) (Nat.pos_of_ne_zero hf0)
    rwa [PadicIntegerEquiv.card_residueField] at h
  have hC := padicCycloFieldNormSubgroup p n
  have hval : normalizedValuation ℚ_[p] (padicPrimeUnit p) = 1 :=
    normalizedValuation_irreducible ℚ_[p] (p : 𝒪[ℚ_[p]]) hπ (padicPrimeUnit p) rfl
  -- the compositum lies in the floor of level `m`, so its norm subgroup is small
  have hle : localNormSubgroup ℚ_[p] (cycloField ℚ_[p] m) ≤ H := by
    calc localNormSubgroup ℚ_[p] (cycloField ℚ_[p] m)
        ≤ localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ f - 1)) ⊓
            localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ))) :=
          le_inf
            (localNormSubgroup_le_of_le ℚ_[p] (cycloField_le_of_dvd ℚ_[p] hm0 (dvd_mul_right _ _)))
            (localNormSubgroup_le_of_le ℚ_[p] (cycloField_le_of_dvd ℚ_[p] hm0 (dvd_mul_left _ _)))
      _ = (Subgroup.zpowers (padicPrimeUnit p) ⊔ higherUnitGroup ℚ_[p] n) ⊓
            Subgroup.comap (normalizedValuationHom ℚ_[p])
              (Subgroup.zpowers (Multiplicative.ofAdd (f : ℤ))) := by
          rw [hU, hC, inf_comm]
      _ ≤ Subgroup.zpowers (padicPrimeUnit p ^ f) ⊔ higherUnitGroup ℚ_[p] n :=
          zpowers_sup_higherUnitGroup_inf_comap_le ℚ_[p] (padicPrimeUnit p) hval f n
      _ ≤ H := hn
  -- order reversal
  have hEle : E ≤ cycloField ℚ_[p] m :=
    (finiteAbelian_le_iff_localNormSubgroup_le ℚ_[p] E (cycloField ℚ_[p] m)).mpr hle
  -- the floor of level `m` maps to `CyclotomicField m ℚ_[p]`
  haveI : IsCyclotomicExtension {m} ℚ_[p] (CyclotomicField m ℚ_[p]) :=
    CyclotomicField.isCyclotomicExtension m ℚ_[p]
  haveI := IsCyclotomicExtension.isSplittingField_X_pow_sub_one m ℚ_[p] (CyclotomicField m ℚ_[p])
  let j : cycloField ℚ_[p] m →ₐ[ℚ_[p]] CyclotomicField m ℚ_[p] :=
    Polynomial.IsSplittingField.lift (cycloField ℚ_[p] m) (X ^ m - 1 : ℚ_[p][X])
      (Polynomial.IsSplittingField.splits (CyclotomicField m ℚ_[p]) (X ^ m - 1 : ℚ_[p][X]))
  exact ⟨m, Nat.pos_of_ne_zero hm0, IsCyclotomicExtension.zeta m ℚ_[p] (CyclotomicField m ℚ_[p]),
    IsCyclotomicExtension.zeta_spec m ℚ_[p] _,
    IsCyclotomicExtension.adjoin_primitive_root_eq_top (IsCyclotomicExtension.zeta_spec m ℚ_[p] _),
    ⟨j.comp ((IntermediateField.inclusion hEle).comp e.toAlgHom)⟩⟩

end Atlas.Knowledge
