import Mathlib
import Atlas.Knowledge.AbstractFixedField
import Atlas.Knowledge.FiniteAbstractField
import Atlas.Knowledge.FiniteResidueAbstractField
import Atlas.Knowledge.LocalResidueDatum
import Atlas.Knowledge.RelativeIndexCardinal
import Atlas.Knowledge.ResidueActionIndex

/-!
# residue degree of a finite abstract field

The residue field a finite abstract field selects inside the residue
algebraic closure of a mixed-characteristic local field: the residue subfield
generated by the decomposition residue field of its fixed field, finite over
the base residue field, whose degree is exactly the residue degree the local
datum attaches to the abstract field. The comparison runs on the common
selected residue field, so it applies when the fixed field is not normal over
the local field. This connects the engine's abstract residue degrees to
actual field degrees (#104).

## Main definitions

* `localAbstractFixedResidueIntermediateField` — the residue subfield of a
  closed subgroup's fixed field.
* `localAbstractFixedResidueFiniteGaloisIntermediateField` — the same
  subfield, packaged for the intrinsic finite-field datum.

## Main statements

* `localAbstractFixedResidueAction_map_eq_fixingSubgroup` — the residue-action
  image of `H` is the fixing subgroup of its residue subfield; proved.
* `localResidueDatum_residueDegree_eq_selectedResidueFinrank` — the abstract
  residue degree is the degree of the selected residue subfield; proved.

## Implementation notes

The residue subfield is `adjoin` of the image of the fixed field's
decomposition residue field, rather than a scalar-tower instance between the
two residue-action quotient presentations, as in the source; the three named
local instances keep typeclass search from unfolding the fixed-field and
residue-action constructions inside finite-dimensionality statements, and are
load-bearing. The engine's finiteness witness is spelled with
`Subgroup.subgroupOf` as in `Atlas.Knowledge.AbstractFixedField`, and the
ambient field is the algebraic closure throughout, with
`Atlas.Knowledge.localResidueDatum`'s names replacing the source's
separable-closure ones. The unnamed `IsAlgClosure`/`IsGalois` pair at the top
is Atlas's, not the source's: the source draws `IsGalois` on the residue pair
from its own global instances, while here it does not synthesize without the
closure bundle — the same device as in `Atlas.Knowledge.ResidueDatumIn`. Not
ported from the source file, as knowledge nothing on the arc consumes: the
scalar-restricted residue action (`:206–249`) and the pointwise
normalized-degree comparison (`:383–450`), whose sole consumer is the
fixed-field local data downstream of the valuation datum.

## References

* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

open scoped Pointwise

open ValuativeRel

namespace Atlas.Knowledge

noncomputable section

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsMixedCharLocalField K]

local instance :
    IsAlgClosure
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (selectedResidueField (localAbsoluteValuationSubring K)) :=
  ⟨inferInstance, inferInstance⟩

local instance :
    IsGalois
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (selectedResidueField (localAbsoluteValuationSubring K)) :=
  inferInstance

/-- **The residue subfield selected by a closed subgroup**: the subfield of
the residue algebraic closure generated by the decomposition residue field of
the subgroup's fixed field ([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:33`]
[Yamaguchi2026]). -/
def localAbstractFixedResidueIntermediateField
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    IntermediateField
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (selectedResidueField (localAbsoluteValuationSubring K)) := by
  let E := abstractFixedField K (AlgebraicClosure K) H
  let A := localAbsoluteValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let kE := decompositionResidueField E A
  exact IntermediateField.adjoin k
    (Set.range (algebraMap kE Omega))

/-- The canonical scalar structure on the selected fixed residue field.
Naming these instances keeps typeclass search from unfolding the fixed-field
and residue-action constructions in finite-dimensionality statements
([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:49`]
[Yamaguchi2026]). -/
local instance localAbstractFixedResidueIntermediateFieldAlgebra
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    Algebra
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  (localAbstractFixedResidueIntermediateField K H).algebra

local instance localAbstractFixedResidueIntermediateFieldSMul
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    SMul
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  @Algebra.toSMul _ _ _ _
    (localAbstractFixedResidueIntermediateFieldAlgebra K H)

local instance localAbstractFixedResidueIntermediateFieldModule
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    Module
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) :=
  @Algebra.toModule _ _ _ _
    (localAbstractFixedResidueIntermediateFieldAlgebra K H)

/-- **Every automorphism over the fixed field preserves the absolute
valuation ring**: the base-change form of the full decomposition-group
statement ([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:75`]
[Yamaguchi2026]). -/
theorem localAbstractFixedDecompositionGroup_eq_top
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    decompositionGroup (abstractFixedField K (AlgebraicClosure K) H)
      (localAbsoluteValuationSubring K) = ⊤ := by
  let E := abstractFixedField K (AlgebraicClosure K) H
  let A := localAbsoluteValuationSubring K
  apply top_unique
  intro tau _htau
  let sigma : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K :=
    tau.restrictScalars K
  have hsigma : sigma • A = A := by
    change sigma ∈ decompositionGroup K A
    rw [localAbsoluteDecompositionGroup_eq_top K]
    exact Subgroup.mem_top sigma
  change tau • A = A
  exact hsigma

/-- **Restricting the local residue action to `H` computes over the fixed
field**: the same automorphism of the selected residue field arises from the
residue action over the fixed field of `H` ([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:94`]
[Yamaguchi2026]). -/
theorem localAbstractFixedResidueAction_apply
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K))
    (sigma : H.toSubgroup)
    (x : selectedResidueField (localAbsoluteValuationSubring K)) :
    localResidueAlgAction K sigma.1 x =
      residueAlgActionOfEqTop
        (abstractFixedField K (AlgebraicClosure K) H)
        (localAbsoluteValuationSubring K)
        (localAbstractFixedDecompositionGroup_eq_top K H)
        (abstractSubgroupEquivGaloisGroup K (AlgebraicClosure K) H sigma) x := by
  let A := localAbsoluteValuationSubring K
  obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective x
  change IsLocalRing.residue A
      ((toDecompositionGroupOfEqTop K A
        (localAbsoluteDecompositionGroup_eq_top K) sigma.1) • a) =
    IsLocalRing.residue A
      ((toDecompositionGroupOfEqTop
        (abstractFixedField K (AlgebraicClosure K) H) A
        (localAbstractFixedDecompositionGroup_eq_top K H)
        (abstractSubgroupEquivGaloisGroup K (AlgebraicClosure K) H sigma)) • a)
  congr 1

/-- **The residue-action image of `H` is the fixing subgroup of its residue
subfield** — the reverse inclusion is surjectivity of the residue action after
changing the base to the fixed field ([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:120`]
[Yamaguchi2026]). -/
theorem localAbstractFixedResidueAction_map_eq_fixingSubgroup
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K)) :
    H.toSubgroup.map (localResidueAlgAction K).toMonoidHom =
      (localAbstractFixedResidueIntermediateField K H).fixingSubgroup := by
  let E := abstractFixedField K (AlgebraicClosure K) H
  let A := localAbsoluteValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let kE := decompositionResidueField E A
  let rhoK := localResidueAlgAction K
  let hE := localAbstractFixedDecompositionGroup_eq_top K H
  let rhoE := residueAlgActionOfEqTop E A hE
  let F := localAbstractFixedResidueIntermediateField K H
  ext tau
  constructor
  · rintro ⟨sigma, hsigma, rfl⟩
    let sigmaH : H.toSubgroup := ⟨sigma, hsigma⟩
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    let T : IntermediateField k Omega :=
      { carrier := {y | rhoK sigma y = y}
        zero_mem' := by simp
        one_mem' := by simp
        add_mem' := by
          intro y z hy hz
          change rhoK sigma y = y at hy
          change rhoK sigma z = z at hz
          change rhoK sigma (y + z) = y + z
          rw [map_add]
          exact congrArg₂ (fun a b : Omega => a + b) hy hz
        mul_mem' := by
          intro y z hy hz
          change rhoK sigma y = y at hy
          change rhoK sigma z = z at hz
          change rhoK sigma (y * z) = y * z
          rw [map_mul]
          exact congrArg₂ (fun a b : Omega => a * b) hy hz
        algebraMap_mem' := fun y => (rhoK sigma).commutes y
        inv_mem' := by
          intro y hy
          change rhoK sigma y = y at hy
          simp [hy] }
    have hrange : Set.range (algebraMap kE Omega) ⊆ T := by
      rintro y ⟨z, rfl⟩
      have hbase : rhoK sigma (algebraMap kE Omega z) =
          algebraMap kE Omega z := by
        rw [localAbstractFixedResidueAction_apply K H sigmaH]
        exact (rhoE (abstractSubgroupEquivGaloisGroup
          K (AlgebraicClosure K) H sigmaH)).commutes z
      change rhoK sigma (algebraMap kE Omega z) =
        algebraMap kE Omega z
      exact hbase
    have hFT : F ≤ T := by
      apply IntermediateField.adjoin_le_iff.mpr
      exact hrange
    have hxT : x ∈ T := hFT hx
    change rhoK sigma x = x
    change rhoK sigma x = x at hxT
    exact hxT
  · intro htau
    let tauE : Omega ≃ₐ[kE] Omega :=
      { tau.toRingEquiv with
        commutes' := fun z => by
          have hzF : algebraMap kE Omega z ∈ F := by
            apply IntermediateField.subset_adjoin
            exact ⟨z, rfl⟩
          exact (IntermediateField.mem_fixingSubgroup_iff F tau).mp
            htau (algebraMap kE Omega z) hzF }
    obtain ⟨sigmaE, hsigmaE⟩ :=
      residueAlgActionOfEqTop_surjective E A hE tauE
    let sigmaH : H.toSubgroup :=
      (abstractSubgroupEquivGaloisGroup K (AlgebraicClosure K) H).symm sigmaE
    refine ⟨sigmaH.1, sigmaH.2, ?_⟩
    apply AlgEquiv.ext
    intro x
    change localResidueAlgAction K sigmaH.1 x = tau x
    rw [localAbstractFixedResidueAction_apply K H sigmaH]
    have hsigmaH : abstractSubgroupEquivGaloisGroup
        K (AlgebraicClosure K) H sigmaH = sigmaE :=
      (abstractSubgroupEquivGaloisGroup
        K (AlgebraicClosure K) H).apply_symm_apply sigmaE
    rw [hsigmaH, hsigmaE]
    rfl

/-- **The residue subfield of a finite abstract field is finite**: the index
of the residue-action image divides the index of `H` by surjectivity
([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:250`]
[Yamaguchi2026]). -/
theorem localAbstractFixedResidueIntermediateField_finiteDimensional
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K))
    [Finite
      ((baseField (Field.absoluteGaloisGroup K)).toSubgroup ⧸
        H.toSubgroup.subgroupOf
          (baseField (Field.absoluteGaloisGroup K)).toSubgroup)] :
    FiniteDimensional
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (localAbstractFixedResidueIntermediateField K H) := by
  let G := Field.absoluteGaloisGroup K
  let A := localAbsoluteValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let rho := (localResidueAlgAction K).toMonoidHom
  let F := localAbstractFixedResidueIntermediateField K H
  letI : Finite (G ⧸ H.toSubgroup) :=
    ambientQuotientFiniteOfAbstractFinite
      K (AlgebraicClosure K) H ‹_›
  have hHindex : H.toSubgroup.index ≠ 0 :=
    Subgroup.index_ne_zero_of_finite
  have hmapIndex : (H.toSubgroup.map rho).index ≠ 0 := by
    intro hzero
    have hdiv : (H.toSubgroup.map rho).index ∣ H.toSubgroup.index :=
      H.toSubgroup.index_map_dvd (localResidueAlgAction_surjective K)
    rw [hzero] at hdiv
    exact hHindex (eq_zero_of_zero_dvd hdiv)
  letI : Finite
      ((Omega ≃ₐ[k] Omega) ⧸ H.toSubgroup.map rho) :=
    (Subgroup.index_ne_zero_iff_finite (H := H.toSubgroup.map rho)).mp
      hmapIndex
  have himage : H.toSubgroup.map rho = F.fixingSubgroup :=
    localAbstractFixedResidueAction_map_eq_fixingSubgroup K H
  letI : Finite ((Omega ≃ₐ[k] Omega) ⧸ F.fixingSubgroup) := by
    rw [← himage]
    infer_instance
  letI : Subgroup.FiniteIndex F.fixingSubgroup :=
    F.fixingSubgroup.finiteIndex_of_finite_quotient
  apply (InfiniteGalois.isOpen_iff_finite (K := Omega) F).1
  exact Subgroup.isOpen_of_isClosed_of_finiteIndex
    F.fixingSubgroup (InfiniteGalois.fixingSubgroup_isClosed F)

/-- **The residue subfield, packaged for the intrinsic finite-field datum**
([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:294`]
[Yamaguchi2026]). -/
def localAbstractFixedResidueFiniteGaloisIntermediateField
    (H : ClosedSubgroup (Field.absoluteGaloisGroup K))
    [Finite
      ((baseField (Field.absoluteGaloisGroup K)).toSubgroup ⧸
        H.toSubgroup.subgroupOf
          (baseField (Field.absoluteGaloisGroup K)).toSubgroup)] :
    FiniteGaloisIntermediateField
      (decompositionResidueField K (localAbsoluteValuationSubring K))
      (selectedResidueField (localAbsoluteValuationSubring K)) := by
  let A := localAbsoluteValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let F := localAbstractFixedResidueIntermediateField K H
  letI : Algebra k F := F.algebra
  letI : Module k F := Algebra.toModule
  letI : FiniteDimensional k F :=
    localAbstractFixedResidueIntermediateField_finiteDimensional K H
  letI : Finite F := Module.finite_of_finite k
  letI : Fintype F := Fintype.ofFinite F
  letI : IsGalois k F := by
    obtain ⟨p, hp⟩ := CharP.exists k
    letI : CharP k p := hp
    letI : CharP F p := charP_of_injective_algebraMap' k p
    exact IsGalois.of_separable_splitting_field
      (galois_poly_separable p (Fintype.card F)
        (let ⟨n, _, hn⟩ := FiniteField.card F p
        hn.symm ▸ dvd_pow_self p n.ne_zero))
  exact { toIntermediateField := F }

/-- **The residue degree of a finite abstract field is the degree of its
selected residue subfield** ([Yamaguchi 2026,
`LocalClassFieldTheory/Finite/LocalReciprocity/FiniteSubgroupResidueDegree.lean:327`]
[Yamaguchi2026]). -/
theorem localResidueDatum_residueDegree_eq_selectedResidueFinrank
    (H : FiniteAbstractField (Field.absoluteGaloisGroup K)) :
    (H.residueDegree (localResidueDatum K) : ℕ) =
      Module.finrank
        (decompositionResidueField K (localAbsoluteValuationSubring K))
        (localAbstractFixedResidueIntermediateField K H.field) := by
  let A := localAbsoluteValuationSubring K
  let k := decompositionResidueField K A
  let Omega := selectedResidueField A
  let rho := (localResidueAlgAction K).toMonoidHom
  let R := localAbstractFixedResidueIntermediateField K H.field
  letI : Algebra k R := R.algebra
  letI : Module k R := Algebra.toModule
  letI : FiniteDimensional k R :=
    localAbstractFixedResidueIntermediateField_finiteDimensional K H.field
  let F := localAbstractFixedResidueFiniteGaloisIntermediateField K H.field
  let HR := H.toFiniteResidueAbstractField (localResidueDatum K)
  letI : Finite ((localResidueDatum K).residueQuotient H.field) :=
    HR.finiteResidueQuotient
  have himage : H.field.toSubgroup.map rho =
      F.toIntermediateField.fixingSubgroup := by
    change H.field.toSubgroup.map
        (localResidueAlgAction K).toMonoidHom =
      (localAbstractFixedResidueIntermediateField K H.field).fixingSubgroup
    exact localAbstractFixedResidueAction_map_eq_fixingSubgroup K H.field
  have hindex :
      ((localResidueDatum K).fieldImage HR.field).index =
        Module.finrank k R := by
    rw [(localResidueDatum K).fieldImage_eq_map]
    change
      (H.field.toSubgroup.map
        ((residueAbsoluteDegreeIn k Omega).toMonoidHom.comp rho)).index =
          Module.finrank k R
    exact residueDegreeImage_index_eq_finrank_of_map_eq_fixingSubgroup
      k Omega rho H.field.toSubgroup F himage
  letI : ((localResidueDatum K).fieldImage HR.field).IsFiniteRelIndex
      (⊤ : Subgroup ProfiniteIntegerMul) :=
    ⟨by
      rw [Subgroup.relIndex_top_right, hindex]
      exact Module.finrank_pos.ne'⟩
  apply Nat.cast_injective (R := Cardinal)
  change ((H.residueDegree (localResidueDatum K) : ℕ) : Cardinal) =
    (Module.finrank k R : Cardinal)
  rw [show H.residueDegree (localResidueDatum K) = HR.residueDegree from rfl,
    ← HR.residueDegreeCardinal_eq_coe,
    DegreeData.residueDegreeCardinal,
    relativeIndexCardinal_eq_index_of_finite
      (show (localResidueDatum K).fieldImage HR.field ≤
        (⊤ : Subgroup ProfiniteIntegerMul) from le_top)]
  norm_cast
  simpa only [Subgroup.relIndex_top_right] using hindex

end

end Atlas.Knowledge
