import Mathlib
import Atlas.Knowledge.IntegralClosureDVR

/-!
# monogenic integral closure

The ring of integers of a finite extension of a mixed-characteristic local field—the integral
closure of `𝒪[K]` in `L`, the discrete valuation ring of
`Atlas.Knowledge.IntegralClosureDVR`—is generated by a single element as an `𝒪[K]`-algebra.
This file proves that monogenicity. The uniformizer criterion its adjustment step turns
on—an element of the maximal ideal outside the square of the maximal ideal is irreducible—is
scaffolding inside the file's namespace.

## Main statements

* `monogenicIntegralClosure` — the integral closure of `𝒪[K]` in a finite extension `L` is
  generated by one element as an `𝒪[K]`-algebra.
* `MonogenicIntegralClosure.exists_mem_adjoin_sub_mem_pow` — the `π`-adic approximation
  step, public for the totally ramified sharpening to consume.
* `MonogenicIntegralClosure.faithfulSMul_integralClosure` — the faithful action of the
  base integers on the closure, the shared scaffolding its consumers rebuilt inline.

## Implementation notes

The proof is Serre's. `Polynomial.binomExpansion` is the source's Taylor formula
`R (x + h) = R (x) + h R' (x) + h² b` for the uniformizer adjustment: a lift `x₀` of a
primitive element of the residue extension sends its lifted minimal polynomial `g` into the
maximal ideal, and if `g (x₀)` falls into the square, expanding `g (x₀ + ϖ)` moves it out
because the derivative value `g' (x₀)` is a unit. The Nakayama close of the `π`-adic
approximation, at the finite stage where `𝓂[K]` generates a power of the maximal ideal
upstairs, is the source's Lemma 3 reduction modulo `pB`—neither argument uses completeness,
and module-finiteness of the closure over `𝒪[K]` is what runs it here. The one hypothesis of
the source's Prop. 12 discharged rather than assumed is separability of the residue
extension: the residue fields are finite, so the primitive element exists outright and the
derivative-unit step has its separability for free.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
-/

open ValuativeRel

namespace Atlas.Knowledge

namespace MonogenicIntegralClosure

/-- In a discrete valuation ring, an element of the maximal ideal that is not in the square of
the maximal ideal is irreducible: it is a uniformizer times a unit
([Serre 1979, Chap. I, §1, p.5][Serre1979]). -/
theorem irreducible_of_mem_maximalIdeal_of_notMem_sq {R : Type*} [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] {y : R} (h1 : y ∈ IsLocalRing.maximalIdeal R)
    (h2 : y ∉ IsLocalRing.maximalIdeal R ^ 2) : Irreducible y := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible R
  rw [hϖ.maximalIdeal_eq, Ideal.mem_span_singleton] at h1
  obtain ⟨z, hz⟩ := h1
  have hzu : IsUnit z := by
    by_contra hzn
    have hzm : z ∈ IsLocalRing.maximalIdeal R :=
      (IsLocalRing.mem_maximalIdeal z).mpr (mem_nonunits_iff.mpr hzn)
    rw [hϖ.maximalIdeal_eq, Ideal.mem_span_singleton] at hzm
    obtain ⟨w, hw⟩ := hzm
    refine h2 ?_
    rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact ⟨w, by rw [hz, hw]; ring⟩
  have hassoc : Associated ϖ y := by
    rw [hz]
    exact (associated_mul_unit_left ϖ z hzu).symm
  exact hassoc.irreducible hϖ

variable {A R : Type*} [CommRing A] [IsLocalRing A] [CommRing R] [Algebra A R]
  [IsLocalHom (algebraMap A R)]

/- The value of a lift of the residue minimal polynomial at a lift of its root falls in the
maximal ideal: the residue of the value is the minimal polynomial at its own root. -/
private theorem aeval_mem_maximalIdeal [IsLocalRing R] {g : Polynomial A} {z : R}
    (hg : g.map (IsLocalRing.residue A) =
      minpoly (IsLocalRing.ResidueField A) (IsLocalRing.residue R z)) :
    Polynomial.aeval z g ∈ IsLocalRing.maximalIdeal R := by
  rw [← IsLocalRing.residue_eq_zero_iff,
    Polynomial.map_aeval_eq_aeval_map (φ := IsLocalRing.residue A)
      (ψ := IsLocalRing.residue R) rfl, hg]
  exact minpoly.aeval _ _

/- The derivative value at the lift is a unit: separability keeps the residue of the
derivative value away from zero, and the nonunits of a local ring are the maximal ideal. -/
private theorem isUnit_aeval_derivative [IsLocalRing R] {g : Polynomial A} {z : R}
    (hg : g.map (IsLocalRing.residue A) =
      minpoly (IsLocalRing.ResidueField A) (IsLocalRing.residue R z))
    (hsep : IsSeparable (IsLocalRing.ResidueField A) (IsLocalRing.residue R z)) :
    IsUnit (Polynomial.aeval z (Polynomial.derivative g)) := by
  refine (IsLocalRing.residue_ne_zero_iff_isUnit _).mp ?_
  rw [Polynomial.map_aeval_eq_aeval_map (φ := IsLocalRing.residue A)
      (ψ := IsLocalRing.residue R) rfl, ← Polynomial.derivative_map, hg]
  exact hsep.aeval_derivative_ne_zero (minpoly.aeval _ _)

/- The adjustment step: some lift of the residue primitive element takes the lifted minimal
polynomial to a value outside the square of the maximal ideal, hence to an irreducible value.
If the first lift `x₀` fails, `Polynomial.binomExpansion` writes `g (x₀ + ϖ)` as
`g (x₀) + g' (x₀) ϖ + k ϖ ^ 2` with `g' (x₀)` a unit, and a unit multiple of `ϖ` escapes
the square. -/
private theorem exists_lift_aeval_irreducible [IsDomain R] [IsDiscreteValuationRing R]
    {g : Polynomial A} {x₀ : R}
    (hg : g.map (IsLocalRing.residue A) =
      minpoly (IsLocalRing.ResidueField A) (IsLocalRing.residue R x₀))
    (hsep : IsSeparable (IsLocalRing.ResidueField A) (IsLocalRing.residue R x₀)) :
    ∃ x : R, IsLocalRing.residue R x = IsLocalRing.residue R x₀ ∧
      Irreducible (Polynomial.aeval x g) := by
  by_cases hsq : Polynomial.aeval x₀ g ∈ IsLocalRing.maximalIdeal R ^ 2
  · obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible R
    have hϖm : ϖ ∈ IsLocalRing.maximalIdeal R :=
      hϖ.maximalIdeal_eq ▸ Ideal.mem_span_singleton_self ϖ
    have hunit : IsUnit (Polynomial.aeval x₀ (Polynomial.derivative g)) :=
      isUnit_aeval_derivative hg hsep
    have hres : IsLocalRing.residue R (x₀ + ϖ) = IsLocalRing.residue R x₀ := by
      rw [map_add, (IsLocalRing.residue_eq_zero_iff ϖ).mpr hϖm, add_zero]
    rw [← hres] at hg
    refine ⟨x₀ + ϖ, hres, irreducible_of_mem_maximalIdeal_of_notMem_sq
      (aeval_mem_maximalIdeal hg) fun hmem => ?_⟩
    obtain ⟨k, hk⟩ := Polynomial.binomExpansion (g.map (algebraMap A R)) x₀ ϖ
    simp only [Polynomial.derivative_map, Polynomial.eval_map_algebraMap] at hk
    -- hk : aeval (x₀ + ϖ) g = aeval x₀ g + aeval x₀ (derivative g) * ϖ + k * ϖ ^ 2
    have hd2 : Polynomial.aeval x₀ (Polynomial.derivative g) * ϖ ∈
        IsLocalRing.maximalIdeal R ^ 2 := by
      have heq : Polynomial.aeval x₀ (Polynomial.derivative g) * ϖ =
          Polynomial.aeval (x₀ + ϖ) g - Polynomial.aeval x₀ g - k * ϖ ^ 2 := by
        rw [hk]; ring
      rw [heq]
      exact sub_mem (sub_mem hmem hsq) (Ideal.mul_mem_left _ k (Ideal.pow_mem_pow hϖm 2))
    obtain ⟨v, hv⟩ := hunit
    have hvϖ : (v : R) * ϖ ∈ IsLocalRing.maximalIdeal R ^ 2 := by rw [hv]; exact hd2
    have hϖ2 : ϖ ∈ IsLocalRing.maximalIdeal R ^ 2 := by
      have h2 := Ideal.mul_mem_left _ ((v⁻¹ : Rˣ) : R) hvϖ
      rwa [Units.inv_mul_cancel_left] at h2
    rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hϖ2
    obtain ⟨c, hc⟩ := hϖ2
    have h1 : ϖ * (ϖ * c) = ϖ * 1 := by linear_combination -hc
    exact hϖ.not_isUnit (IsUnit.of_mul_eq_one c (mul_left_cancel₀ hϖ.ne_zero h1))
  · exact ⟨x₀, rfl, irreducible_of_mem_maximalIdeal_of_notMem_sq
      (aeval_mem_maximalIdeal hg) hsq⟩

/-- The `π`-adic approximation: when the residue field is generated over the base residue
field by the residue of `x` and the irreducible `π` lies in the subalgebra adjoining `x`,
every element of `R` is within `𝔪 ^ n` of that subalgebra for every `n`—each digit of a
`π`-adic expansion is corrected inside it
([Serre 1979, Chap. III, §6, Prop. 12, p.57][Serre1979] — the approximation half of its
proof). -/
theorem exists_mem_adjoin_sub_mem_pow [IsDomain R] [IsDiscreteValuationRing R]
    {x π : R}
    (hres : Algebra.adjoin (IsLocalRing.ResidueField A) {IsLocalRing.residue R x} = ⊤)
    (hπ : Irreducible π) (hπmem : π ∈ Algebra.adjoin A {x}) (z : R) (n : ℕ) :
    ∃ y ∈ Algebra.adjoin A {x}, z - y ∈ IsLocalRing.maximalIdeal R ^ n := by
  have key : ∀ c : R, ∃ w ∈ Algebra.adjoin A {x}, c - w ∈ IsLocalRing.maximalIdeal R := by
    intro c
    have hc : IsLocalRing.residue R c ∈
        Algebra.adjoin (IsLocalRing.ResidueField A) {IsLocalRing.residue R x} := by
      rw [hres]; exact Algebra.mem_top
    obtain ⟨pbar, hpbar⟩ := Algebra.adjoin_mem_exists_aeval _ _ hc
    obtain ⟨p, hp⟩ := Polynomial.map_surjective _ IsLocalRing.residue_surjective pbar
    refine ⟨Polynomial.aeval x p, Polynomial.aeval_mem_adjoin_singleton _ _, ?_⟩
    rw [← IsLocalRing.residue_eq_zero_iff, map_sub,
      Polynomial.map_aeval_eq_aeval_map (φ := IsLocalRing.residue A)
        (ψ := IsLocalRing.residue R) rfl, hp, hpbar, sub_self]
  induction n generalizing z with
  | zero => exact ⟨0, Subalgebra.zero_mem _, by simp⟩
  | succ n ih =>
    obtain ⟨y, hy, hzy⟩ := ih z
    rw [hπ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hzy
    obtain ⟨c, hc⟩ := hzy
    obtain ⟨w, hw, hcw⟩ := key c
    rw [hπ.maximalIdeal_eq, Ideal.mem_span_singleton] at hcw
    obtain ⟨d, hd⟩ := hcw
    refine ⟨y + π ^ n * w, add_mem hy (mul_mem (pow_mem hπmem n) hw), ?_⟩
    rw [hπ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact ⟨d, by linear_combination hc + π ^ n * hd⟩

end MonogenicIntegralClosure

variable (K : Type*) [Field K] [ValuativeRel K] (L : Type*) [Field L] [Algebra K L]
  [Algebra.IsAlgebraic K L]

omit [Algebra.IsAlgebraic K L] in
/-- The base integers act faithfully on the integral closure: the structure map factors
through the injective inclusions into the fraction fields — the shared scaffolding of the
closure carrier, named here beside its first consumer. -/
theorem MonogenicIntegralClosure.faithfulSMul_integralClosure :
    FaithfulSMul 𝒪[K] (integralClosure 𝒪[K] L) :=
  (faithfulSMul_iff_algebraMap_injective 𝒪[K] (integralClosure 𝒪[K] L)).mpr fun a b hab => by
    have h := congrArg (algebraMap (integralClosure 𝒪[K] L) L) hab
    rw [← IsScalarTower.algebraMap_apply 𝒪[K] (integralClosure 𝒪[K] L) L,
      ← IsScalarTower.algebraMap_apply 𝒪[K] (integralClosure 𝒪[K] L) L,
      IsScalarTower.algebraMap_apply 𝒪[K] K L, IsScalarTower.algebraMap_apply 𝒪[K] K L] at h
    exact IsFractionRing.injective 𝒪[K] K ((algebraMap K L).injective h)

/-- The ring of integers of a finite extension of a mixed-characteristic local field is
generated by a single element over the base ring of integers
([Serre 1979, Chap. III, §6, Prop. 12, p.57][Serre1979]). -/
theorem monogenicIntegralClosure [TopologicalSpace K] [IsMixedCharLocalField K]
    [FiniteDimensional K L] :
    ∃ x : integralClosure 𝒪[K] L, Algebra.adjoin 𝒪[K] {x} = ⊤ := by
  haveI := MonogenicIntegralClosure.faithfulSMul_integralClosure K L
  haveI : IsLocalHom (algebraMap 𝒪[K] (integralClosure 𝒪[K] L)) :=
    Algebra.IsIntegral.isLocalHom 𝒪[K] (integralClosure 𝒪[K] L)
  haveI : Module.Finite 𝒪[K] (integralClosure 𝒪[K] L) :=
    IsIntegralClosure.finite 𝒪[K] K L (integralClosure 𝒪[K] L)
  haveI : Finite (IsLocalRing.ResidueField (integralClosure 𝒪[K] L)) :=
    IsLocalRing.ResidueField.finite_of_finite (inferInstance : Finite 𝓀[K])
  -- a primitive element of the finite residue extension, as a generator of the subalgebra
  obtain ⟨xbar, hxbar⟩ := Field.exists_primitive_element_of_finite_bot 𝓀[K]
    (IsLocalRing.ResidueField (integralClosure 𝒪[K] L))
  have hadj : Algebra.adjoin 𝓀[K] {xbar} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (IsAlgebraic.of_finite _ _), hxbar, IntermediateField.top_toSubalgebra]
  obtain ⟨g, hgmap⟩ := Polynomial.map_surjective _ IsLocalRing.residue_surjective
    (minpoly 𝓀[K] xbar)
  obtain ⟨x₀, hx₀⟩ := IsLocalRing.residue_surjective xbar
  rw [← hx₀] at hgmap hadj
  have hsep : IsSeparable 𝓀[K] (IsLocalRing.residue (integralClosure 𝒪[K] L) x₀) :=
    Algebra.IsSeparable.isSeparable _ _
  obtain ⟨x, hxres, hπ⟩ := MonogenicIntegralClosure.exists_lift_aeval_irreducible hgmap hsep
  rw [← hxres] at hadj
  -- the maximal ideal of the base generates a power of the maximal ideal upstairs
  have hmapbot : Ideal.map (algebraMap 𝒪[K] (integralClosure 𝒪[K] L)) 𝓂[K] ≠ ⊥ := fun h =>
    IsDiscreteValuationRing.not_a_field 𝒪[K]
      ((Ideal.map_eq_bot_iff_of_injective
        (FaithfulSMul.algebraMap_injective 𝒪[K] (integralClosure 𝒪[K] L))).mp h)
  obtain ⟨m, hm⟩ := IsDiscreteValuationRing.ideal_eq_span_pow_irreducible hmapbot hπ
  have hmm : Ideal.map (algebraMap 𝒪[K] (integralClosure 𝒪[K] L)) 𝓂[K] =
      IsLocalRing.maximalIdeal (integralClosure 𝒪[K] L) ^ m := by
    rw [hm, hπ.maximalIdeal_eq, Ideal.span_singleton_pow]
  refine ⟨x, Algebra.toSubmodule_eq_top.mp (top_le_iff.mp ?_)⟩
  refine Submodule.le_of_le_smul_of_le_jacobson_bot (Module.finite_def.mp inferInstance)
    (IsLocalRing.maximalIdeal_le_jacobson ⊥) ?_
  intro z _
  obtain ⟨y, hy, hzy⟩ := MonogenicIntegralClosure.exists_mem_adjoin_sub_mem_pow hadj hπ
    (Polynomial.aeval_mem_adjoin_singleton _ _) z m
  rw [Ideal.smul_top_eq_map]
  refine Submodule.mem_sup.mpr
    ⟨y, (Subalgebra.mem_toSubmodule _).mpr hy, z - y, ?_, by ring⟩
  rw [Submodule.restrictScalars_mem, hmm]
  exact hzy

end Atlas.Knowledge
