import Mathlib
import Atlas.Knowledge.PadicIntegerEquiv
import Atlas.Knowledge.PadicExpIsomorphism
import Atlas.Knowledge.CycloField
import Atlas.Knowledge.CyclotomicIntegerBasis
import Atlas.Knowledge.NormIndexAbelian
import Atlas.Knowledge.StandardLubinTateSubgroupIndex
import Atlas.Knowledge.IntegerHigherUnitCount
import Atlas.Knowledge.NormQuotient
import Atlas.Knowledge.RationalIntegerValuation

/-!
# p-adic cyclotomic floor norm subgroup

The norm subgroup of the `p ^ n`-th cyclotomic floor over `ℚ_[p]`: the norms from
`ℚ_[p](ζ_{p^n})` are exactly the elements `u * p ^ m` with `u ≡ 1 mod p ^ n`, Milne's
description of the kernel of the local Artin map on `ℚ_p[ζ_{p^r}]`, in the layer's
spelling `⟨p⟩ ⊔ U^(n)`. This is the ramified half of the local Kronecker–Weber theorem:
together with the unramified floors of `Atlas.Knowledge.CycloFieldOfDegree` it realizes
every standard open subgroup of `Atlas.Knowledge.StandardOpenSubgroups` as the norm subgroup
of a cyclotomic field, which is what `Atlas.Knowledge.LocalKroneckerWeber` consumes.
Everything here is proved.

## Main statements

* `padicCycloFieldNormSubgroup` — `N(ℚ_[p](ζ_{p^n})ˣ) = ⟨p⟩ ⊔ U^(n)`; proved.
* `PadicCycloFieldNormSubgroup.cyclotomic_irreducible` — `cyclotomic (p ^ n) ℚ_[p]` is
  irreducible; proved.
* `PadicCycloFieldNormSubgroup.cycloField_isCyclotomicExtension` — the cyclotomic floor of
  `Atlas.Knowledge.CycloField` is a cyclotomic extension in Mathlib's sense; proved.

## Implementation notes

The equality is an index squeeze, as `Atlas.Knowledge.StandardLubinTateNormSubgroup` is: the
standard subgroup has index `(p - 1) * p ^ (n - 1)` by
`Atlas.Knowledge.standardLubinTateSubgroupIndex`, the norm subgroup has index the degree by
`Atlas.Knowledge.normIndexAbelian`, the degree is `(p ^ n).totient` because the cyclotomic
polynomial is irreducible over `ℚ_[p]` — Eisenstein after the shift `X ↦ X + 1`, the leg
`Atlas.Knowledge.CyclotomicIntegerBasis` already carries — and one containment suffices. The
containment is the source's argument
(`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean`): `p` is the norm of `1 - ζ` by
Mathlib's `IsPrimitiveRoot.sub_one_norm_isPrimePow`, and a principal unit of depth `n` is a
`(p ^ n).totient`-th power of a principal unit, hence the norm of a base element, because the
exponential of `Atlas.Knowledge.PadicExpIsomorphism` turns the ideal `p ^ (n - 1) • 𝓂` into `U^(n)`
and division by the unit `p - 1` is free. That argument needs the exponential to converge on `𝓂`,
which for `p = 2` it does not: there it reaches only `U^(n + 1)`, of index `2` in `U^(n)`, and the
missing coset is supplied by the norm of `2 + i` from the subfield `ℚ_[2](i)`, which is
`5 ^ 2 ^ (n - 2)`, a unit of depth exactly `n`. The source handles `p = 2` by an explicit
square-class analysis of `U^(2)` over seven hundred lines; the coset argument here replaces it. The
degenerate floor `p ^ n = 2` is `ℚ_[2]` itself, where both sides are the whole group and the index
squeeze says so. Milne states the result as the kernel of the Artin map; the norm subgroup is that
kernel by `Atlas.Knowledge.AbsoluteLocalArtinNormKernel`, but the proof here goes through the index
count and never mentions the map. The field is the cyclotomic floor of `Atlas.Knowledge.CycloField`
inside `AlgebraicClosure ℚ_[p]` rather than the source's abstract field generated by a primitive
root, because that is where the order reversal `Atlas.Knowledge.FiniteAbelianSubfieldOrder` reads
it; the coset argument at `p = 2` and the transport of the exponential are Atlas's own and cite no
source.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

open ValuativeRel Polynomial
open scoped IntermediateField

namespace Atlas.Knowledge

namespace PadicCycloFieldNormSubgroup

section CycloField

variable (K : Type*) [Field K] [CharZero K]

/-- The cyclotomic floor of `Atlas.Knowledge.CycloField` is a cyclotomic extension in Mathlib's
sense: it contains a primitive root of unity and is generated by the roots of unity. -/
instance cycloField_isCyclotomicExtension (m : ℕ) [NeZero m] :
    IsCyclotomicExtension {m} K (cycloField K m) := by
  refine ⟨fun {n} hn hn0 => ?_, fun x => ?_⟩
  · rw [Set.mem_singleton_iff] at hn
    subst hn
    haveI := IsSepClosedOfCharZero.isCyclotomicExtension (AlgebraicClosure K) {n}
    obtain ⟨ζ, hζ⟩ := IsCyclotomicExtension.exists_isPrimitiveRoot (AlgebraicClosure K)
      (AlgebraicClosure K) (S := {n}) rfl hn0
    exact ⟨⟨ζ, mem_cycloField K hn0 hζ.pow_eq_one⟩,
      IsPrimitiveRoot.coe_submonoidClass_iff.mp hζ⟩
  · have h := Polynomial.IsSplittingField.adjoin_rootSet (cycloField K m) (X ^ m - 1 : K[X])
    have hset : (X ^ m - 1 : K[X]).rootSet (cycloField K m) =
        {b | ∃ n ∈ ({m} : Set ℕ), n ≠ 0 ∧ b ^ n = 1} := by
      have hne : (X ^ m - 1 : K[X]) ≠ 0 := by
        simpa using X_pow_sub_C_ne_zero (NeZero.pos m) (1 : K)
      ext b
      simp [Polynomial.mem_rootSet, sub_eq_zero, hne, NeZero.ne m]
    rw [← hset, h]
    exact Algebra.mem_top

end CycloField

variable (p : ℕ) [hp : Fact p.Prime]

/-- The prime `p` as a unit of `ℚ_[p]`. -/
noncomputable def padicPrimeUnit : ℚ_[p]ˣ :=
  Units.mk0 (p : ℚ_[p]) (Nat.cast_ne_zero.mpr hp.out.ne_zero)

/-- The prime unit is the Lubin–Tate uniformizer unit of the irreducible `p`. -/
theorem padicPrimeUnit_eq :
    padicPrimeUnit p =
      standardLubinTateUniformizerUnit ℚ_[p] (PadicIntegerEquiv.irreducible_natCast p) :=
  Units.ext (by simp [padicPrimeUnit, standardLubinTateUniformizerUnit])

/-- The `p`-power cyclotomic polynomial is irreducible over `ℚ_[p]`: Eisenstein after the
shift `X ↦ X + 1` ([Serre 1979, Chap. IV, §4, proof of Prop. 17, p.78][Serre1979]). -/
theorem cyclotomic_irreducible (n : ℕ) (hn : n ≠ 0) :
    Irreducible (cyclotomic (p ^ n) ℚ_[p]) := by
  haveI := IsSepClosedOfCharZero.isCyclotomicExtension (AlgebraicClosure ℚ_[p]) {p ^ n}
  obtain ⟨ζ, hζ⟩ := IsCyclotomicExtension.exists_isPrimitiveRoot (AlgebraicClosure ℚ_[p])
    (AlgebraicClosure ℚ_[p]) (S := {p ^ n}) rfl (pow_ne_zero n hp.out.ne_zero)
  rw [← CyclotomicIntegerBasis.minpoly_eq_cyclotomic hζ hn]
  exact minpoly.irreducible ((PadicAlgCl.isAlgebraic p).isAlgebraic ζ).isIntegral

/-- The `p ^ n`-th cyclotomic floor over `ℚ_[p]` has degree `(p ^ n).totient`
([Serre 1979, Chap. IV, §4, Prop. 17 (i), p.78][Serre1979];
[Milne 2020, Chap. I, §3, Ex. 3.13 (b), p.44][MilneCFT]). -/
theorem finrank_cycloField (n : ℕ) (hn : n ≠ 0) :
    Module.finrank ℚ_[p] (cycloField ℚ_[p] (p ^ n)) = (p ^ n).totient := by
  haveI : NeZero (p ^ n) := ⟨pow_ne_zero n hp.out.ne_zero⟩
  exact IsCyclotomicExtension.finrank (cycloField ℚ_[p] (p ^ n)) (cyclotomic_irreducible p n hn)

/-- `p` is a norm from the `p ^ n`-th cyclotomic floor: it is the norm of `1 - ζ`, the constant
term of the Eisenstein polynomial of `ζ - 1`
([Serre 1979, Chap. IV, §4, proof of Prop. 17, p.78][Serre1979]; Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:85`). -/
theorem padicPrimeUnit_mem (n : ℕ) (hn : n ≠ 0) (h2 : p ^ n ≠ 2) :
    padicPrimeUnit p ∈ localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ n)) := by
  haveI : NeZero (p ^ n) := ⟨pow_ne_zero n hp.out.ne_zero⟩
  obtain ⟨ζ, hζ⟩ := IsCyclotomicExtension.exists_isPrimitiveRoot ℚ_[p]
    (cycloField ℚ_[p] (p ^ n)) (S := {p ^ n}) rfl (pow_ne_zero n hp.out.ne_zero)
  have hnorm : Algebra.norm ℚ_[p] (ζ - 1) = ((p ^ n).minFac : ℚ_[p]) :=
    hζ.sub_one_norm_isPrimePow (hp.out.prime.isPrimePow.pow hn) (cyclotomic_irreducible p n hn)
      h2
  rw [Nat.Prime.pow_minFac hp.out hn] at hnorm
  have h1 : 1 < p ^ n := Nat.one_lt_pow hn hp.out.one_lt
  have hne : ζ - 1 ≠ 0 := sub_ne_zero.mpr (hζ.ne_one h1)
  refine ⟨Units.mk0 (ζ - 1) hne, Units.ext ?_⟩
  simpa [normUnits, padicPrimeUnit] using hnorm

section Exp

/-- The exponential turns natural multiples into powers on its convergence ideal. -/
theorem exp_nsmul (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsMixedCharLocalField K] (x : 𝒪[K])
    (hx : x ∈ (𝓂[K] ^ (absoluteRamificationIndex K / (residueCharacteristic K - 1) + 1) :
      Ideal 𝒪[K])) (k : ℕ) :
    NormedSpace.exp ((k • x : 𝒪[K]) : K) = NormedSpace.exp (x : K) ^ k := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [succ_nsmul, Subring.coe_add, PadicExpIsomorphism.exp_add K _ _ (nsmul_mem hx k) hx, ih,
      pow_succ]

/-- A principal unit of depth `n + 1 / (p - 1)` is a `(p ^ n).totient`-th power in `ℚ_[p]`:
the exponential carries `p ^ (n - 1) • 𝓂 ^ (1 + 1 / (p - 1))` onto the unit level, and the
unit `p - 1` divides freely (Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:30`). -/
theorem exists_pow_totient_eq (n : ℕ) (hn : n ≠ 0) (i : ℕ+) (hi : (i : ℕ) = n + 1 / (p - 1))
    (u : ℚ_[p]ˣ) (hu : u ∈ higherUnitGroup ℚ_[p] i) :
    ∃ r : ℚ_[p]ˣ, r ^ (p ^ n).totient = u := by
  set c : ℕ := 1 / (p - 1) with hc
  have hi' : (i : ℕ) = n + c := hi
  have hthr : absoluteRamificationIndex ℚ_[p] / (residueCharacteristic ℚ_[p] - 1) + 1 = c + 1 := by
    rw [PadicIntegerEquiv.absoluteRamificationIndex_eq, PadicIntegerEquiv.residueCharacteristic_eq]
  have hi : absoluteRamificationIndex ℚ_[p] < (residueCharacteristic ℚ_[p] - 1) * i := by
    rw [PadicIntegerEquiv.absoluteRamificationIndex_eq, PadicIntegerEquiv.residueCharacteristic_eq,
      hi']
    have h2 := hp.out.two_le
    rcases Nat.lt_or_ge 2 p with h3 | h3
    · exact lt_of_lt_of_le (by omega : 1 < p - 1)
        (Nat.le_mul_of_pos_right _ (Nat.add_pos_left (Nat.pos_of_ne_zero hn) _))
    · have hp2 : p = 2 := by omega
      subst hp2
      simp [hc]
      omega
  -- the exponential bijection at level `n + c`
  have hbij := padicExpIsomorphism ℚ_[p] i hi
  obtain ⟨x, hx, hxu⟩ := hbij.surjOn ⟨u, hu, rfl⟩
  obtain ⟨x, hxmem, rfl⟩ := hx
  -- `x = p ^ (n - 1) * z` with `z` on the convergence ideal
  have hxmem' : x ∈ Ideal.span {(p : 𝒪[ℚ_[p]]) ^ (n + c)} := by
    rwa [PadicIntegerEquiv.maximalIdeal_eq, Ideal.span_singleton_pow, hi'] at hxmem
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton.mp hxmem'
  -- `p - 1` is a unit of the integers
  have hunit : IsUnit ((p - 1 : ℕ) : 𝒪[ℚ_[p]]) := by
    rw [isUnit_natCast_iff, PadicIntegerEquiv.residueCharacteristic_eq]
    have := hp.out.two_le
    exact fun h => absurd (Nat.le_of_dvd (by omega) h) (by omega)
  set z : 𝒪[ℚ_[p]] := hunit.unit⁻¹ * ((p : 𝒪[ℚ_[p]]) ^ (c + 1) * a) with hz
  have hzmem : z ∈ (𝓂[ℚ_[p]] ^ (c + 1) : Ideal 𝒪[ℚ_[p]]) := by
    rw [PadicIntegerEquiv.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact Dvd.intro_left ((hunit.unit⁻¹ : 𝒪[ℚ_[p]]ˣ) * a) (by rw [hz]; ring)
  have hsmul : ((p ^ n).totient • z : 𝒪[ℚ_[p]]) = x := by
    rw [Nat.totient_prime_pow hp.out (Nat.pos_of_ne_zero hn), ha, nsmul_eq_mul, hz]
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
    have hcancel : ((p - 1 : ℕ) : 𝒪[ℚ_[p]]) * (hunit.unit⁻¹ : 𝒪[ℚ_[p]]ˣ) = 1 := by
      have := Units.mul_inv hunit.unit
      rwa [hunit.unit_spec] at this
    rw [Nat.cast_mul, Nat.cast_pow]
    calc ((p : 𝒪[ℚ_[p]]) ^ (m + 1 - 1) * ((p - 1 : ℕ) : 𝒪[ℚ_[p]])) *
          ((hunit.unit⁻¹ : 𝒪[ℚ_[p]]ˣ) * ((p : 𝒪[ℚ_[p]]) ^ (c + 1) * a))
        = (((p - 1 : ℕ) : 𝒪[ℚ_[p]]) * (hunit.unit⁻¹ : 𝒪[ℚ_[p]]ˣ)) *
            ((p : 𝒪[ℚ_[p]]) ^ m * ((p : 𝒪[ℚ_[p]]) ^ (c + 1) * a)) := by
          simp only [Nat.add_sub_cancel]; ring
      _ = (p : 𝒪[ℚ_[p]]) ^ (m + 1 + c) * a := by rw [hcancel, one_mul]; ring
  -- `exp z` is a unit of the level `c + 1`
  have hzmem' : z ∈ (𝓂[ℚ_[p]] ^ (absoluteRamificationIndex ℚ_[p] /
      (residueCharacteristic ℚ_[p] - 1) + 1) : Ideal 𝒪[ℚ_[p]]) := by rwa [hthr]
  have hi1 : absoluteRamificationIndex ℚ_[p] < (residueCharacteristic ℚ_[p] - 1) * (c + 1) := by
    rw [PadicIntegerEquiv.absoluteRamificationIndex_eq, PadicIntegerEquiv.residueCharacteristic_eq]
    have h2 := hp.out.two_le
    rcases Nat.lt_or_ge 2 p with h3 | h3
    · exact lt_of_lt_of_le (by omega : 1 < p - 1) (Nat.le_mul_of_pos_right _ (Nat.succ_pos c))
    · have hp2 : p = 2 := by omega
      subst hp2
      simp [hc]
  obtain ⟨r, -, hr⟩ :=
    (padicExpIsomorphism ℚ_[p] ⟨c + 1, Nat.succ_pos c⟩ hi1).mapsTo ⟨z, hzmem, rfl⟩
  refine ⟨r, Units.ext ?_⟩
  rw [Units.val_pow_eq_pow_val, hr, ← exp_nsmul ℚ_[p] z hzmem', hsmul, hxu]

end Exp

/-- The principal units of depth `n + 1 / (p - 1)` are norms from the `p ^ n`-th cyclotomic
floor: each is a `(p ^ n).totient`-th power, and the `[L : K]`-th power of a base element is
its norm (Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:30`). -/
theorem higherUnitGroup_le_of_threshold (n : ℕ) (hn : n ≠ 0) (i : ℕ+)
    (hi : (i : ℕ) = n + 1 / (p - 1)) :
    higherUnitGroup ℚ_[p] i ≤ localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ n)) := by
  intro u hu
  obtain ⟨r, hr⟩ := exists_pow_totient_eq p n hn i hi u hu
  refine ⟨Units.map (algebraMap ℚ_[p] (cycloField ℚ_[p] (p ^ n))).toMonoidHom r, Units.ext ?_⟩
  rw [← hr]
  simp [normUnits, Algebra.norm_algebraMap, finrank_cycloField p n hn]

section Two

/-- The `2`-adic size of `5 ^ 2 ^ k - 1` is exactly `2 ^ (-(k + 2))`: squaring a unit of depth
`j ≥ 2` lands at depth exactly `j + 1`. -/
theorem norm_five_pow_sub_one (k : ℕ) :
    ‖(5 : ℚ_[2]) ^ 2 ^ k - 1‖ = (2 : ℝ) ^ (-((k : ℤ) + 2)) := by
  induction k with
  | zero =>
    have : (5 : ℚ_[2]) ^ 2 ^ 0 - 1 = (2 : ℚ_[2]) ^ 2 := by norm_num
    rw [this]
    have h := Padic.norm_p_pow (p := 2) 2
    push_cast at h
    rw [h]
    norm_num
  | succ k ih =>
    have hfac : (5 : ℚ_[2]) ^ 2 ^ (k + 1) - 1 =
        ((5 : ℚ_[2]) ^ 2 ^ k - 1) * (((5 : ℚ_[2]) ^ 2 ^ k - 1) + 2) := by
      rw [pow_succ, pow_mul]; ring
    have h2 : ‖(2 : ℚ_[2])‖ = (2 : ℝ)⁻¹ := by
      have := Padic.norm_p (p := 2)
      push_cast at this
      exact this
    have hlt : ‖(5 : ℚ_[2]) ^ 2 ^ k - 1‖ ≠ ‖(2 : ℚ_[2])‖ := by
      rw [ih, h2]
      have : (2 : ℝ) ^ (-((k : ℤ) + 2)) < (2 : ℝ)⁻¹ := by
        rw [← zpow_neg_one]
        exact zpow_lt_zpow_right₀ (by norm_num) (by omega)
      exact this.ne
    rw [hfac, norm_mul, Padic.add_eq_max_of_ne hlt, ih, h2]
    rw [max_eq_right (by
      rw [← zpow_neg_one]
      exact (zpow_lt_zpow_right₀ (by norm_num) (by omega)).le)]
    have hexp : -((k : ℤ) + 2) + -1 = -(((k + 1 : ℕ) : ℤ) + 2) := by push_cast; ring
    rw [← zpow_neg_one, ← zpow_add₀ (by norm_num), hexp]

/-- `2 + i` in the `2 ^ n`-th cyclotomic floor, `i` a primitive fourth root of unity, has norm
`5 ^ 2 ^ (n - 2)`: its norm from `ℚ_[2](i)` is `5`, and the floor has degree `2 ^ (n - 2)` over
that subfield. -/
theorem exists_norm_eq_five_pow (n : ℕ) (hn : 2 ≤ n) :
    ∃ x : cycloField ℚ_[2] (2 ^ n), Algebra.norm ℚ_[2] x = (5 : ℚ_[2]) ^ 2 ^ (n - 2) := by
  set F := cycloField ℚ_[2] (2 ^ n) with hF
  haveI : NeZero (2 ^ n) := ⟨pow_ne_zero n two_ne_zero⟩
  obtain ⟨ζ, hζ⟩ := IsCyclotomicExtension.exists_isPrimitiveRoot ℚ_[2] F (S := {2 ^ n}) rfl
    (pow_ne_zero n two_ne_zero)
  have hdvd : 2 ^ (n - 2) ∣ 2 ^ n := pow_dvd_pow 2 (by omega)
  have hi : IsPrimitiveRoot (ζ ^ 2 ^ (n - 2)) 4 := by
    have h := hζ.pow_of_dvd (pow_ne_zero _ two_ne_zero) hdvd
    rwa [Nat.pow_div (by omega) two_pos, show n - (n - 2) = 2 by omega] at h
  set i : F := ζ ^ 2 ^ (n - 2) with hi_def
  set g : F := i + algebraMap ℚ_[2] F 2 with hg
  refine ⟨g, ?_⟩
  have hirr4 : Irreducible (cyclotomic (2 ^ 2) ℚ_[2]) := cyclotomic_irreducible 2 2 two_ne_zero
  have hmin_i : minpoly ℚ_[2] i = X ^ 2 + Polynomial.C 1 := by
    rw [← hi.minpoly_eq_cyclotomic_of_irreducible (by simpa using hirr4),
      show (4 : ℕ) = 2 ^ (1 + 1) by norm_num, cyclotomic_prime_pow_eq_geom_sum Nat.prime_two]
    simp [Finset.sum_range_succ, add_comm]
  have hmin_g :
      minpoly ℚ_[2] g = (X ^ 2 + Polynomial.C 1 : ℚ_[2][X]).comp (X - Polynomial.C 2) := by
    rw [hg, minpoly.add_algebraMap, hmin_i]
  have hdeg : ((X ^ 2 + Polynomial.C 1 : ℚ_[2][X]).comp (X - Polynomial.C 2)).natDegree = 2 := by
    rw [natDegree_comp, natDegree_X_sub_C, natDegree_X_pow_add_C, mul_one]
  have hint : IsIntegral ℚ_[2] g := IsIntegral.of_finite ℚ_[2] g
  set pb := IntermediateField.adjoin.powerBasis hint with hpb
  have hnormE : Algebra.norm ℚ_[2] pb.gen = 5 := by
    rw [Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly, hpb,
      IntermediateField.adjoin.powerBasis_dim, IntermediateField.adjoin.powerBasis_gen,
      IntermediateField.minpoly_gen, hmin_g, hdeg, coeff_zero_eq_eval_zero, eval_comp]
    simp
    norm_num
  have hdimE : Module.finrank ℚ_[2] ℚ_[2]⟮g⟯ = 2 := by
    rw [pb.finrank, hpb, IntermediateField.adjoin.powerBasis_dim, hmin_g, hdeg]
  have hfinC : Module.finrank ℚ_[2] F = 2 ^ (n - 1) := by
    rw [hF, finrank_cycloField 2 n (by omega), Nat.totient_prime_pow Nat.prime_two (by omega)]
    simp
  have hdimEC : Module.finrank ℚ_[2]⟮g⟯ F = 2 ^ (n - 2) := by
    have h := Module.finrank_mul_finrank ℚ_[2] ℚ_[2]⟮g⟯ F
    rw [hdimE, hfinC, show 2 ^ (n - 1) = 2 * 2 ^ (n - 2) by
      rw [← pow_succ']; congr 1; omega] at h
    exact Nat.eq_of_mul_eq_mul_left two_pos h
  have hg' : g = algebraMap ℚ_[2]⟮g⟯ F pb.gen := by
    rw [hpb, IntermediateField.adjoin.powerBasis_gen]; rfl
  rw [hg', ← Algebra.norm_norm (S := ℚ_[2]⟮g⟯), Algebra.norm_algebraMap, map_pow, hnormE, hdimEC]

/-- `5` is a unit of the `2`-adic integers. -/
theorem five_isUnit : IsUnit (5 : 𝒪[ℚ_[2]]) := by
  have h := isUnit_natCast_iff (K := ℚ_[2]) 5
  rw [PadicIntegerEquiv.residueCharacteristic_eq, Nat.cast_ofNat] at h
  exact h.mpr (by decide)

/-- `5 ^ 2 ^ (n - 2)` is a principal unit of depth exactly `n`: it lies in `U^(n)` and not in
`U^(n + 1)`. -/
theorem five_pow_mem (n : ℕ) (hn : 2 ≤ n) :
    five_isUnit.unit ^ 2 ^ (n - 2) ∈ integerHigherUnitGroup ℚ_[2] n ∧
      five_isUnit.unit ^ 2 ^ (n - 2) ∉ integerHigherUnitGroup ℚ_[2] (n + 1) := by
  have hval : (((five_isUnit.unit ^ 2 ^ (n - 2) : 𝒪[ℚ_[2]]ˣ) : 𝒪[ℚ_[2]]) - 1 : 𝒪[ℚ_[2]]) =
      ⟨(5 : ℚ_[2]) ^ 2 ^ (n - 2) - 1, by
        rw [PadicIntegerEquiv.integer_eq, PadicInt.mem_subring_iff]
        rw [norm_five_pow_sub_one]
        exact zpow_le_one_of_nonpos₀ (by norm_num) (by omega)⟩ := by
    apply Subtype.ext
    simp [Units.val_pow_eq_pow_val]
    rfl
  have hnorm : ‖((((five_isUnit.unit ^ 2 ^ (n - 2) : 𝒪[ℚ_[2]]ˣ) : 𝒪[ℚ_[2]]) - 1 :
      𝒪[ℚ_[2]]) : ℚ_[2])‖ = (2 : ℝ) ^ (-(n : ℤ)) := by
    rw [hval]
    change ‖(5 : ℚ_[2]) ^ 2 ^ (n - 2) - 1‖ = _
    rw [norm_five_pow_sub_one]
    congr 1
    push_cast [Nat.cast_sub hn]
    ring
  constructor
  · change _ ∈ (𝓂[ℚ_[2]] ^ n : Ideal 𝒪[ℚ_[2]])
    rw [PadicIntegerEquiv.mem_maximalIdeal_pow_iff, hnorm]
    push_cast
    exact le_rfl
  · change ¬ _ ∈ (𝓂[ℚ_[2]] ^ (n + 1) : Ideal 𝒪[ℚ_[2]])
    rw [PadicIntegerEquiv.mem_maximalIdeal_pow_iff, hnorm, not_le]
    push_cast
    exact zpow_lt_zpow_right₀ (by norm_num) (by omega)

end Two

section RelIndex

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsMixedCharLocalField K]

/-- The integer unit levels are nested. -/
theorem integerHigherUnitGroup_succ_le (n : ℕ) :
    integerHigherUnitGroup K (n + 1) ≤ integerHigherUnitGroup K n :=
  fun _ hu => Ideal.pow_le_pow_right (Nat.le_succ n) hu

/-- Consecutive integer unit levels have relative index the residue cardinality: the quotient
`U^(n) / U^(n + 1)` is the additive group of the residue field
([Serre 1979, Chap. IV, §2, Prop. 6 (b), p.66][Serre1979]). -/
theorem integerHigherUnitGroup_relIndex (n : ℕ) (hn : n ≠ 0) :
    (integerHigherUnitGroup K (n + 1)).relIndex (integerHigherUnitGroup K n) = Nat.card 𝓀[K] := by
  have h := Subgroup.relIndex_mul_index (integerHigherUnitGroup_succ_le K n)
  change _ * Nat.card (𝒪[K]ˣ ⧸ integerHigherUnitGroup K n) =
    Nat.card (𝒪[K]ˣ ⧸ integerHigherUnitGroup K (n + 1)) at h
  rw [integerHigherUnitCount K n hn, integerHigherUnitCount K (n + 1) (Nat.succ_ne_zero n),
    Nat.add_sub_cancel] at h
  have hq : 1 < Nat.card 𝓀[K] := Finite.one_lt_card
  have hpos : 0 < (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ (n - 1) :=
    Nat.mul_pos (by omega) (Nat.pow_pos (by omega))
  refine Nat.eq_of_mul_eq_mul_right hpos ?_
  rw [h]
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  rw [Nat.add_sub_cancel]
  ring

end RelIndex

/-- For `p = 2` and `n ≥ 2`, the principal units of depth `n` are norms from the `2 ^ n`-th
cyclotomic floor: the exponential reaches the depth `n + 1`, and `5 ^ 2 ^ (n - 2)`, a norm of
depth exactly `n`, supplies the missing coset of index `2`
([Milne 2020, Chap. I, §3, Ex. 3.13, p.44][MilneCFT]; Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:817`). -/
theorem higherUnitGroup_le_two (n : ℕ) (hn : 2 ≤ n) :
    higherUnitGroup ℚ_[2] ⟨n, by omega⟩ ≤ localNormSubgroup ℚ_[2] (cycloField ℚ_[2] (2 ^ n)) := by
  set N := localNormSubgroup ℚ_[2] (cycloField ℚ_[2] (2 ^ n)) with hN
  set φ : 𝒪[ℚ_[2]]ˣ →* ℚ_[2]ˣ := Units.map (algebraMap 𝒪[ℚ_[2]] ℚ_[2]).toMonoidHom with hφ
  set A := integerHigherUnitGroup ℚ_[2] (n + 1) with hA
  set B := integerHigherUnitGroup ℚ_[2] n with hB
  set w := five_isUnit.unit ^ 2 ^ (n - 2) with hw
  have hAN : A.map φ ≤ N := by
    rw [hA, hφ, map_integerHigherUnitGroup_eq_higherUnitGroup ℚ_[2] (n + 1) (Nat.succ_ne_zero n)]
    exact higherUnitGroup_le_of_threshold 2 n (by omega) _ (by simp)
  have hwN : φ w ∈ N := by
    obtain ⟨x, hx⟩ := exists_norm_eq_five_pow n hn
    have hx0 : x ≠ 0 :=
      Algebra.norm_ne_zero_iff.mp (by rw [hx]; exact pow_ne_zero _ (by norm_num))
    refine ⟨Units.mk0 x hx0, Units.ext ?_⟩
    change Algebra.norm ℚ_[2] x =
      (algebraMap 𝒪[ℚ_[2]] ℚ_[2]) ((five_isUnit.unit ^ 2 ^ (n - 2) : 𝒪[ℚ_[2]]ˣ) : 𝒪[ℚ_[2]])
    rw [hx, Units.val_pow_eq_pow_val, five_isUnit.unit_spec, map_pow, map_ofNat]
  obtain ⟨hwB, hwA⟩ := five_pow_mem n hn
  have hrel := integerHigherUnitGroup_relIndex ℚ_[2] n (by omega)
  rw [PadicIntegerEquiv.card_residueField] at hrel
  set D := A ⊔ Subgroup.zpowers w with hD
  have hAD : A ≤ D := le_sup_left
  have hDB : D ≤ B := sup_le (integerHigherUnitGroup_succ_le ℚ_[2] n) (Subgroup.zpowers_le.mpr hwB)
  have hmul := Subgroup.relIndex_mul_relIndex A D B hAD hDB
  rw [hrel] at hmul
  have hne1 : A.relIndex D ≠ 1 := fun h =>
    hwA (Subgroup.relIndex_eq_one.mp h (Subgroup.mem_sup_right (Subgroup.mem_zpowers w)))
  have hD1 : D.relIndex B = 1 := by
    have hdvd : A.relIndex D ∣ 2 := Dvd.intro _ hmul
    rcases (Nat.dvd_prime Nat.prime_two).mp hdvd with h | h
    · exact absurd h hne1
    · rw [h] at hmul
      omega
  have hBD : B ≤ D := Subgroup.relIndex_eq_one.mp hD1
  have hDN : D.map φ ≤ N := by
    rw [hD, Subgroup.map_sup, MonoidHom.map_zpowers]
    exact sup_le hAN (Subgroup.zpowers_le.mpr hwN)
  intro u hu
  rw [higherUnitGroup_eq_map_integerHigherUnitGroup] at hu
  obtain ⟨u', hu', rfl⟩ := hu
  exact hDN ⟨u', hBD hu', rfl⟩

/-- The principal units of depth `n` are norms from the `p ^ n`-th cyclotomic floor, away from
the degenerate floor `p ^ n = 2`
([Milne 2020, Chap. I, §3, Ex. 3.13, p.44][MilneCFT]; Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:919`). -/
theorem higherUnitGroup_le (n : ℕ+) (h2 : p ^ (n : ℕ) ≠ 2) :
    higherUnitGroup ℚ_[p] n ≤ localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ))) := by
  by_cases hp2 : p = 2
  · subst hp2
    have hn2 : 2 ≤ (n : ℕ) := by
      by_contra h
      have h1 : (n : ℕ) = 1 := by have := n.pos; omega
      rw [h1] at h2
      exact h2 (pow_one 2)
    exact higherUnitGroup_le_two n hn2
  · have hc : 1 / (p - 1) = 0 := Nat.div_eq_of_lt (by have := hp.out.two_le; omega)
    exact higherUnitGroup_le_of_threshold p n n.ne_zero n (by rw [hc, add_zero])

/-- The index of the standard subgroup `⟨p⟩ ⊔ U^(n)` in `ℚ_[p]ˣ` is `(p - 1) * p ^ (n - 1)`
([Milne 2020, Chap. I, §1, p.25][MilneCFT]). -/
theorem standardSubgroup_index (n : ℕ+) :
    (Subgroup.zpowers (padicPrimeUnit p) ⊔ higherUnitGroup ℚ_[p] n).index =
      (p - 1) * p ^ ((n : ℕ) - 1) := by
  rw [higherUnitGroup_eq_map_integerHigherUnitGroup, padicPrimeUnit_eq]
  have h := standardLubinTateSubgroupIndex ℚ_[p] (PadicIntegerEquiv.irreducible_natCast p)
    ((n : ℕ) - 1)
  rw [Nat.sub_add_cancel n.pos, PadicIntegerEquiv.card_residueField] at h
  exact h

/-- The index of the norm subgroup of the `p ^ n`-th cyclotomic floor is its degree,
`(p - 1) * p ^ (n - 1)` ([Milne 2020, Chap. I, §1, Thm. 1.1 (b), p.20][MilneCFT]). -/
theorem localNormSubgroup_index (n : ℕ+) :
    (localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ)))).index =
      (p - 1) * p ^ ((n : ℕ) - 1) := by
  haveI : NeZero (p ^ (n : ℕ)) := ⟨pow_ne_zero _ hp.out.ne_zero⟩
  change Nat.card (ℚ_[p]ˣ ⧸ (Units.map (Algebra.norm ℚ_[p])).range) = _
  rw [normIndexAbelian ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ))), finrank_cycloField p n n.ne_zero,
    Nat.totient_prime_pow hp.out n.pos, mul_comm]

end PadicCycloFieldNormSubgroup

open PadicCycloFieldNormSubgroup in
/-- **The norm subgroup of the `p ^ n`-th cyclotomic floor over `ℚ_[p]`** is the subgroup
generated by `p` and the principal units of depth `n`: the norms from `ℚ_[p](ζ_{p^n})` are the
`u * p ^ m` with `u ≡ 1 mod p ^ n`
([Milne 2020, Chap. I, §3, Ex. 3.13 (b), p.44][MilneCFT]; Yamaguchi 2026,
`LocalClassFieldTheory/Finite/CyclotomicNorm/PrincipalUnits.lean:919`). -/
theorem padicCycloFieldNormSubgroup (p : ℕ) [hp : Fact p.Prime] (n : ℕ+) :
    localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ))) =
      Subgroup.zpowers (padicPrimeUnit p) ⊔ higherUnitGroup ℚ_[p] n := by
  have hS := standardSubgroup_index p n
  have hN := localNormSubgroup_index p n
  by_cases h2 : p ^ (n : ℕ) = 2
  · have hp2 : p = 2 := by
      have := (Nat.dvd_prime Nat.prime_two).mp (h2 ▸ dvd_pow_self p n.ne_zero)
      exact this.resolve_left hp.out.one_lt.ne'
    have hn1 : (n : ℕ) = 1 := by
      subst hp2
      exact Nat.pow_right_injective le_rfl (by simpa using h2)
    have hone : (p - 1) * p ^ ((n : ℕ) - 1) = 1 := by rw [hp2, hn1]; norm_num
    rw [Subgroup.index_eq_one.mp (hS.trans hone), Subgroup.index_eq_one.mp (hN.trans hone)]
  · have hle : Subgroup.zpowers (padicPrimeUnit p) ⊔ higherUnitGroup ℚ_[p] n ≤
        localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ))) :=
      sup_le (Subgroup.zpowers_le.mpr (padicPrimeUnit_mem p n n.ne_zero h2))
        (higherUnitGroup_le p n h2)
    have h := Subgroup.relIndex_mul_index hle
    rw [hS, hN] at h
    have hpos : 0 < (p - 1) * p ^ ((n : ℕ) - 1) :=
      Nat.mul_pos (by have := hp.out.two_le; omega) (Nat.pow_pos hp.out.pos)
    have hrel : (Subgroup.zpowers (padicPrimeUnit p) ⊔ higherUnitGroup ℚ_[p] n).relIndex
        (localNormSubgroup ℚ_[p] (cycloField ℚ_[p] (p ^ (n : ℕ)))) = 1 :=
      Nat.eq_of_mul_eq_mul_right hpos (by rw [h, one_mul])
    exact le_antisymm (Subgroup.relIndex_eq_one.mp hrel) hle

end Atlas.Knowledge
