import Mathlib
import Atlas.Knowledge.PadicIsMixedCharLocalField
import Atlas.Knowledge.ResidueCharacteristic
import Atlas.Knowledge.AbsoluteRamificationIndex

/-!
# p-adic integer equivalence

The integer ring of the carrier `ℚ_[p]` is Mathlib's `ℤ_[p]`: the valuation subring of the
valuative relation `Atlas.Knowledge.PadicIsMixedCharLocalField` installs is the closed unit
ball, which is what `ℤ_[p]` is by definition, so the two rings are one subring of `ℚ_[p]` and
the identification is a ring equivalence. Everything the layer's abstract invariants say about
`ℚ_[p]` reads off through it: `p` is a uniformizer, the residue field is `ZMod p` and so has
`p` elements, the residue characteristic is `p`, and the absolute ramification index is `1`.
These are the numbers the exponential threshold of `Atlas.Knowledge.PadicExpIsomorphism` and
the index counts of `Atlas.Knowledge.IntegerHigherUnitCount` take as inputs, and the item
exists so that `ℚ_[p]` can be fed to them. Everything here is proved.

## Main definitions

* `padicIntegerEquiv` — `𝒪[ℚ_[p]] ≃+* ℤ_[p]`.
* `PadicIntegerEquiv.residueFieldEquiv` — `𝓀[ℚ_[p]] ≃+* ZMod p`.

## Main statements

* `PadicIntegerEquiv.irreducible_natCast` — `p` is irreducible in `𝒪[ℚ_[p]]`; proved.
* `PadicIntegerEquiv.card_residueField` — `Nat.card 𝓀[ℚ_[p]] = p`; proved.
* `PadicIntegerEquiv.residueCharacteristic_eq` — `residueCharacteristic ℚ_[p] = p`; proved.
* `PadicIntegerEquiv.absoluteRamificationIndex_eq` — `absoluteRamificationIndex ℚ_[p] = 1`;
  proved.
* `PadicIntegerEquiv.mem_maximalIdeal_pow_iff` — the ideal filtration is the norm
  filtration: `x ∈ 𝓂[ℚ_[p]] ^ n ↔ ‖(x : ℚ_[p])‖ ≤ p ^ (-n)`; proved.

## Implementation notes

The equivalence is `RingEquiv.subringCongr` on an equality of subrings of `ℚ_[p]`, so its
underlying function is the identity on the underlying `p`-adic numbers and every coercion
lemma is `rfl`; the equality itself is the compatibility of the layer's valuation with
`Padic.mulValuation` read against `Padic.norm_le_one_iff_val_nonneg`. The invariants are
transported rather than recomputed: irreducibility along `MulEquiv.irreducible_iff` from
`PadicInt.irreducible_p`, the residue field along `IsLocalRing.ResidueField.mapEquiv` into
`PadicInt.residueField`, and the ramification index from
`Atlas.Knowledge.span_residueCharacteristic_eq_maximalIdeal_pow` once `𝓂[ℚ_[p]]` is known
to be generated by `p`. The residue characteristic is read from `ZMod p` through the transported
`CharP` instance. Nothing here is specific to the source; the source pins its own `p`-adic
model through a transported complete discretely valued field
(`LocalFieldTheory/Padic/PrincipalUnits.lean`), where Atlas keeps `ℚ_[p]` itself as the carrier.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
-/

open ValuativeRel

namespace Atlas.Knowledge

variable (p : ℕ) [hp : Fact p.Prime]

namespace PadicIntegerEquiv

/-- The valuation subring of `ℚ_[p]` is the closed unit ball, as a subring
([Serre 1979, Chap. II, §1, pp.26–27][Serre1979]). -/
theorem integer_eq : (valuation ℚ_[p]).integer = PadicInt.subring p := by
  ext x
  rw [Valuation.mem_integer_iff, PadicInt.mem_subring_iff,
    (isEquiv (valuation ℚ_[p]) Padic.mulValuation).le_one_iff_le_one]
  rcases eq_or_ne x 0 with rfl | hx
  · simp
  · rw [Padic.mulValuation_toFun, if_neg hx, Padic.norm_le_one_iff_val_nonneg,
      ← WithZero.exp_zero, WithZero.exp_le_exp]
    exact neg_nonpos

end PadicIntegerEquiv

/-- The integer ring of `ℚ_[p]` is `ℤ_[p]`
([Serre 1979, Chap. II, §1, pp.26–27][Serre1979]). -/
noncomputable def padicIntegerEquiv : 𝒪[ℚ_[p]] ≃+* ℤ_[p] :=
  RingEquiv.subringCongr (PadicIntegerEquiv.integer_eq p)

namespace PadicIntegerEquiv

@[simp]
theorem coe_apply (x : 𝒪[ℚ_[p]]) : ((padicIntegerEquiv p x : ℤ_[p]) : ℚ_[p]) = (x : ℚ_[p]) :=
  rfl

@[simp]
theorem coe_symm_apply (x : ℤ_[p]) :
    (((padicIntegerEquiv p).symm x : 𝒪[ℚ_[p]]) : ℚ_[p]) = (x : ℚ_[p]) :=
  rfl

/-- `p` is a uniformizer of `ℚ_[p]` ([Serre 1979, Chap. II, §1, p.27][Serre1979]). -/
theorem irreducible_natCast : Irreducible (p : 𝒪[ℚ_[p]]) := by
  rw [← MulEquiv.irreducible_iff (padicIntegerEquiv p), map_natCast]
  exact PadicInt.irreducible_p

/-- The maximal ideal of `𝒪[ℚ_[p]]` is generated by `p`. -/
theorem maximalIdeal_eq : 𝓂[ℚ_[p]] = Ideal.span {(p : 𝒪[ℚ_[p]])} :=
  (irreducible_natCast p).maximalIdeal_eq

/-- The residue field of `ℚ_[p]` is the prime field `ZMod p`
([Serre 1979, Chap. II, §1, p.27][Serre1979]). -/
noncomputable def residueFieldEquiv : 𝓀[ℚ_[p]] ≃+* ZMod p :=
  (IsLocalRing.ResidueField.mapEquiv (padicIntegerEquiv p)).trans PadicInt.residueField

/-- The residue field of `ℚ_[p]` has `p` elements
([Serre 1979, Chap. II, §1, p.27][Serre1979]). -/
theorem card_residueField : Nat.card 𝓀[ℚ_[p]] = p := by
  rw [Nat.card_congr (residueFieldEquiv p).toEquiv, Nat.card_zmod]

/-- The residue characteristic of `ℚ_[p]` is `p`
([Serre 1979, Chap. II, §1, p.27][Serre1979]). -/
theorem residueCharacteristic_eq : residueCharacteristic ℚ_[p] = p := by
  haveI : CharP 𝓀[ℚ_[p]] p := by
    rw [CharP.charP_iff_prime_eq_zero hp.out]
    apply (residueFieldEquiv p).injective
    rw [map_natCast, map_zero, ZMod.natCast_self]
  exact ringChar.eq 𝓀[ℚ_[p]] p

/-- `ℚ_[p]` is absolutely unramified: its absolute ramification index is `1`, the prime `p`
being its own uniformizer ([Serre 1979, Chap. II, §1, p.27][Serre1979]). -/
theorem absoluteRamificationIndex_eq : absoluteRamificationIndex ℚ_[p] = 1 := by
  have h := span_residueCharacteristic_eq_maximalIdeal_pow ℚ_[p]
  rw [residueCharacteristic_eq, ← maximalIdeal_eq] at h
  haveI : (𝓂[ℚ_[p]]).IsPrime := (IsLocalRing.maximalIdeal.isMaximal _).isPrime
  have hprime : Prime (𝓂[ℚ_[p]] : Ideal 𝒪[ℚ_[p]]) :=
    Ideal.prime_of_isPrime (IsDiscreteValuationRing.not_a_field 𝒪[ℚ_[p]]) inferInstance
  calc absoluteRamificationIndex ℚ_[p]
      = multiplicity 𝓂[ℚ_[p]] (𝓂[ℚ_[p]] ^ absoluteRamificationIndex ℚ_[p]) :=
        (multiplicity_pow_self_of_prime hprime _).symm
    _ = multiplicity 𝓂[ℚ_[p]] (𝓂[ℚ_[p]] ^ 1) := by rw [← h, pow_one]
    _ = 1 := multiplicity_pow_self_of_prime hprime 1

/-- The ideal filtration of `𝒪[ℚ_[p]]` is the norm filtration: `x ∈ 𝓂 ^ n` if and only if
`‖x‖ ≤ p ^ (-n)` ([Serre 1979, Chap. II, §1, pp.26–27][Serre1979]). -/
theorem mem_maximalIdeal_pow_iff (x : 𝒪[ℚ_[p]]) (n : ℕ) :
    x ∈ (𝓂[ℚ_[p]] ^ n : Ideal 𝒪[ℚ_[p]]) ↔ ‖(x : ℚ_[p])‖ ≤ (p : ℝ) ^ (-(n : ℤ)) := by
  rw [maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton,
    ← map_dvd_iff (padicIntegerEquiv p), map_pow, map_natCast, ← Ideal.mem_span_singleton,
    ← PadicInt.norm_le_pow_iff_mem_span_pow, PadicInt.norm_def, coe_apply]

end PadicIntegerEquiv

end Atlas.Knowledge
