import Mathlib
import Atlas.Knowledge.EisensteinSet
import Atlas.Knowledge.NormalizedValuation

/-!
# Serre mass of totally ramified extensions

The weighing of local fields behind the source's mass formula: the totally ramified degree-`h`
extensions of a local field inside a fixed algebraic closure, each weighted by
`q^{-c (K/F)}` for `c (K/F) = v_K (δ_{K/F}) - h + 1` the conductor-style exponent of the
different, summed and normalized by the degree. Serre's mass formula is the statement that
this weighing is a probability; the source consumes it as the left side of its Theorem 1.7,
which `Atlas.Knowledge.MassFormula` records against the shooting game.

## Main definitions

* `totallyRamifiedSet` — the source's `S (h, F)`, carved out of the algebraic closure by
  Eisenstein generation.
* `serreConductor` — the exponent `c (K/F)`, read off any Eisenstein presentation.
* `serreMass` — the mass of a set of extensions.

## Implementation notes

Three encodings, each with its reason. A totally ramified extension is one generated by a
root of an Eisenstein polynomial—the classical uniformizer argument, in both directions—so
`S (h, F)` is defined by Eisenstein generation, which needs no valuative structure on the
subfields of the closure. The different of a monogenic Eisenstein presentation is generated
by the derivative at the root, and on a totally ramified extension `v_K` is `v_F` of the
norm, so the conductor is read as the normalized valuation of the norm of the derivative,
minus `h - 1`; the reading is presentation-independent, and the definition takes an `sInf`
over presentations to stay canonical, junking to `0` off `S (h, F)`, where no presentation
exists. The source sums over isomorphism classes weighted by `1 / (q^c · #Aut)`; summing over
the subfields of a fixed closure counts each class once per embedding modulo automorphisms,
that is `h / #Aut` times, so the class sum is the subfield sum divided by `h`—the shape taken
here, whose events are isomorphism-invariant wherever the layer states one. The residue size
`q` is a parameter, pinned to the field by the consuming claims.

## References

* [Pagano2022] C. Pagano, *Jump sets in local fields*, J. Algebra **593** (2022), 398–476.
-/

namespace Atlas.Knowledge

open ValuativeRel
open scoped ENNReal

/-- The source's `S (h, F)`: the totally ramified degree-`h` extensions of `F` inside a fixed
algebraic closure, carved out by Eisenstein generation
([Pagano 2022, §1.1.2, p.406][Pagano2022]). -/
def totallyRamifiedSet (F : Type*) [Field F] [ValuativeRel F] (h : ℕ+) :
    Set (IntermediateField F (AlgebraicClosure F)) :=
  {K | ∃ g ∈ eisensteinSet F h, ∃ π : AlgebraicClosure F,
    Polynomial.aeval π (g.map (algebraMap ↥𝒪[F] F)) = 0 ∧
    IntermediateField.adjoin F {π} = K}

/-- The exponent `c (K/F) = v_K (δ_{K/F}) - h + 1` of the Serre mass, read off an Eisenstein
presentation: the different is generated by the derivative at the root, and `v_K` is `v_F` of
the norm on a totally ramified extension ([Pagano 2022, §1.1.2, p.406][Pagano2022]). -/
noncomputable def serreConductor (F : Type*) [Field F] [ValuativeRel F] [TopologicalSpace F]
    [IsMixedCharLocalField F] (h : ℕ+) (K : IntermediateField F (AlgebraicClosure F)) : ℕ :=
  sInf {c : ℕ | ∃ g ∈ eisensteinSet F h, ∃ π : AlgebraicClosure F,
    Polynomial.aeval π (g.map (algebraMap ↥𝒪[F] F)) = 0 ∧
    IntermediateField.adjoin F {π} = K ∧
    ∃ y : ↥K, (y : AlgebraicClosure F) =
        Polynomial.aeval π ((g.map (algebraMap ↥𝒪[F] F)).derivative) ∧
      ∃ u : Fˣ, (u : F) = Algebra.norm F y ∧
        (c : ℤ) = normalizedValuation F u - ((h : ℤ) - 1)}

/-- The **Serre mass** of a set of totally ramified degree-`h` extensions: each weighted by
`q^{-c (K/F)}`, summed over the subfields of the closure and normalized by the degree—the
class sum of the source, each isomorphism class appearing `h / #Aut` times among the
subfields ([Pagano 2022, §1.1.2, p.406][Pagano2022]). -/
noncomputable def serreMass (F : Type*) [Field F] [ValuativeRel F] [TopologicalSpace F]
    [IsMixedCharLocalField F] (q : ℕ+) (h : ℕ+)
    (A : Set (IntermediateField F (AlgebraicClosure F))) : ℝ≥0∞ :=
  (∑' K : {K // K ∈ totallyRamifiedSet F h ∧ K ∈ A},
    ((q : ℝ≥0∞))⁻¹ ^ serreConductor F h K.val) / (h : ℝ≥0∞)

end Atlas.Knowledge
