import Mathlib
import Atlas.Knowledge.HigherUnitGroup

/-!
# standard open subgroups

Every open subgroup of the multiplicative group of a nonarchimedean local field contains a
sufficiently deep higher unit group. An open subgroup of finite index `d` therefore contains
`Subgroup.zpowers (π ^ d) ⊔ higherUnitGroup K i` for some level `i` and any uniformizer `π`.
These are the standard subgroups used in the local existence theorem and in the finiteness
of the conductor exponent in `Atlas.Knowledge.ConductorExponent`.

## Main statements

* `exists_higherUnitGroup_le_of_isOpen` — an open subgroup of `Kˣ` contains a unit level.
* `exists_zpowers_sup_higherUnitGroup_le_of_isOpen_finiteIndex` — an open subgroup of finite
  index contains a standard subgroup for a given uniformizer.

## Implementation notes

The source's mapped-subgroup presentation `fieldPrincipalUnits` is identified with the
translate-set carrier of `Atlas.Knowledge.HigherUnitGroup` by
`Atlas.Knowledge.mem_higherUnitGroup_iff`. The neighborhood argument follows the source:
pull an open subgroup back to a neighborhood in the field, then choose a power of the
maximal ideal inside a valuation ball. Mathlib's
`Irreducible.maximalIdeal_pow_eq_setOf_le_v_coe_pow` identifies that power with a closed
ball, and `exists_pow_lt₀` supplies a sufficiently small radius. Increasing the exponent by
one gives a positive level, matching the layer's `ℕ+` indexing.

Both statements apply in either characteristic. The second keeps the source's finite-index
hypothesis, although `Subgroup.pow_index_mem` itself does not need it. Its uniformizer is an
argument because the Lubin–Tate consumer fixes one first; the level depends only on the open
subgroup. The same containment therefore holds uniformly for every choice of uniformizer.

## References

* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

namespace Atlas.Knowledge

noncomputable section

open ValuativeRel

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]

/-- **Every open subgroup of the multiplicative group of a
nonarchimedean local field contains a sufficiently deep unit
level** (Yamaguchi 2026,
`LocalFieldTheory/NonarchimedeanLocalField/StandardOpenSubgroups.lean:37`). -/
theorem exists_higherUnitGroup_le_of_isOpen (H : Subgroup Kˣ) (hH : IsOpen (H : Set Kˣ)) :
    ∃ i : ℕ+, higherUnitGroup K i ≤ H := by
  rcases Units.isEmbedding_val₀.isOpen_iff.mp hH with ⟨V, hVopen, hV⟩
  have hOneV : (1 : K) ∈ V := by
    have h1 : (1 : Kˣ) ∈ Units.val ⁻¹' V := hV.symm ▸ H.one_mem
    exact h1
  obtain ⟨γ, -, hball⟩ :=
    (IsValuativeTopology.hasBasis_nhds (1 : K)).mem_iff.mp (hVopen.mem_nhds hOneV)
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible (↥𝒪[K])
  haveI : MulArchimedean (ValueGroupWithZero K) :=
    ValuativeRel.isRankLeOne_iff_mulArchimedean.mp inferInstance
  obtain ⟨N, hN⟩ := exists_pow_lt₀
    (Valuation.integer.v_irreducible_lt_one (v := valuation K) hϖ) γ
  refine ⟨⟨N + 1, Nat.succ_pos _⟩, ?_⟩
  intro x hx
  obtain ⟨u, hu, rfl⟩ := (mem_higherUnitGroup_iff K ⟨N + 1, Nat.succ_pos _⟩ x).1 hx
  have huN := Ideal.pow_le_pow_right (Nat.le_succ N) hu
  have hbound : valuation K (((u : ↥𝒪[K]) - 1 : ↥𝒪[K]) : K) ≤
      valuation K (ϖ : K) ^ N := by
    exact (Set.ext_iff.mp
      (hϖ.maximalIdeal_pow_eq_setOf_le_v_coe_pow (valuation K) N) _).mp huN
  have hxV : ((Units.map (𝒪[K].subtype : ↥𝒪[K] →* K) u : Kˣ) : K) ∈ V := by
    apply hball
    simpa using hbound.trans_lt hN
  change Units.map (𝒪[K].subtype : ↥𝒪[K] →* K) u ∈ (H : Set Kˣ)
  rw [← hV]
  exact hxV

/-- **An open finite-index subgroup contains a standard subgroup**
generated by the index-th power of a given uniformizer and a
sufficiently deep unit level (Yamaguchi 2026,
`LocalFieldTheory/NonarchimedeanLocalField/StandardOpenSubgroups.lean:77`). -/
theorem exists_zpowers_sup_higherUnitGroup_le_of_isOpen_finiteIndex
    (H : Subgroup Kˣ) [H.FiniteIndex] (hH : IsOpen (H : Set Kˣ))
    (π : ↥𝒪[K]) (hπ : Irreducible π) :
    ∃ i : ℕ+,
      Subgroup.zpowers ((Units.mk0 (π : K)
        (fun h0 => hπ.ne_zero (Subtype.ext h0))) ^ H.index) ⊔ higherUnitGroup K i ≤ H := by
  obtain ⟨i, hi⟩ := exists_higherUnitGroup_le_of_isOpen K H hH
  exact ⟨i, sup_le ((Subgroup.zpowers_le).2 (H.pow_index_mem _)) hi⟩

end

end Atlas.Knowledge
