import Mathlib
import Atlas.Knowledge.StandardLubinTateGaloisDescription

/-!
# standard Lubin–Tate norm subgroup

The norm-subgroup description of the level tower — the existence engine of local class
field theory: the norms from level `n` are exactly the subgroup of `Kˣ` generated by the
uniformizer and the `(n+1)`-st higher units, Milne's
`Nm(K_{π,n+1}ˣ) = (1 + 𝔪^{n+1}) · π^ℤ`. The uniformizer unit is defined here; the
equality is recorded ahead of its proof — it is the index computation against the
changed-uniformizer comparison, local class field theory proper. This is the statement
Phase 2's recorded existence claims name as their engine.

## Main definitions

* `standardLubinTateUniformizerUnit` — `π` as an element of `Kˣ`.

## Main statements

* `standardLubinTateNormSubgroup_eq` — `⟨π⟩ ⊔ U^{(n+1)} = Nm(Lₙˣ)`; recorded ahead of
  its proof.

## Implementation notes

The norm subgroup is spelled as the range of `Units.map (Algebra.norm K)` on the level
field's units, and the principal side joins `Subgroup.zpowers` of the uniformizer unit
with the image of `Atlas.Knowledge.integerHigherUnitGroup` under the units map of
`algebraMap 𝒪[K] K` — everything in Mathlib vocabulary, no chosen-subgroup wrapper. The
claim is the per-uniformizer family Milne already states for every prime element; the
level field varies with `π`, so this is not more general than Milne, only than the
source's Lean statement, which fixes its transported canonical uniformizer
(`LocalClassFieldTheory/LubinTateApplication/StandardNormSubgroupExact.lean:85`) and
reaches other uniformizers through the changed-uniformizer comparison.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in
  Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

open scoped ValuativeRel

namespace Atlas.Knowledge

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsMixedCharLocalField K]

/-- The uniformizer as a unit of the fraction field
([Yamaguchi 2026, `LubinTate/FiniteLevel/NormSubgroup.lean:36`][Yamaguchi2026]). -/
noncomputable def standardLubinTateUniformizerUnit {π : 𝒪[K]} (hπ : Irreducible π) :
    Kˣ :=
  Units.mk0 (algebraMap 𝒪[K] K π) (by
    intro h0
    exact hπ.ne_zero (IsFractionRing.injective 𝒪[K] K (by rw [h0, map_zero])))

/-- The **norm subgroup of a standard level**: the subgroup generated by the uniformizer
and the `(n+1)`-st higher units is exactly the group of norms from level `n` — the
existence engine of local class field theory. Claim recorded ahead of its proof
([Milne 2020, Chap. I, §1, p.25][MilneCFT];
[Yamaguchi 2026,
`LocalClassFieldTheory/LubinTateApplication/StandardNormSubgroupExact.lean:85`]
[Yamaguchi2026]). -/
theorem standardLubinTateNormSubgroup_eq {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
        (integerHigherUnitGroup K (n + 1)).map
          (Units.map (algebraMap 𝒪[K] K).toMonoidHom) =
      (Units.map (Algebra.norm K
        (S := standardLubinTateLevelField K hπ n))).range := by
  sorry

end Atlas.Knowledge
