import Mathlib
import Atlas.Knowledge.IntegerHigherUnitCount
import Atlas.Knowledge.NormalizedValuation
import Atlas.Knowledge.StandardLubinTateUniformizerUnit

/-!
# standard Lubin–Tate subgroup index

The index of the candidate norm subgroup: the subgroup of `Kˣ` generated by the
uniformizer and the image of the `(n + 1)`-st integer higher units has index
`(q − 1) · qⁿ` — the degree of the level-`n` field, and the index Milne's norm-group
identity `Nm(K_{π,n}) = (1 + 𝔪ⁿ) · π^ℤ` forces on the norms. The computation is the
splitting of `Kˣ` along the normalized valuation: every field unit is a uniformizer
power times its unit part, the unit part measured back in `𝒪[K]ˣ` through the kernel
identification of `Atlas.Knowledge.NormalizedValuation`, so the quotient by the
candidate subgroup is the unit-parameter quotient that
`Atlas.Knowledge.integerHigherUnitCount` counts. This is the counting half of the norm
computation `Atlas.Knowledge.standardLubinTateNormSubgroup_eq` records.

## Main statements

* `standardLubinTateSubgroupIndex` — `[Kˣ : ⟨π⟩ ⊔ U^{(n+1)}] = (q − 1) · qⁿ`; proved.

## Implementation notes

The engine is a character `Kˣ →* 𝒪[K]ˣ ⧸ U^{(n+1)}` rather than an isomorphism
`Kˣ ≅ ℤ × 𝒪ˣ`: the unit part `x · (π^{v(x)})⁻¹` is a homomorphism because the group is
commutative, it lands in the valuation kernel by the section identity `v ∘ π^• = id`,
and the kernel equivalence to `𝒪[K]ˣ` is Mathlib's `Submonoid.unitsEquivUnitsType`
carried across `ker_normalizedValuationHom`, so its underlying value is the unit's image
on the nose and the `rfl`-steps downstream keep firing. The kernel of the character is
computed by `le_antisymm`: one inclusion decomposes a field unit as uniformizer power
times unit part, the other checks the two generators of the join separately, and the
index is then `Subgroup.index_ker` against the count. The normalized valuation takes
value `+1` on uniformizers — `Atlas.Knowledge.NormalizedValuation`'s sign — so the
section is `zpowersHom` at the uniformizer itself, with no inverse twist.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

open ValuativeRel

namespace Atlas.Knowledge

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsMixedCharLocalField K]

/-- The normalized valuation of the uniformizer unit is one. -/
private theorem normalizedValuationHom_uniformizerUnit {π : 𝒪[K]} (hπ : Irreducible π) :
    normalizedValuationHom K (standardLubinTateUniformizerUnit K hπ) =
      Multiplicative.ofAdd (1 : ℤ) := by
  have h := normalizedValuation_irreducible K π hπ
    (standardLubinTateUniformizerUnit K hπ) rfl
  rw [show normalizedValuationHom K (standardLubinTateUniformizerUnit K hπ) =
      Multiplicative.ofAdd
        (normalizedValuation K (standardLubinTateUniformizerUnit K hπ)) from rfl, h]

/-- The valuation retracts the uniformizer section. -/
private theorem normalizedValuationHom_section {π : 𝒪[K]} (hπ : Irreducible π)
    (m : Multiplicative ℤ) :
    normalizedValuationHom K
      (zpowersHom Kˣ (standardLubinTateUniformizerUnit K hπ) m) = m := by
  rw [zpowersHom_apply, map_zpow, normalizedValuationHom_uniformizerUnit K hπ, ← ofAdd_zsmul]
  simp

/-- The unit part of a field unit: divide off the uniformizer power. -/
private noncomputable def unitPart {π : 𝒪[K]} (hπ : Irreducible π) : Kˣ →* Kˣ :=
  MonoidHom.mk'
    (fun x => x * (zpowersHom Kˣ (standardLubinTateUniformizerUnit K hπ)
      (normalizedValuationHom K x))⁻¹)
    (fun x y => by
      rw [map_mul, map_mul, mul_inv]
      exact mul_mul_mul_comm x y _ _)

/-- The unit part has valuation one. -/
private theorem unitPart_mem_ker {π : 𝒪[K]} (hπ : Irreducible π) (x : Kˣ) :
    unitPart K hπ x ∈ (normalizedValuationHom K).ker := by
  rw [MonoidHom.mem_ker, unitPart, MonoidHom.mk'_apply, map_mul, map_inv,
    normalizedValuationHom_section K hπ, mul_inv_cancel]

/-- The unit part of a member of the kernel is itself. -/
private theorem unitPart_of_mem_ker {π : 𝒪[K]} (hπ : Irreducible π) {x : Kˣ}
    (hx : x ∈ (normalizedValuationHom K).ker) : unitPart K hπ x = x := by
  rw [unitPart, MonoidHom.mk'_apply, MonoidHom.mem_ker.mp hx]
  simp

/-- Every field unit is its uniformizer power times its unit part. -/
private theorem eq_zpow_mul_unitPart {π : 𝒪[K]} (hπ : Irreducible π) (x : Kˣ) :
    x = (standardLubinTateUniformizerUnit K hπ) ^
        Multiplicative.toAdd (normalizedValuationHom K x) * unitPart K hπ x := by
  rw [unitPart, MonoidHom.mk'_apply,
    show (zpowersHom Kˣ (standardLubinTateUniformizerUnit K hπ)
        (normalizedValuationHom K x)) =
      (standardLubinTateUniformizerUnit K hπ) ^
        Multiplicative.toAdd (normalizedValuationHom K x) from zpowersHom_apply _ _ _]
  rw [mul_comm x, mul_inv_cancel_left]

/-- The integer units are the kernel of the normalized valuation, as an equivalence. -/
private noncomputable def kerEquiv : 𝒪[K]ˣ ≃* (normalizedValuationHom K).ker :=
  (Submonoid.unitsEquivUnitsType (𝒪[K].toSubmonoid)).symm.trans
    (MulEquiv.subgroupCongr (ker_normalizedValuationHom K).symm)

/-- The unit part, restricted to the kernel. -/
private noncomputable def unitPartKer {π : 𝒪[K]} (hπ : Irreducible π) :
    Kˣ →* (normalizedValuationHom K).ker :=
  (unitPart K hπ).codRestrict _ (unitPart_mem_ker K hπ)

/-- The level character on the field units. -/
private noncomputable def fieldCharacter {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    Kˣ →* (𝒪[K]ˣ ⧸ integerHigherUnitGroup K (n + 1)) :=
  (QuotientGroup.mk' (integerHigherUnitGroup K (n + 1))).comp
    ((kerEquiv K).symm.toMonoidHom.comp (unitPartKer K hπ))

private theorem fieldCharacter_surjective {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    Function.Surjective (fieldCharacter K hπ n) := by
  intro c
  obtain ⟨u, rfl⟩ := QuotientGroup.mk'_surjective (integerHigherUnitGroup K (n + 1)) c
  refine ⟨((kerEquiv K u : (normalizedValuationHom K).ker) : Kˣ), ?_⟩
  have hmem : ((kerEquiv K u : (normalizedValuationHom K).ker) : Kˣ) ∈
      (normalizedValuationHom K).ker := (kerEquiv K u).2
  have hfix : unitPartKer K hπ ((kerEquiv K u : (normalizedValuationHom K).ker) : Kˣ) =
      kerEquiv K u := by
    apply Subtype.ext
    exact unitPart_of_mem_ker K hπ hmem
  rw [fieldCharacter, MonoidHom.comp_apply, MonoidHom.comp_apply, hfix]
  simp only [MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply]

private theorem fieldCharacter_ker {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    (fieldCharacter K hπ n).ker =
      Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
        (integerHigherUnitGroup K (n + 1)).map
          (Units.map (algebraMap 𝒪[K] K).toMonoidHom) := by
  apply le_antisymm
  · intro x hx
    rw [MonoidHom.mem_ker, fieldCharacter, MonoidHom.comp_apply, MonoidHom.comp_apply,
      QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff] at hx
    simp only [MulEquiv.coe_toMonoidHom] at hx
    have himg : unitPart K hπ x = Units.map (algebraMap 𝒪[K] K).toMonoidHom
        ((kerEquiv K).symm (unitPartKer K hπ x)) := by
      calc unitPart K hπ x
          = ((unitPartKer K hπ x : (normalizedValuationHom K).ker) : Kˣ) := rfl
        _ = ((kerEquiv K ((kerEquiv K).symm (unitPartKer K hπ x)) :
              (normalizedValuationHom K).ker) : Kˣ) := by
            rw [MulEquiv.apply_symm_apply]
        _ = Units.map (algebraMap 𝒪[K] K).toMonoidHom
            ((kerEquiv K).symm (unitPartKer K hπ x)) := rfl
    have h1 : (standardLubinTateUniformizerUnit K hπ) ^
        Multiplicative.toAdd (normalizedValuationHom K x) ∈
          Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
            (integerHigherUnitGroup K (n + 1)).map
              (Units.map (algebraMap 𝒪[K] K).toMonoidHom) :=
      Subgroup.mem_sup_left (Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) _)
    have h2 : unitPart K hπ x ∈
        Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
          (integerHigherUnitGroup K (n + 1)).map
            (Units.map (algebraMap 𝒪[K] K).toMonoidHom) :=
      Subgroup.mem_sup_right (Subgroup.mem_map.mpr ⟨_, hx, himg.symm⟩)
    rw [eq_zpow_mul_unitPart K hπ x]
    exact mul_mem h1 h2
  · rw [sup_le_iff]
    constructor
    · rw [Subgroup.zpowers_le, MonoidHom.mem_ker, fieldCharacter,
        MonoidHom.comp_apply, MonoidHom.comp_apply, QuotientGroup.mk'_apply,
        QuotientGroup.eq_one_iff]
      have hup : unitPartKer K hπ (standardLubinTateUniformizerUnit K hπ) = 1 := by
        apply Subtype.ext
        change unitPart K hπ (standardLubinTateUniformizerUnit K hπ) = 1
        rw [unitPart, MonoidHom.mk'_apply, normalizedValuationHom_uniformizerUnit,
          show zpowersHom Kˣ (standardLubinTateUniformizerUnit K hπ)
              (Multiplicative.ofAdd 1) =
            (standardLubinTateUniformizerUnit K hπ) ^
              Multiplicative.toAdd (Multiplicative.ofAdd (1 : ℤ)) from
            zpowersHom_apply _ _ _]
        simp
      rw [hup]
      simp only [map_one]
      exact one_mem _
    · rintro y ⟨u, hu, rfl⟩
      rw [MonoidHom.mem_ker, fieldCharacter, MonoidHom.comp_apply, MonoidHom.comp_apply,
        QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
      have hmem : Units.map (algebraMap 𝒪[K] K).toMonoidHom u ∈
          (normalizedValuationHom K).ker := (kerEquiv K u).2
      have hfix : unitPartKer K hπ (Units.map (algebraMap 𝒪[K] K).toMonoidHom u) =
          kerEquiv K u :=
        Subtype.ext (unitPart_of_mem_ker K hπ hmem)
      rw [hfix]
      simp only [MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_apply]
      exact hu

/-- **The candidate norm subgroup has index the level degree**:
`[Kˣ : ⟨π⟩ ⊔ U^{(n+1)}] = (q − 1) · qⁿ`
([Milne 2020, Chap. I, §1, p.25][MilneCFT];
[Yamaguchi 2026, `LocalClassFieldTheory/LubinTateApplication/StandardSubgroupIndex.lean:74`]
[Yamaguchi2026]). -/
theorem standardLubinTateSubgroupIndex {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    (Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
      (integerHigherUnitGroup K (n + 1)).map
        (Units.map (algebraMap 𝒪[K] K).toMonoidHom)).index =
      (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n := by
  rw [← fieldCharacter_ker K hπ n, Subgroup.index_ker,
    MonoidHom.range_eq_top.mpr (fieldCharacter_surjective K hπ n), Subgroup.card_top]
  simpa using integerHigherUnitCount K (n + 1) (Nat.succ_ne_zero n)

end Atlas.Knowledge
