import Mathlib
import Atlas.Knowledge.IntegerHigherUnitGroup
import Atlas.Knowledge.IsMixedCharLocalField
import Atlas.Knowledge.NormIndexAbelian
import Atlas.Knowledge.StandardLubinTateGaloisDescription
import Atlas.Knowledge.StandardLubinTateLevelField
import Atlas.Knowledge.StandardLubinTateNormMembership
import Atlas.Knowledge.StandardLubinTateSubgroupIndex
import Atlas.Knowledge.StandardLubinTateUniformizerUnit

/-!
# standard Lubin–Tate norm subgroup

The norm-subgroup description of the level tower — the existence engine of local class
field theory: the norms from level `n` are exactly the subgroup of `Kˣ` generated by the
uniformizer and the `(n+1)`-st higher units, Milne's
`Nm(K_{π,n+1}ˣ) = (1 + 𝔪^{n+1}) · π^ℤ`. The uniformizer unit is
`Atlas.Knowledge.standardLubinTateUniformizerUnit`; the equality is proved as the index
squeeze it always was: the containment of
`Atlas.Knowledge.standardLubinTateNormMembership_le`, the principal side's index of
`Atlas.Knowledge.standardLubinTateSubgroupIndex`, and the norm side's index from
`Atlas.Knowledge.normIndexAbelian` at the level degree, the cardinality form of finite
local reciprocity. This is the statement Phase 2's recorded existence claims name as
their engine.

## Main statements

* `standardLubinTateNormSubgroup_eq` — `⟨π⟩ ⊔ U^{(n+1)} = Nm(Lₙˣ)`; proved as an index
  squeeze against `Atlas.Knowledge.normIndexAbelian`.

## Implementation notes

The norm subgroup is spelled as the range of `Units.map (Algebra.norm K)` on the level
field's units, and the principal side joins `Subgroup.zpowers` of the uniformizer unit
with the image of `Atlas.Knowledge.integerHigherUnitGroup` under the units map of
`algebraMap 𝒪[K] K` — everything in Mathlib vocabulary, no chosen-subgroup wrapper. The
claim is the per-uniformizer family Milne already states for every prime element; the
level field varies with `π`, so this is not more general than Milne, only than the
source's Lean statement, which fixes its transported canonical uniformizer
(`LocalClassFieldTheory/LubinTateApplication/StandardNormSubgroupExact.lean:85`) and
reaches other uniformizers through the changed-uniformizer comparison.

## References

* [MilneCFT] J. S. Milne, *Class field theory* (v4.03), available at www.jmilne.org/math/,
  2020.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in
  Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

open scoped ValuativeRel

namespace Atlas.Knowledge

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsMixedCharLocalField K]

/- Two subgroups with the same finite index, one inside the other, coincide: the
relative index collapses to one. -/
private theorem subgroup_eq_of_le_of_index_eq {G : Type*} [Group G] {H N : Subgroup G}
    (hle : H ≤ N) (hidx : H.index = N.index) (h0 : N.index ≠ 0) : H = N := by
  have hrel := Subgroup.relIndex_mul_index hle
  rw [hidx] at hrel
  have h1 : H.relIndex N = 1 :=
    Nat.eq_of_mul_eq_mul_right (Nat.pos_of_ne_zero h0) (by rw [hrel, one_mul])
  exact le_antisymm hle (Subgroup.relIndex_eq_one.mp h1)

/-- The **norm subgroup of a standard level**: the subgroup generated by the uniformizer
and the `(n+1)`-st higher units is exactly the group of norms from level `n` — the
existence engine of local class field theory, proved as an index squeeze against
`Atlas.Knowledge.normIndexAbelian`
([Milne 2020, Chap. I, §1, p.25][MilneCFT];
[Yamaguchi 2026,
`LocalClassFieldTheory/LubinTateApplication/StandardNormSubgroupExact.lean:85`]
[Yamaguchi2026]). -/
theorem standardLubinTateNormSubgroup_eq {π : 𝒪[K]} (hπ : Irreducible π) (n : ℕ) :
    Subgroup.zpowers (standardLubinTateUniformizerUnit K hπ) ⊔
        (integerHigherUnitGroup K (n + 1)).map
          (Units.map (algebraMap 𝒪[K] K).toMonoidHom) =
      (Units.map (Algebra.norm K
        (S := standardLubinTateLevelField K hπ n))).range := by
  haveI : IsAbelianGalois K ↥(standardLubinTateLevelField K hπ n) :=
    standardLubinTateLevelField_isAbelianGalois K hπ n
  have hq1 : 1 < Nat.card 𝓀[K] := Finite.one_lt_card
  have hidx0 : (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n ≠ 0 :=
    Nat.mul_ne_zero (by omega) (Nat.pow_pos (by omega : 0 < Nat.card 𝓀[K])).ne'
  have hN : ((Units.map (Algebra.norm K
      (S := standardLubinTateLevelField K hπ n))).range).index =
      (Nat.card 𝓀[K] - 1) * Nat.card 𝓀[K] ^ n := by
    have h := normIndexAbelian K ↥(standardLubinTateLevelField K hπ n)
    rw [standardLubinTateLevelField_finrank (A := ↥𝒪[K]) (K := K) hπ n] at h
    exact h
  refine subgroup_eq_of_le_of_index_eq (standardLubinTateNormMembership_le K hπ n)
    ?_ ?_
  · rw [standardLubinTateSubgroupIndex K hπ n, hN]
  · rw [hN]
    exact hidx0

end Atlas.Knowledge
