import Mathlib
import Atlas.Knowledge.TateCohomologyFiniteCyclic

/-!
# Tate-vanishing norm surjectivity

Under `Ĥ⁰ = 0` the norm reaches every fixed point: for a finite cyclic
group the zeroth Tate cohomology is `A^G / N A` read at the generator,
so its vanishing hands each `g`-fixed element a norm preimage. The
`Ĥ⁰` twin of `Atlas.Knowledge.tateVanishingNormKernel`, and the
elementwise content the universal norm-descent lift consumes (#104).

## Main statements

* `tateVanishingNormSurjectivity` — under `Ĥ⁰ = 0`, every `g`-fixed
  element is a norm; proved.

## Implementation notes

The statement sits at Mathlib's own one-universe generality
`{R G : Type u}`: `tateCohomology` binds the coefficient ring and the
group in a single universe block, so the ring is generalized from the
engine's `ℤ` to any commutative ring to leave the group free — the
hypothesis is inherently cohomological, so neither an elementwise
restatement (it would equal the conclusion) nor a `Shrink` transport
(no consumer supplies a shrunk vanishing) buys more. An instantiation
at `ℤ` coefficients still drops the group to `Type 0` — Mathlib's
homological layer ties the universes, not `Rep` itself, which is now
polymorphic — which is why the engine's `Type*` witness chain takes
this vanishing elementwise, as a hypothesis of
`Atlas.Knowledge.universalNormDescent_cyclic_lift_and_correction`,
rather than through this item. The source states this beside its
elementary unit-cohomology axiom; the layer names it for what it is
and shelves it beside its `Ĥ⁻¹` twin, whose `G`/`A` variable names it
also adopts for the source's `IntegralRepGroupType`-valued `Q`/`M`.
The `isCyclic_of_generator` helper is the anonymous constructor, and
the finite-cyclic comparison is the layer's
`tateCohomologyIsoFiniteCyclicZero`.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer
  New York, 1979.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

open CategoryTheory

/-- **Under `Ĥ⁰ = 0` every `g`-fixed element is a norm**: for a finite
cyclic group generated by `g`, the vanishing of the zeroth Tate cohomology
`A^G / N A` hands each fixed element a norm preimage
([Serre 1979, Chap. VIII, §4, p.133][Serre1979];
[Yamaguchi 2026,
`AbstractClassFieldTheory/Reciprocity/Construction/UnitCohomologyAxiom.lean:167`]
[Yamaguchi2026]). -/
theorem tateVanishingNormSurjectivity {R G : Type u} [CommRing R] [Group G]
    [Fintype G] (A : Rep R G) (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (hzero : Limits.IsZero (tateCohomology A 0)) :
    ∀ x : A.V, A.ρ g x = x → ∃ y : A.V, A.norm.hom y = x := by
  letI : IsCyclic G := ⟨⟨g, hg⟩⟩
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  let S := Rep.FiniteCyclicGroup.normHomCompSub A g
  have hSzero : Limits.IsZero S.homology := by
    exact Limits.IsZero.of_iso hzero
      (tateCohomologyIsoFiniteCyclicZero A g hg).symm
  have hS : S.Exact := (S.exact_iff_isZero_homology).2 hSzero
  intro x hx
  have hxker : S.g x = 0 := by
    change A.ρ g x - x = 0
    exact sub_eq_zero.mpr hx
  rcases (S.moduleCat_exact_iff.mp hS x hxker) with ⟨y, hy⟩
  exact ⟨y, hy⟩

end Atlas.Knowledge
