import Mathlib
import Atlas.Knowledge.TateCohomologyFiniteCyclic

/-!
# norm kernel under Tate vanishing

The elementwise content of `Ĥ⁻¹(G, A) = 0` for a finite cyclic group: every
norm-zero element of the module is a `(ρ(g) − 1)`-value. This is the eliminator the
reciprocity engine (#104) applies at each finite unramified cyclic level — the step
that turns the cohomological unit axiom into an actual preimage — extracted from
the homology object rather than assumed separately.

## Main statements

* `tateVanishingNormKernel` — under `Ĥ⁻¹ = 0`, the norm kernel is the
  `(ρ(g) − 1)`-range; proved.

## Implementation notes

The route runs through `H¹`: the finite-cyclic periodicity identifies `H¹(G, A)`
with the homology of `A —(ρ(g)−1)→ A —N→ A` and hence with `Ĥ⁻¹(G, A)` through
`Atlas.Knowledge.tateCohomologyIsoFiniteCyclicNegOne`, and the vanishing
hypothesis makes the class of a norm-kernel element trivial, which Mathlib's
`groupCohomologyπOdd_eq_zero_iff` converts into the witness. The group sits in
`Type 0`: Mathlib's `tateCohomology` requires the coefficient ring and the group in
one universe, and the ring is `ℤ`.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer
  New York, 1979.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

open CategoryTheory

/- The finite-cyclic periodicity in the one degree needed: `H¹ ≅ Ĥ⁻¹`. -/
private noncomputable def finiteCyclicH1IsoTateNegOne {G : Type} [Group G]
    [Fintype G] (A : Rep ℤ G) (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    groupCohomology.H1 A ≅ tateCohomology A (-1) := by
  letI : IsCyclic G := ⟨⟨g, hg⟩⟩
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  let e :
      groupCohomology.H1 A ≅
        (Rep.FiniteCyclicGroup.subCompNormHom A g).homology := by
    simpa using
      (Rep.FiniteCyclicGroup.groupCohomologyIsoOdd A g hg 1 (by simp))
  exact e ≪≫ (tateCohomologyIsoFiniteCyclicNegOne A g hg).symm

/-- **Under `Ĥ⁻¹ = 0` the norm kernel is the `(ρ(g) − 1)`-range**: for a finite
cyclic group generated by `g`, every norm-zero element has a `(ρ(g) − 1)`-preimage
— `Ĥ⁻¹ = ker N/DA` read elementwise at zero
([Serre 1979, Chap. VIII, §4, p.133][Serre1979];
[Yamaguchi 2026, `CyclicCohomology/NormKernelVanishing.lean:116`]
[Yamaguchi2026]). -/
theorem tateVanishingNormKernel {G : Type} [Group G] [Fintype G]
    (A : Rep ℤ G) (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (hzero : Limits.IsZero (tateCohomology A (-1))) :
    ∀ x : A.V, A.norm.hom x = 0 →
      ∃ y : A.V, A.ρ g y - y = x := by
  letI : IsCyclic G := ⟨⟨g, hg⟩⟩
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  letI : Module ℤ A.V := A.hV2
  have hH1 : Limits.IsZero (groupCohomology.H1 A) :=
    Limits.IsZero.of_iso hzero (finiteCyclicH1IsoTateNegOne A g hg)
  letI : Subsingleton (groupCohomology.H1 A) :=
    ModuleCat.subsingleton_of_isZero hH1
  intro x hx
  let x' : LinearMap.ker A.norm.hom.toLinearMap := ⟨x, hx⟩
  have hclass :
      Rep.FiniteCyclicGroup.groupCohomologyπOdd A g hg 1 (by simp) x' = 0 :=
    Subsingleton.elim _ _
  rcases (Rep.FiniteCyclicGroup.groupCohomologyπOdd_eq_zero_iff
    A g hg 1 (by simp) x').1 hclass with ⟨y, hy⟩
  exact ⟨y, by simpa [Rep.sub_hom] using hy⟩

end Atlas.Knowledge
