import Mathlib
import Atlas.Knowledge.TateCohomologyFiniteCyclic

/-!
# norm kernel under Tate vanishing

The elementwise content of `Ĥ⁻¹(G, A) = 0` for a finite cyclic group: every
norm-zero element of the module is a `(ρ(g) − 1)`-value. This is the extraction
the reciprocity engine (#104) reads its cohomological vanishing through — the step
that turns a trivial homology object into an actual preimage — recorded from the
homology object rather than assumed separately.

## Main statements

* `tateVanishingNormKernel` — under `Ĥ⁻¹ = 0`, the norm kernel is the
  `(ρ(g) − 1)`-range; proved.

## Implementation notes

The statement sits at Mathlib's own one-universe generality `{R G : Type u}`:
`tateCohomology` binds the coefficient ring and the group in a single universe
block, so the ring is generalized from the engine's `ℤ` to any commutative ring to
leave the group free — the hypothesis is inherently cohomological, so neither an
elementwise restatement (it would equal the conclusion verbatim) nor a `Shrink`
transport (no consumer supplies a shrunk vanishing) buys more. An instantiation at
`ℤ` coefficients still drops the group to `Type 0` — Mathlib's homological layer
ties the universes, not `Rep` itself, which is now polymorphic — which is why the
engine's `Type*` witness chain takes this eliminator elementwise, as a hypothesis
of `Atlas.Knowledge.universalNormDescent_cyclic_lift_and_correction`, rather than
through this item. The route runs through `H¹`: the finite-cyclic periodicity
identifies `H¹(G, A)` with the homology of `A —(ρ(g)−1)→ A —N→ A` and hence with
`Ĥ⁻¹(G, A)` through `Atlas.Knowledge.tateCohomologyIsoFiniteCyclicNegOne`, and the
vanishing hypothesis makes the class of a norm-kernel element trivial, which
Mathlib's `groupCohomologyπOdd_eq_zero_iff` converts into the witness.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer
  New York, 1979.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

open CategoryTheory

/- The finite-cyclic periodicity in the one degree needed: `H¹ ≅ Ĥ⁻¹`. -/
private noncomputable def finiteCyclicH1IsoTateNegOne {R G : Type u} [CommRing R]
    [Group G] [Fintype G] (A : Rep R G) (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    groupCohomology.H1 A ≅ tateCohomology A (-1) := by
  letI : IsCyclic G := ⟨⟨g, hg⟩⟩
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  let e :
      groupCohomology.H1 A ≅
        (Rep.FiniteCyclicGroup.subCompNormHom A g).homology := by
    simpa using
      (Rep.FiniteCyclicGroup.groupCohomologyIsoOdd A g hg 1 (by simp))
  exact e ≪≫ (tateCohomologyIsoFiniteCyclicNegOne A g hg).symm

/-- **Under `Ĥ⁻¹ = 0` the norm kernel is the `(ρ(g) − 1)`-range**: for a finite
cyclic group generated by `g`, every norm-zero element has a `(ρ(g) − 1)`-preimage
— `Ĥ⁻¹ = ker N/DA` read elementwise at zero
([Serre 1979, Chap. VIII, §4, p.133][Serre1979];
[Yamaguchi 2026, `CyclicCohomology/NormKernelVanishing.lean:116`]
[Yamaguchi2026]). -/
theorem tateVanishingNormKernel {R G : Type u} [CommRing R] [Group G] [Fintype G]
    (A : Rep R G) (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (hzero : Limits.IsZero (tateCohomology A (-1))) :
    ∀ x : A.V, A.norm.hom x = 0 →
      ∃ y : A.V, A.ρ g y - y = x := by
  letI : IsCyclic G := ⟨⟨g, hg⟩⟩
  letI : CommGroup G := IsCyclic.commGroup (α := G)
  letI : Module R A.V := A.hV2
  have hH1 : Limits.IsZero (groupCohomology.H1 A) :=
    Limits.IsZero.of_iso hzero (finiteCyclicH1IsoTateNegOne A g hg)
  letI : Subsingleton (groupCohomology.H1 A) :=
    ModuleCat.subsingleton_of_isZero hH1
  intro x hx
  let x' : LinearMap.ker A.norm.hom.toLinearMap := ⟨x, hx⟩
  have hclass :
      Rep.FiniteCyclicGroup.groupCohomologyπOdd A g hg 1 (by simp) x' = 0 :=
    Subsingleton.elim _ _
  rcases (Rep.FiniteCyclicGroup.groupCohomologyπOdd_eq_zero_iff
    A g hg 1 (by simp) x').1 hclass with ⟨y, hy⟩
  exact ⟨y, by simpa [Rep.sub_hom] using hy⟩

end Atlas.Knowledge
