import Mathlib

/-!
# Tate cohomology of a finite cyclic group in boundary degrees

Mathlib's Tate cohomology in degrees `0` and `-1`, identified with the standard
finite-cyclic short complexes: for a finite cyclic group generated by `g`,
`Ĥ⁰(G, A)` is the homology of `A —N→ A —(ρ(g)−1)→ A` and `Ĥ⁻¹(G, A)` the homology
of `A —(ρ(g)−1)→ A —N→ A` — the period-two description `Ĥ⁰ = A^G/NA`,
`Ĥ⁻¹ = ker N/DA`. No alternative cohomology model is introduced: both sides are
homology objects Mathlib already defines, and the reciprocity engine (#104) reads
its class-field-axiom data through these identifications.

## Main definitions

* `tateCohomologyIsoZeroBoundary` — `Ĥ⁰` as boundary short-complex homology, for
  any finite group.
* `tateCohomologyIsoFiniteCyclicZero` — the cyclic `Ĥ⁰` description.
* `tateCohomologyIsoFiniteCyclicNegOne` — the cyclic `Ĥ⁻¹` description.

## Implementation notes

The degree-zero identification rewrites the Tate complex's short complex at `0`
through Mathlib's chain/cochain isomorphisms in degrees `-1, 0, 1`; the cyclic
forms then replace kernel and boundary through
`groupCohomology.d₀₁_ker_eq_invariants` and the finite-cyclic coinvariants
identification, transporting homology along `Submodule.Quotient.equiv`. Everything
is universe-polymorphic in the coefficient ring and the group.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer
  New York, 1979.
* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

open CategoryTheory

/-- **Degree-zero Tate cohomology is boundary short-complex homology**: for every
finite group, `Ĥ⁰(G, A)` is the homology of `A —N→ A —d₀₁→ C¹(G, A)`
([Serre 1979, Chap. VIII, §1, p.127][Serre1979] — `Ĥ⁰ = A^G/NA` with
`N = Σ_{s ∈ G} s`;
[Yamaguchi 2026, `CyclicCohomology/TateComparison.lean:22`][Yamaguchi2026]). -/
noncomputable def tateCohomologyIsoZeroBoundary {R G : Type u} [CommRing R]
    [Group G] [Fintype G] (A : Rep R G) :
    tateCohomology A 0 ≅
      (ShortComplex.mk A.norm.toModuleCatHom (groupCohomology.d₀₁ A)
        (Rep.norm_comp_d_eq_zero A)).homology := by
  let S : ShortComplex (ModuleCat R) :=
    .mk A.norm.toModuleCatHom (groupCohomology.d₀₁ A)
      (Rep.norm_comp_d_eq_zero A)
  let eS : (tateComplex A).sc 0 ≅ S :=
    (tateComplex A).isoSc' (-1) 0 1 (by simp) (by simp) ≪≫
      ShortComplex.isoMk
        (by exact groupHomology.chainsIso₀ A)
        (groupCohomology.cochainsIso₀ A)
        (groupCohomology.cochainsIso₁ A)
        (by
          change
            (groupHomology.chainsIso₀ A).hom ≫ A.norm.toModuleCatHom =
              A.tateNorm ≫ (groupCohomology.cochainsIso₀ A).hom
          rw [Rep.tateNorm]
          simp)
        (groupCohomology.comp_d₀₁_eq A)
  exact ShortComplex.homologyMapIso eS

/-- **The cyclic `Ĥ⁰` description**: for a finite cyclic group generated by `g`,
degree-zero Tate cohomology is the homology of `A —N→ A —(ρ(g)−1)→ A` —
`Ĥ⁰ = A^G/NA` read at the actual homology object
([Serre 1979, Chap. VIII, §4, p.133][Serre1979] —
"`Ĥ^q(G,A) = Ker(D)/Im(N) = A^G/NA` for `q ≡ 0 mod 2`";
[Yamaguchi 2026, `CyclicCohomology/TateComparison.lean:47`][Yamaguchi2026]). -/
noncomputable def tateCohomologyIsoFiniteCyclicZero {R G : Type u} [CommRing R]
    [CommGroup G] [Fintype G] (A : Rep R G) (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    tateCohomology A 0 ≅
      (Rep.FiniteCyclicGroup.normHomCompSub A g).homology := by
  let S : ShortComplex (ModuleCat R) :=
    .mk A.norm.toModuleCatHom (groupCohomology.d₀₁ A)
      (Rep.norm_comp_d_eq_zero A)
  let T := Rep.FiniteCyclicGroup.normHomCompSub A g
  have hker : LinearMap.ker S.g.hom = LinearMap.ker T.g.hom := by
    dsimp [S, T]
    rw [groupCohomology.d₀₁_ker_eq_invariants]
    ext x
    simpa [Rep.sub_hom, sub_eq_zero] using
      Representation.mem_invariants_iff_of_forall_mem_zpowers A.ρ g hg x
  let eK : LinearMap.ker S.g.hom ≃ₗ[R] LinearMap.ker T.g.hom :=
    LinearEquiv.ofEq _ _ hker
  have hboundary :
      (LinearMap.range S.moduleCatToCycles).map eK.toLinearMap =
        LinearMap.range T.moduleCatToCycles := by
    ext x
    constructor
    · rintro ⟨y, ⟨z, rfl⟩, rfl⟩
      refine ⟨z, ?_⟩
      apply Subtype.ext
      rfl
    · rintro ⟨z, rfl⟩
      refine ⟨S.moduleCatToCycles z, ⟨z, rfl⟩, ?_⟩
      apply Subtype.ext
      rfl
  let eQ : S.moduleCatLeftHomologyData.H ≅ T.moduleCatLeftHomologyData.H :=
    (Submodule.Quotient.equiv _ _ eK hboundary).toModuleIso
  exact tateCohomologyIsoZeroBoundary A ≪≫
    S.moduleCatHomologyIso ≪≫ eQ ≪≫ T.moduleCatHomologyIso.symm

/-- **The cyclic `Ĥ⁻¹` description**: for a finite cyclic group generated by `g`,
degree-minus-one Tate cohomology is the homology of `A —(ρ(g)−1)→ A —N→ A` —
`Ĥ⁻¹ = ker N/DA` read at the actual homology object
([Serre 1979, Chap. VIII, §4, p.133][Serre1979] —
"`Ĥ^q(G,A) = Ker(N)/Im(D) = _N A/DA` for `q ≡ 1 mod 2`";
[Yamaguchi 2026, `CyclicCohomology/TateComparison.lean:83`][Yamaguchi2026]). -/
noncomputable def tateCohomologyIsoFiniteCyclicNegOne {R G : Type u} [CommRing R]
    [CommGroup G] [Fintype G] (A : Rep R G) (g : G)
    (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    tateCohomology A (-1) ≅
      (Rep.FiniteCyclicGroup.subCompNormHom A g).homology := by
  let S : ShortComplex (ModuleCat R) :=
    .mk (groupHomology.d₁₀ A) A.norm.toModuleCatHom (Rep.comp_eq_zero A)
  let eS : (tateComplex A).sc (-1) ≅ S :=
    (tateComplex A).isoSc' (-2) (-1) 0 (by simp) (by simp) ≪≫
      ShortComplex.isoMk
        (groupHomology.chainsIso₁ A)
        (groupHomology.chainsIso₀ A)
        (groupCohomology.cochainsIso₀ A)
        (groupHomology.comp_d₁₀_eq A)
        (by simp [S, tateComplex, Rep.tateNorm]; rfl)
  let T := Rep.FiniteCyclicGroup.subCompNormHom A g
  have hRange : LinearMap.range S.f.hom = LinearMap.range T.f.hom := by
    dsimp [S, T]
    rw [groupHomology.range_d₁₀_eq_coinvariantsKer]
    exact Representation.FiniteCyclicGroup.coinvariantsKer_eq_range A.ρ g hg
  let eK : LinearMap.ker S.g.hom ≃ₗ[R] LinearMap.ker T.g.hom :=
    LinearEquiv.ofEq _ _ rfl
  have hboundary :
      (LinearMap.range S.moduleCatToCycles).map eK.toLinearMap =
        LinearMap.range T.moduleCatToCycles := by
    ext x
    constructor
    · rintro ⟨y, ⟨z, rfl⟩, rfl⟩
      have hz : S.f z ∈ LinearMap.range T.f.hom := by
        rw [← hRange]
        exact ⟨z, rfl⟩
      rcases hz with ⟨w, hw⟩
      refine ⟨w, ?_⟩
      apply Subtype.ext
      exact hw
    · rintro ⟨w, rfl⟩
      have hw : T.f w ∈ LinearMap.range S.f.hom := by
        rw [hRange]
        exact ⟨w, rfl⟩
      rcases hw with ⟨z, hz⟩
      refine ⟨S.moduleCatToCycles z, ⟨z, rfl⟩, ?_⟩
      apply Subtype.ext
      exact hz
  let eQ : S.moduleCatLeftHomologyData.H ≅ T.moduleCatLeftHomologyData.H :=
    (Submodule.Quotient.equiv _ _ eK hboundary).toModuleIso
  exact ShortComplex.homologyMapIso eS ≪≫
    S.moduleCatHomologyIso ≪≫ eQ ≪≫ T.moduleCatHomologyIso.symm

end Atlas.Knowledge
