import Mathlib

/-!
# topological generation

The topological-generation theory the Frobenius fixed-field construction
runs on: a set topologically generates a group when the closure of the
subgroup it generates is everything, packaged with the closed subgroup a set
generates. Around them, the lemmas the construction consumes: membership in
a closed generated subgroup pushes along a continuous homomorphism into the
image's generated subgroup, a group with a dense image of `Multiplicative ℤ`
is topologically generated by the image of the generator, and generation
itself pushes along continuous surjections and descends to quotients (#104).

## Main definitions

* `TopologicallyGenerates` — the closure of the generated subgroup is `⊤`.
* `closedSubgroupGenerated` / `closedSubgroupGeneratedMap` — the closed
  subgroup a set generates, with the canonical family inside it.

## Main statements

* `topologicallyGenerates_iff_dense` — topological generation is density of
  the generated subgroup; proved.
* `closedSubgroupGeneratedMap_topologicallyGenerates` — the canonical
  family topologically generates its closed generated subgroup; proved.
* `map_mem_closedSubgroupGenerated_image` /
  `map_mem_closedSubgroupGenerated_singleton` — membership in a closed
  generated subgroup pushes along a continuous homomorphism; proved.
* `topologicallyGenerates_singleton_of_denseRange_mint` — a group with a
  dense image of `Multiplicative ℤ` is topologically generated by the image
  of the generator `Multiplicative.ofAdd 1`; proved.
* `topologicallyGenerates_image_of_continuousSurjective` /
  `topologicallyGenerates_quotient_image` — generation pushes along
  continuous surjections and descends to quotients; proved.

## References

* n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory in Lean 4*,
  [GitHub repository](https://github.com/n-yamaguchi-0729/ClassFieldTheory), pinned commit
  `6010237`, 2026.
-/

open Set

namespace Atlas.Knowledge

universe u v

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- **Topological generation**: the closure of the abstract subgroup a set
generates is the whole group (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:24`). -/
def TopologicallyGenerates (X : Set G) : Prop :=
  (Subgroup.closure X).topologicalClosure = ⊤

/-- **Topological generation is density of the generated subgroup**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:29`). -/
theorem topologicallyGenerates_iff_dense {X : Set G} :
    TopologicallyGenerates (G := G) X ↔
      Dense ((Subgroup.closure X : Subgroup G) : Set G) := by
  rw [TopologicallyGenerates, SetLike.ext'_iff,
    Subgroup.topologicalClosure_coe, Subgroup.coe_top, dense_iff_closure_eq]

/-- **The closed subgroup a set topologically generates** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:36`). -/
def closedSubgroupGenerated (X : Set G) : ClosedSubgroup G where
  toSubgroup := (Subgroup.closure X).topologicalClosure
  isClosed' := Subgroup.isClosed_topologicalClosure _

/-- **The canonical family in the closed subgroup that it generates**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:41`). -/
def closedSubgroupGeneratedMap {A : Type v} (φ : A → G) :
    A → (closedSubgroupGenerated (G := G) (Set.range φ) : Subgroup G) :=
  fun a =>
    ⟨φ a, Subgroup.le_topologicalClosure _
      (Subgroup.subset_closure ⟨a, rfl⟩)⟩

/-- **The canonical family topologically generates its closed generated
subgroup** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:49`). -/
theorem closedSubgroupGeneratedMap_topologicallyGenerates {A : Type v}
    (φ : A → G) :
    TopologicallyGenerates
      (G := (closedSubgroupGenerated (G := G) (Set.range φ) : Subgroup G))
      (Set.range (closedSubgroupGeneratedMap (G := G) φ)) := by
  let K : ClosedSubgroup G := closedSubgroupGenerated (G := G) (Set.range φ)
  let φK : A → (K : Subgroup G) := closedSubgroupGeneratedMap (G := G) φ
  let L : Subgroup (K : Subgroup G) := Subgroup.closure (Set.range φK)
  have hmap :
      Subgroup.map (K : Subgroup G).subtype L =
        Subgroup.closure (Set.range φ) := by
    refine le_antisymm ?_ ?_
    · rw [Subgroup.map_le_iff_le_comap, Subgroup.closure_le]
      rintro y ⟨a, rfl⟩
      exact Subgroup.subset_closure ⟨a, rfl⟩
    · rw [Subgroup.closure_le]
      rintro y ⟨a, rfl⟩
      change φ a ∈ Subgroup.map (K : Subgroup G).subtype L
      exact ⟨φK a, Subgroup.subset_closure ⟨a, rfl⟩, rfl⟩
  have himage :
      ((Subtype.val : ↥(K : Subgroup G) → G) ''
          ((L : Subgroup ↥(K : Subgroup G)) : Set ↥(K : Subgroup G))) =
        ((Subgroup.map (K : Subgroup G).subtype L : Subgroup G) : Set G) := by
    ext y
    constructor
    · rintro ⟨z, hz, rfl⟩
      exact ⟨z, hz, rfl⟩
    · rintro ⟨z, hz, hzy⟩
      exact ⟨z, hz, hzy⟩
  rw [topologicallyGenerates_iff_dense, dense_iff_closure_eq]
  ext y
  constructor
  · intro _
    simp only [mem_univ]
  · intro _
    change y ∈ closure ((L : Subgroup K) : Set K)
    rw [closure_subtype]
    change (y : G) ∈
      closure
        (((Subtype.val : ↥(K : Subgroup G) → G) ''
          ((L : Subgroup ↥(K : Subgroup G)) : Set ↥(K : Subgroup G))))
    rw [himage, hmap]
    change (y : G) ∈
      ((Subgroup.closure (Set.range φ)).topologicalClosure : Set G)
    exact y.2

/-- **Membership in a closed generated subgroup pushes along a continuous
homomorphism**, after mapping the generating set (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:97`). -/
theorem map_mem_closedSubgroupGenerated_image
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) {X : Set G} {y : G}
    (hy : y ∈ (closedSubgroupGenerated (G := G) X : Subgroup G)) :
    φ y ∈ (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H) := by
  let K : Subgroup G :=
    (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H).comap
      (φ : G →* H)
  have hX : X ⊆ K := by
    intro x hx
    exact Subgroup.le_topologicalClosure _
      (Subgroup.subset_closure ⟨x, hx, rfl⟩)
  have hKclosed : IsClosed (K : Set G) := by
    change IsClosed {x : G | φ x ∈
      (closedSubgroupGenerated (G := H) (φ '' X) : Subgroup H)}
    exact (closedSubgroupGenerated (G := H) (φ '' X)).isClosed'.preimage
      φ.continuous
  exact
    (Subgroup.topologicalClosure_minimal _
      ((Subgroup.closure_le (K := K)).2 hX) hKclosed) hy

/-- **The singleton form of the functoriality of closed topological
generation** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:119`). -/
theorem map_mem_closedSubgroupGenerated_singleton
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) (x : G) {y : G}
    (hy : y ∈
      (closedSubgroupGenerated (G := G) ({x} : Set G) : Subgroup G)) :
    φ y ∈
      (closedSubgroupGenerated (G := H) ({φ x} : Set H) : Subgroup H) := by
  simpa using
    (map_mem_closedSubgroupGenerated_image (G := G) (H := H) φ
      (X := ({x} : Set G)) hy)

/-- **A group with a dense image of the infinite cyclic group is
topologically generated by the image of the generator
`Multiplicative.ofAdd 1`** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:132`). -/
theorem topologicallyGenerates_singleton_of_denseRange_mint
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : Multiplicative ℤ →* H) (hf : DenseRange f) :
    TopologicallyGenerates
      (G := H) ({f (Multiplicative.ofAdd 1)} : Set H) := by
  let g : H := f (Multiplicative.ofAdd 1)
  have hsubset :
      Set.range f ⊆
        (((Subgroup.closure ({g} : Set H)).topologicalClosure :
          Subgroup H) : Set H) := by
    intro y hy
    rcases hy with ⟨n, rfl⟩
    have hz : f n ∈ Subgroup.zpowers g := by
      have hEq : f n = g ^ n.toAdd := by
        simpa [g] using (MonoidHom.apply_mint (f := f) (n := n))
      rw [hEq]
      exact (Subgroup.zpowers g).zpow_mem (Subgroup.mem_zpowers g) n.toAdd
    exact Subgroup.le_topologicalClosure _
      (by simpa [g, Subgroup.zpowers_eq_closure] using hz)
  have hclosure :
      closure (Set.range f) ⊆
        (((Subgroup.closure ({g} : Set H)).topologicalClosure :
          Subgroup H) : Set H) :=
    closure_minimal hsubset (Subgroup.isClosed_topologicalClosure _)
  rw [TopologicallyGenerates]
  apply top_unique
  intro x _hx
  have hx' : x ∈ closure (Set.range f) := by
    rw [hf.closure_range]
    simp only [mem_univ]
  exact hclosure hx'

/-- **Topological generation pushes forward along a continuous surjective
homomorphism** (Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:166`). -/
theorem topologicallyGenerates_image_of_continuousSurjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (f : G →* H) (hf : Continuous f) (hfsurj : Function.Surjective f)
    {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates (G := H) (f '' X) := by
  have hmap :
      (Subgroup.closure X).map f = Subgroup.closure (f '' X) := by
    simpa using MonoidHom.map_closure f X
  have htop :
      ((Subgroup.closure X).map f).topologicalClosure = ⊤ := by
    exact DenseRange.topologicalClosure_map_subgroup
      (f := f) (hf := hf) (hf' := hfsurj.denseRange)
      (by simpa [TopologicallyGenerates] using hX)
  rw [TopologicallyGenerates, ← hmap]
  exact htop

/-- **Topological generation descends to a quotient by a normal subgroup**
(Yamaguchi 2026,
`AbstractClassFieldTheory/Degree/TopologicalGeneration.lean:183`). -/
theorem topologicallyGenerates_quotient_image
    (N : Subgroup G) [N.Normal]
    {X : Set G} (hX : TopologicallyGenerates (G := G) X) :
    TopologicallyGenerates
      (G := G ⧸ N) ((QuotientGroup.mk' N) '' X) :=
  topologicallyGenerates_image_of_continuousSurjective
    (G := G) (H := G ⧸ N) (QuotientGroup.mk' N)
    continuous_quotient_mk' (QuotientGroup.mk'_surjective N) hX

end Atlas.Knowledge
