import Mathlib
import Atlas.Knowledge.IsMixedCharLocalField

/-!
# generation by uniformizers

The unit group of a mixed-characteristic local field is generated by its uniformizers.
Every integer unit is a quotient of two uniformizers; the discrete-valuation factorization
then handles every nonzero field element.

## Main statements

* `uniformizerUnits_generate` — uniformizer units generate the field's multiplicative group.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer New
  York, 1979.
-/

open ValuativeRel

namespace Atlas.Knowledge

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsMixedCharLocalField K]

/-- Uniformizers generate the field's multiplicative group
([Serre 1979, Chap. I, §1, pp.1–3][Serre1979]). -/
theorem uniformizerUnits_generate :
    Subgroup.closure
        {u : Kˣ | ∃ hu : (u : K) ∈ 𝒪[K], Irreducible (⟨(u : K), hu⟩ : 𝒪[K])} =
      (⊤ : Subgroup Kˣ) := by
  rw [Subgroup.eq_top_iff']
  intro x
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  have hinj : Function.Injective (algebraMap 𝒪[K] K) := IsFractionRing.injective 𝒪[K] K
  have hne : ∀ a : 𝒪[K], a ≠ 0 → algebraMap 𝒪[K] K a ≠ 0 := fun a ha h0 =>
    ha (hinj (by rwa [map_zero]))
  -- irreducible integers give elements of the generating set
  have hSmem : ∀ (a : 𝒪[K]) (ha : Irreducible a) (h0 : algebraMap 𝒪[K] K a ≠ 0),
      Units.mk0 (algebraMap 𝒪[K] K a) h0 ∈
        {u : Kˣ | ∃ hu : (u : K) ∈ 𝒪[K], Irreducible (⟨(u : K), hu⟩ : 𝒪[K])} := by
    intro a ha h0
    refine ⟨a.2, ?_⟩
    have : (⟨((Units.mk0 (algebraMap 𝒪[K] K a) h0 : Kˣ) : K), a.2⟩ : 𝒪[K]) = a :=
      Subtype.ext rfl
    rwa [this]
  -- units of the integers are quotients of two irreducibles
  have hunit : ∀ w : 𝒪[K]ˣ, ∀ h0 : algebraMap 𝒪[K] K (w : 𝒪[K]) ≠ 0,
      Units.mk0 (algebraMap 𝒪[K] K (w : 𝒪[K])) h0 ∈ Subgroup.closure
        {u : Kˣ | ∃ hu : (u : K) ∈ 𝒪[K], Irreducible (⟨(u : K), hu⟩ : 𝒪[K])} := by
    intro w h0
    have hirr2 : Irreducible ((w : 𝒪[K]) * ϖ) :=
      Associated.irreducible ⟨w, mul_comm ϖ (w : 𝒪[K])⟩ hϖ
    have hϖ0 : algebraMap 𝒪[K] K ϖ ≠ 0 := hne ϖ hϖ.ne_zero
    have hwϖ0 : algebraMap 𝒪[K] K ((w : 𝒪[K]) * ϖ) ≠ 0 := hne _ hirr2.ne_zero
    have hsplit : Units.mk0 (algebraMap 𝒪[K] K (w : 𝒪[K])) h0 =
        Units.mk0 (algebraMap 𝒪[K] K ((w : 𝒪[K]) * ϖ)) hwϖ0 *
          (Units.mk0 (algebraMap 𝒪[K] K ϖ) hϖ0)⁻¹ := by
      ext
      simp only [Units.val_mul, Units.val_inv_eq_inv_val, Units.val_mk0, map_mul]
      rw [mul_inv_cancel_right₀ hϖ0]
    rw [hsplit]
    exact Subgroup.mul_mem _
      (Subgroup.subset_closure (hSmem _ hirr2 hwϖ0))
      (Subgroup.inv_mem _ (Subgroup.subset_closure (hSmem _ hϖ hϖ0)))
  -- factor an arbitrary unit of the field
  have hx0 : (x : K) ≠ 0 := Units.ne_zero x
  obtain ⟨n, u, hu⟩ :=
    IsDiscreteValuationRing.exists_units_eq_smul_zpow_of_irreducible hϖ hx0
  have hϖ0 : algebraMap 𝒪[K] K ϖ ≠ 0 := hne ϖ hϖ.ne_zero
  have hu0 : algebraMap 𝒪[K] K (u : 𝒪[K]) ≠ 0 := hne _ (Units.ne_zero u)
  have hxeq : x = Units.mk0 (algebraMap 𝒪[K] K (u : 𝒪[K])) hu0 *
      (Units.mk0 (algebraMap 𝒪[K] K ϖ) hϖ0) ^ (n : ℤ) := by
    ext
    push_cast [hu, Units.smul_def, Algebra.smul_def]
    rfl
  rw [hxeq]
  exact Subgroup.mul_mem _ (hunit u hu0)
    (Subgroup.zpow_mem _ (Subgroup.subset_closure (hSmem ϖ hϖ hϖ0)) n)

end Atlas.Knowledge
