import Mathlib
import Atlas.Knowledge.FrobeniusElements
import Atlas.Knowledge.NormalizedDegree

/-!
# generators of unramified quotients

In a finite unramified Galois extension, the restriction of any element of
normalized degree one generates the Galois quotient: correcting a
Frobenius-semigroup preimage by an inertia element moves it into the
subgroup, so every class is a power of the restriction. Surjectivity of
the normalized degree then supplies such a generator outright — the
cyclicity input of the unit-cohomology axiom (#104).

## Main statements

* `DegreeData.quotient_generator_of_unramified_degree_one` — a degree-one
  element restricts to a generator; proved.
* `DegreeData.exists_quotient_generator_of_unramified` — a finite
  unramified Galois quotient has a degree-one generator; proved.

## References

* [Yamaguchi2026] n-yamaguchi-0729, *ClassFieldTheory: local and global class field theory
  in Lean 4*, GitHub repository, pinned commit `6010237`, 2026.
-/

namespace Atlas.Knowledge

noncomputable section

universe u

variable {G : Type u} [Group G] [TopologicalSpace G]

namespace DegreeData

/-- **A degree-one element restricts to a generator of a finite unramified
Galois quotient** ([Yamaguchi 2026,
`AbstractClassFieldTheory/Reciprocity/Construction/ReciprocityIndependence.lean:269`]
[Yamaguchi2026]). -/
theorem quotient_generator_of_unramified_degree_one (D : DegreeData G)
    (K : FiniteResidueAbstractField D) (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    [hfinite : Finite
      (K.field.toSubgroup ⧸ L.toSubgroup.subgroupOf K.field.toSubgroup)]
    (hUnramified :
      (⟨L, K.field, hLK⟩ : AbstractExtension G).IsUnramified D)
    (φ : K.field.toSubgroup)
    (hφ : D.normalizedDegree K φ =
      Multiplicative.ofAdd (1 : ProfiniteInteger)) :
    ∀ x : K.field.toSubgroup ⧸ L.toSubgroup.subgroupOf K.field.toSubgroup,
      x ∈ Subgroup.zpowers (QuotientGroup.mk φ) := by
  intro x
  obtain ⟨q, hqx⟩ := D.frobeniusRestriction_surjective K L hLK x
  obtain ⟨n, _hn, hdegree⟩ := q.2
  let t : K.field.toSubgroup := Quotient.out q.1
  have htq :
      (QuotientGroup.mk t :
        K.field.toSubgroup ⧸
          D.extensionInertiaWithin K.field L hLK) = q.1 :=
    Quotient.out_eq' q.1
  have hdt : D.normalizedDegree K t =
      (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n := by
    calc
      D.normalizedDegree K t =
          D.extensionNormalizedDegree K L hLK
            (QuotientGroup.mk t) := rfl
      _ = D.extensionNormalizedDegree K L hLK q.1 :=
        congrArg (D.extensionNormalizedDegree K L hLK) htq
      _ = _ := hdegree
  let z : K.field.toSubgroup := t⁻¹ * φ ^ n
  have hzI : z ∈ D.fieldInertiaWithin K.field := by
    rw [← D.normalizedDegree_ker K]
    change D.normalizedDegree K z = 1
    calc
      D.normalizedDegree K z =
          (D.normalizedDegree K t)⁻¹ *
            (D.normalizedDegree K φ) ^ n := by
        simp [z, map_mul, map_inv, map_pow]
      _ = ((Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n)⁻¹ *
            (Multiplicative.ofAdd (1 : ProfiniteInteger)) ^ n := by
        rw [hdt, hφ]
      _ = 1 := by simp
  have hzL : z.1 ∈ L.toSubgroup :=
    ((⟨L, K.field, hLK⟩ :
        AbstractExtension G).isUnramified_iff_inertia_le D).1
      hUnramified ⟨z.2, hzI⟩
  have hzE : z ∈ L.toSubgroup.subgroupOf K.field.toSubgroup :=
    Subgroup.mem_subgroupOf.2 hzL
  have htgen :
      (QuotientGroup.mk t : K.field.toSubgroup ⧸
        L.toSubgroup.subgroupOf K.field.toSubgroup) =
        (QuotientGroup.mk φ) ^ n := by
    apply QuotientGroup.eq.mpr
    simpa [z] using hzE
  have htx :
      (QuotientGroup.mk t : K.field.toSubgroup ⧸
        L.toSubgroup.subgroupOf K.field.toSubgroup) = x := by
    calc
      QuotientGroup.mk t = D.extensionRestriction K.field L hLK
          (QuotientGroup.mk t) := rfl
      _ = D.extensionRestriction K.field L hLK q.1 :=
        congrArg (D.extensionRestriction K.field L hLK) htq
      _ = x := hqx
  have hxpow : x = (QuotientGroup.mk φ) ^ n := htx.symm.trans htgen
  rw [hxpow]
  exact Subgroup.mem_zpowers_iff.mpr ⟨(n : ℤ), by simp⟩

/-- **A finite unramified Galois quotient is generated by the restriction
of an element of normalized degree one** — the cyclicity input of the
unit-cohomology axiom ([Yamaguchi 2026,
`AbstractClassFieldTheory/Reciprocity/Construction/ReciprocityIndependence.lean:338`]
[Yamaguchi2026]). -/
theorem exists_quotient_generator_of_unramified
    (D : DegreeData G) (K : FiniteResidueAbstractField D)
    (L : ClosedSubgroup G)
    (hLK : L.toSubgroup ≤ K.field.toSubgroup)
    [hnormal : (L.toSubgroup.subgroupOf K.field.toSubgroup).Normal]
    [hfinite : Finite
      (K.field.toSubgroup ⧸ L.toSubgroup.subgroupOf K.field.toSubgroup)]
    (hUnramified :
      (⟨L, K.field, hLK⟩ : AbstractExtension G).IsUnramified D) :
    ∃ g : K.field.toSubgroup ⧸ L.toSubgroup.subgroupOf K.field.toSubgroup,
      ∀ x, x ∈ Subgroup.zpowers g := by
  obtain ⟨φ, hφ⟩ := D.normalizedDegree_surjective K
    (Multiplicative.ofAdd (1 : ProfiniteInteger))
  refine ⟨QuotientGroup.mk φ, ?_⟩
  exact D.quotient_generator_of_unramified_degree_one
    K L hLK hUnramified φ hφ

end DegreeData

end

end Atlas.Knowledge
